START TRANSACTION;

DROP TEMPORARY TABLE IF EXISTS tmp_economic_calendar_import;

CREATE TEMPORARY TABLE tmp_economic_calendar_import (
    date_value DATE NULL,
    time_value VARCHAR(50) NULL,
    country VARCHAR(50) NULL,
    impact VARCHAR(20) NULL,
    figures VARCHAR(255) NULL,
    previous_value VARCHAR(100) NULL,
    forecast_value VARCHAR(100) NULL,
    actual_value VARCHAR(100) NULL,
    sources TEXT NULL,
    measures LONGTEXT NULL,
    usual_effect LONGTEXT NULL,
    frequency LONGTEXT NULL,
    next_released VARCHAR(100) NULL,
    notes LONGTEXT NULL,
    isBankHoliday TINYINT(1) NOT NULL DEFAULT 0,
    bankHolidayNote LONGTEXT NULL,
    why_trader_care LONGTEXT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

INSERT INTO
    tmp_economic_calendar_import (
        date_value,
        time_value,
        country,
        impact,
        figures,
        previous_value,
        forecast_value,
        actual_value,
        sources,
        measures,
        usual_effect,
        frequency,
        next_released,
        notes,
        isBankHoliday,
        bankHolidayNote,
        why_trader_care
    )
VALUES (
        '2026-03-23',
        '21.00',
        'US',
        'Low',
        'Construction Spending m/m',
        '0.8%',
        '0.1%',
        '-0.3%',
        'Biro Sensus',
        'Perubahan total jumlah pengeluaran dari pengembang rumah yang dibelanjakan untuk proyek-proyek konstruksi.',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 30 hari setelah bulan berjalan',
        'No Information',
        '-',
        0,
        NULL,
        '-'
    ),
    (
        '2026-03-23',
        '22.00',
        'EUR',
        'Low',
        'Consumer Confidence',
        '-12',
        '-15',
        '-16',
        'Komisi Statistik Wilayah Euro (Eurostat)',
        'Tingkat indeks difusi berdasarkan konsumen yang disurvei;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 22 hari setelah bulan berjalan',
        'No Information',
        'Di atas 0 menunjukkan optimisme, di bawah menunjukkan pesimisme. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Januari 2010, merupakan rilis paling awal dan cenderung memiliki dampak paling besar. Final tidak dilaporkan karena kurang penting;',
        0,
        NULL,
        'Kepercayaan finansial merupakan indikator utama belanja konsumen, yang menyumbang sebagian besar aktivitas perekonomian secara keseluruhan;'
    ),
    (
        '2026-03-24',
        '05.00',
        'AUD',
        'Low',
        'Flash Manufacturing PMI',
        '51.0',
        NULL,
        '50.1',
        'Markit (rilis terbaru)',
        'Tingkat indeks difusi berdasarkan manajer pembelian yang disurvei di industri manufaktur;',
        '''Sebenarnya'' lebih besar dari ''Prakiraan'' baik untuk mata uang;',
        'Dirilis setiap bulan, sekitar 3 minggu ke bulan saat ini;',
        'No Information',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada Oktober 2018, merupakan rilis paling awal sehingga cenderung memiliki dampak paling besar. Final tidak disertakan karena kurang penting;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-03-24',
        '05.00',
        'AUD',
        'Low',
        'Flash Services PMI',
        '52.8',
        NULL,
        '46.6',
        'S&P Global',
        'Tingkat indeks difusi berdasarkan survei manajer pembelian di industri jasa;',
        '''Actual'' greater than ''Forecast'' is good for currency;',
        'Dirilis setiap bulan, sekitar 3 minggu setelah bulan berjalan;',
        'No Information',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada Oktober 2018, merupakan rilis paling awal sehingga cenderung memiliki dampak paling besar. Final tidak disertakan karena kurang penting;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-03-24',
        '06.30',
        'JPN',
        'Low',
        'National Core CPI y/y',
        '2.0%',
        '1.7%',
        '1.6%',
        'Biro Statistik',
        'Perubahan harga barang dan jasa yang dibeli konsumen, tidak termasuk pangan segar;',
        'Aktual > Perkiraan = Positif',
        'RIlis bulanan, biasanya pada Jumat terakhir dari periode bulan berjalan',
        'No Information',
        '-',
        0,
        NULL,
        '-'
    ),
    (
        '2026-03-24',
        '07.30',
        'JPN',
        'Low',
        'Flash Manufacturing PMI (JPN)',
        '53.0',
        '52.9',
        NULL,
        'S&P Global',
        'Tingkat indeks difusi berdasarkan manajer pembelian yang disurvei dalam industri manufaktur; Survei dari sekitar 400 manajer pembelian yang dimintai respon untuk menilai tingkat relatif dari kondisi bisnis termasuk ketenagakerjaan, produksi, pesanan bar',
        'Aktual > Perkiraan = Cenderung positif untuk mata uang (USD)',
        'Dirilis bulanan, sekitar 3 minggu dari bulan berjalan',
        'No Information',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Mei 2014, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-03-24',
        '15.15',
        'EUR',
        'Medium',
        'French Flash Manufacturing PMI',
        '50.1',
        '49.4',
        '50.2',
        'S&P Global',
        'Tingkat indeks difusi berdasarkan survei manajer pembelian di industri manufaktur;',
        '''Aktual'' lebih besar dari ''Perkiraan'' bagus untuk mata uang;',
        'Dirilis setiap bulan, sekitar 3 minggu setelah bulan berjalan;',
        'No Information',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Maret 2008, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-03-24',
        '15.30',
        'EUR',
        'High',
        'German Flash Manufacturing PMI',
        '50.9',
        '49.6',
        '51.7',
        'S&P Global',
        'Tingkat indeks difusi berdasarkan survei manajer pembelian di industri manufaktur;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 3 minggu dalam bulan berjalan',
        'No Information',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Maret 2008, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-03-24',
        '15.30',
        'EUR',
        'High',
        'German Flash Services PMI',
        '53.5',
        '52.5',
        '51.2',
        'S&P Global',
        'Tingkat indeks difusi berdasarkan survei manajer pembelian di industri jasa;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 3 minggu dalam bulan berjalan',
        'No Information',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Maret 2008, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-03-24',
        '16.00',
        'EUR',
        'Low',
        'Flash Manufacturing PMI (EUR)',
        '50.8',
        '49.5',
        '51.4',
        'S&P Global',
        'Tingkat indeks difusi berdasarkan survei manajer pembelian di industri manufaktur;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 3 minggu dalam bulan berjalan',
        'No Information',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Juni 2007, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-03-24',
        '16.00',
        'EUR',
        'Low',
        'Flash Services PMI',
        '51.9',
        '51.1',
        '50.1',
        'S&P Global',
        'Tingkat indeks difusi berdasarkan survei manajer pembelian di industri jasa;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 3 minggu dalam bulan berjalan',
        'No Information',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Maret 2008, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-03-24',
        '16.30',
        'GBP',
        'Medium',
        'Flash Services PMI',
        '53.9',
        '52.8',
        '51.2',
        'S&P Global',
        'Tingkat indeks difusi berdasarkan survei manajer pembelian di industri jasa;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 3 minggu dalam bulan berjalan',
        'No Information',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Juni 2007, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-03-24',
        '16.30',
        'GBP',
        'High',
        'Flash Manufacturing PMI',
        '51.7',
        '50.0',
        '51.4',
        'Markit (latest release)',
        'Tingkat indeks difusi berdasarkan manajer pembelian yang disurvei di industri manufaktur;',
        '''Sebenarnya'' lebih besar dari ''Prakiraan'' baik untuk mata uang;',
        'Dirilis setiap bulan, sekitar 3 minggu ke bulan saat ini;',
        'No Information',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada November 2019, merupakan rilis paling awal sehingga cenderung memiliki dampak paling besar;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-03-24',
        '16.30',
        'GBP',
        'High',
        'Flash Services PMI (GBP)',
        '53.9',
        '52.8',
        '51.2',
        'Markit (latest release)',
        'Tingkat indeks difusi berdasarkan manajer pembelian yang disurvei di industri jasa;',
        '''Aktual'' lebih besar dari ''Perkiraan'' bagus untuk mata uang;',
        'Dirilis setiap bulan, sekitar 3 minggu ke bulan saat ini;',
        'No Information',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada November 2019, merupakan rilis paling awal sehingga cenderung memiliki dampak paling besar;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-03-24',
        '18.00',
        'GBP',
        'Low',
        'CBI Realized Sales',
        '-43',
        '-43',
        '-52',
        'Konfederasi Industri Inggris (Confederation of British Industry)',
        'Tingkat indeks difusi berdasarkan pengecer yang disurvei dan grosir',
        'Aktual > Perkiraan = Bagus untuk mata uang',
        'Dirilis bulanan, sekitar akhir bulan berjalan',
        'No Information',
        'Di atas 0 menunjukkan volume penjualan yang lebih tinggi, di bawah 0 menunjukkan lebih rendah. Sumber berubah formula perhitungan seri sebagai Juli 2009',
        0,
        NULL,
        'Ini adalah indikator utama belanja konsumen karena pengecer dan penjualan grosir secara langsung dipengaruhi oleh tingkat pembelian konsumen'
    ),
    (
        '2026-03-24',
        '19.15',
        'US',
        'Low',
        'ADP Weekly Employment Change',
        '9.0K',
        NULL,
        '10.0K',
        'Automatic Data Processing, Inc. (latest release)',
        'Estimated average weekly change in the number of employed people during the previous 4 weeks, excluding the farming industry and government;',
        '''Actual'' greater than ''Forecast'' is good for currency;',
        'Released weekly, on the first Tuesday about 2 weeks after the rolling four-week period ends;',
        'No Information',
        'This is high-frequency private-sector employment data based on a rolling four-week average, and tends to be more volatile than the monthly ADP Employment Report. The release is skipped in any week that overlaps with publication of the monthly ADP Employment Report. Source first released in Oct 2025;',
        0,
        NULL,
        'Job creation is an important leading indicator of consumer spending, which accounts for a majority of overall economic activity;'
    ),
    (
        '2026-03-24',
        '19.30',
        'US',
        'Low',
        'Revised Nonfarm Productivity q/q',
        '2.8%',
        '2.4%',
        '1.8%',
        'Biro Statistik Tenaga Kerja',
        'Perubahan tahunan dari efisiensi tenaga kerja ketika memproduksi barang dan jasa, termasuk dari industri pertanian; Meskipun ini adalah data kuartalan (q/q), namun dilaporkan dalam format tahunan (perubahan kuartalan x4); Ada 2 versi laporan yang dir',
        'Aktual aan = Poairif',
        'Rilis kuartalan, sekitar 65 hari setelah kuartal berakhir',
        'No Information',
        'Meskipun ini adalah data q/q, namun dilaporkan dalam format tahunan (perubahan triwulanan x4). ''Sebelumnya'' yang tercantum adalah ''Aktual'' dari rilis Awal dan oleh karena itu data ''Riwayat'' akan tampak tidak berhubungan. Ada 2 versi laporan ini yang dirilis dengan jarak satu bulan ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Awal dan Revisi. Rilis Awal adalah yang paling awal dan dengan demikian cenderung memiliki dampak paling besar;',
        0,
        NULL,
        'Produktivitas dan inflasi terkait tenaga kerja saling terkait secara langsung - penurunan produktivitas pekerja setara dengan kenaikan upah mereka. Ketika perusahaan membayar lebih untuk tenaga kerja, biaya yang lebih tinggi biasanya dibebankan kepada konsumen;'
    ),
    (
        '2026-03-24',
        '19.30',
        'US',
        'Low',
        'Revised Unit Labor Costs q/q',
        '2.8%',
        '3.4%',
        '4.4%',
        'Biro Statistik Tenaga Kerja',
        'Perubahan tahunan dari harga yang dibayarkan oleh pebisnis kepada tenaga kerja, namun tidak termasuk pada industri pertanian;',
        'Aktual > Perkiraan = Positif',
        'Rilis kuartalan, sekitar 65 hari setelah kuartal berakhir',
        'No Information',
        'Meskipun ini adalah data q/q, namun dilaporkan dalam format tahunan (perubahan triwulanan x4). ''Sebelumnya'' yang tercantum adalah ''Aktual'' dari rilis Awal dan oleh karena itu data ''Riwayat'' akan tampak tidak berhubungan. Ada 2 versi laporan ini yang dirilis dengan jarak satu bulan ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Awal dan Revisi. Rilis Awal adalah yang paling awal dan dengan demikian cenderung memiliki dampak paling besar;',
        0,
        NULL,
        '-'
    ),
    (
        '2026-03-24',
        '20.45',
        'US',
        'High',
        'Flash Manufacturing PMI (US)',
        '51.6',
        '51.5',
        '52.4',
        'S&P Global',
        'Tingkat indeks difusi berdasarkan survei terhadap manajer pembelian dalam industri manufaktur;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 3 minggu dalam bulan berjalan',
        'No Information',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Mei 2012, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-03-24',
        '20.45',
        'US',
        'High',
        'Flash Services PMI (US)',
        '51.7',
        '52.0',
        '51.1',
        'S&P Global',
        'Tingkat indeks difusi berdasarkan survei terhadap manajer pembelian dalam industri jasa;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 3 minggu dalam bulan berjalan',
        'No Information',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan November 2013, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-03-24',
        '21.00',
        'US',
        'Medium',
        'Richmond Manufacturing Index',
        '-10',
        '-5',
        '0',
        'Federal Reserve Bank of Richmond',
        'Tingkat indeks komposit berdasarkan produsen yang disurvei di wilayah Richmond;',
        'AKtual > Perkiraan = Positif',
        'Dirilis setiap bulan, pada hari Selasa keempat bulan berjalan;',
        'No Information',
        'Di atas 0 menunjukkan kondisi membaik, di bawah menunjukkan kondisi memburuk. Cenderung memiliki dampak yang tidak terlalu besar karena terdapat indikator regional yang terkait dengan kondisi manufaktur sebelumnya;',
        0,
        NULL,
        '-'
    ),
    (
        '2026-03-25',
        '06.50',
        'JPN',
        'Low',
        'Monetary Policy Meeting Minutes (JPN)',
        NULL,
        NULL,
        NULL,
        'Bank of Japan',
        'Ini adalah catatan rinci dari pertemuan Kebijakan Dewan Bank of Japan, memberikan wawasan mendalam terhadap kondisi ekonomi yang bisa mempengaruhi keputusan mereka untuk menetapkan tingkat suku bunga.',
        'Lebih hawkish dari pada perkiraan biasanya akan direspon negatif oleh pasar, tapi bila lebih dovish dibandingkan perkiraan biasanya akan direspon positif.',
        'Variabel, sekitar 14 kali dalam setahun, 30-50 hari setelah pengumuman suku bunga antar bank (Overnight Call Rate)',
        'No Information',
        NULL,
        0,
        NULL,
        NULL
    ),
    (
        '2026-03-25',
        '07.30',
        'AUD',
        'High',
        'CPI y/y (AUD)',
        '3.8%',
        '3.8%',
        '3.7%',
        'Australian Bureau of Statistics',
        'Perubahan harga barang dan jasa yang dibeli konsumen;',
        '''Actual'' greater than ''Forecast'' is good for currency;',
        'Dirilis setiap bulan, sekitar 25 hari setelah bulan berakhir;',
        'No Information',
        'Angka ini merupakan salah satu dari sedikit angka penyesuaian non-musiman yang dilaporkan dalam kalender. Sumber pertama kali dirilis pada Oktober 2022;',
        0,
        NULL,
        'Harga konsumen menyumbang sebagian besar inflasi secara keseluruhan. Inflasi penting dalam penilaian mata uang karena kenaikan harga menyebabkan bank sentral menaikkan suku bunga untuk pengendalian inflasi;'
    ),
    (
        '2026-03-25',
        '07.30',
        'AUD',
        'High',
        'CPI m/m',
        '0.4%',
        '0.1%',
        '0.0%',
        'Australian Bureau of Statistics (latest release)',
        '-',
        '''Actual'' greater than ''Forecast'' is good for currency;',
        'Released monthly, about 25 days after the month ends;',
        'No Information',
        'Ini rilis inflasi yang paling penting, karena keluar paling cepat dibanding indikator inflasi lain dan cakupannya luas (ngukur banyak komponen harga di ekonomi, bukan cuma satu sektor). Angka ini termasuk sedikit data yang dilaporkan dalam bentuk “non-seasonally adjusted (NSA)” → artinya belum “dibersihkan” dari pola musiman (misal efek Lebaran, akhir tahun, musim liburan), jadi bisa terlihat lebih “naik-turun” secara alami. Sumber data mengubah frekuensi rilis dari triwulan (quarterly) jadi bulanan (monthly) → data jadi lebih sering keluar, tapi historinya bisa terasa “beda ritme” karena sebelumnya lebih jarang.',
        0,
        NULL,
        'Data inflasi konsumen penting karena mewakili porsi besar inflasi. Kenaikan inflasi biasanya mendorong bank sentral menaikkan suku bunga untuk menahan laju harga, yang dapat memperkuat mata uang lewat kenaikan imbal hasil aset domestik.'
    ),
    (
        '2026-03-25',
        '07.30',
        'AUD',
        'High',
        'Trimmed Mean CPI m/m',
        '0.3%',
        '0.3%',
        '0.2%',
        'Reserve Bank of Australia (latest release)',
        'Perubahan harga barang dan jasa yang dibeli oleh konsumen, tidak termasuk 30% barang yang paling fluktuatif;',
        'Angka ''aktual'' yang lebih besar dari angka ''prakiraan'' baik untuk mata uang;',
        'Dirilis setiap bulan, sekitar 25 hari setelah bulan berakhir;',
        'No Information',
        'Data ini mewakili tren inflasi yang mendasari melalui pembobotan komponen dan pengecualian anomali. Ini adalah salah satu dari sedikit angka yang tidak disesuaikan secara musiman yang dilaporkan pada kalender. Sumber mengubah frekuensi rilis dari triwulanan menjadi bulanan dan mengubah rumus perhitungan seri mulai Januari 2026;',
        0,
        NULL,
        'Harga konsumen menyumbang sebagian besar inflasi secara keseluruhan. Inflasi penting bagi valuasi mata uang karena kenaikan harga menyebabkan bank sentral menaikkan suku bunga sebagai bentuk penghormatan terhadap mandat pengendalian inflasi mereka;'
    ),
    (
        '2026-03-25',
        '14.00',
        'GBP',
        'High',
        'CPI y/y (GBP)',
        '3.0%',
        '3.0%',
        '3.0%',
        'Kantor Statistik Federal',
        'Perubahan harga barang dan jasa yang dibeli oleh konsumen;',
        'Actual > Forecast = Bagus untuk mata uang',
        'Rilis bulanan, sekitar 16 hari setelah bulan berakhir',
        'No Information',
        'Data ini dianggap sebagai data inflasi paling penting di Inggris karena digunakan sebagai target inflasi bank sentral (BOE);',
        0,
        NULL,
        'Harga konsumen menyumbang sebagian besar inflasi secara keseluruhan. Inflasi penting dalam penilaian mata uang karena kenaikan harga menyebabkan bank sentral menaikkan suku bunga untuk menghormati mandat pengendalian inflasi;'
    ),
    (
        '2026-03-25',
        '14.00',
        'GBP',
        'Low',
        'Core CPI y/y',
        '3.1%',
        '3.1%',
        '3.2%',
        'Komisi Statistik Wilayah Euro (Eurostat)',
        'Perubahan harga barang dan jasa yang dibeli konsumen, tidak termasuk produk makanan yang mudah menguap, energi, alkohol, dan tembakau;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 16 hari setelah bulan berakhir',
        'No Information',
        'Data Inti mempunyai dampak yang kecil jika dibandingkan dengan negara lain karena keseluruhan CPI merupakan target inflasi yang diamanatkan oleh bank sentral;',
        0,
        NULL,
        '-'
    ),
    (
        '2026-03-25',
        '14.00',
        'GBP',
        'Low',
        'PPI Input m/m',
        '0.4%',
        '0.5%',
        '0.8%',
        'Kantor Statistik Nasional',
        'Perubahan harga barang dan bahan baku yang dibeli oleh produsen;',
        'Actual > Forecast = Bagus untuk mata uang',
        'Rilis bulanan, sekitar 15 hari setelah bulan berakhir',
        'No Information',
        '-',
        0,
        NULL,
        'Ini adalah indikator utama inflasi konsumen - ketika produsen membayar lebih untuk biaya barang yang lebih tinggi biasanya biaya tersebut akan diteruskan kepada konsumen;'
    ),
    (
        '2026-03-25',
        '14.00',
        'GBP',
        'Low',
        'PPI Output m/m',
        '0.0%',
        '0.3%',
        '-0.5%',
        'Office for National Statistics (latest release)',
        'Perubahan harga barang yang dijual oleh produsen;',
        '''Actual'' greater than ''Forecast'' is good for currency;',
        'Dirilis setiap bulan, sekitar 15 hari setelah bulan berakhir;',
        'No Information',
        'Hanya mencakup barang yang diproduksi di dalam negeri;',
        0,
        NULL,
        '-'
    ),
    (
        '2026-03-25',
        '14.00',
        'GBP',
        'Low',
        'RPI y/y',
        '3.8%',
        '3.7%',
        '3.6%',
        'Kantor Statistik Nasional',
        'Perubahan harga barang dan jasa yang dibeli oleh konsumen untuk tujuan konsumsi;',
        'Actual > Forecast = Bagus untuk mata uang',
        'Rilis bulanan, sekitar 16 hari setelah bulan berakhir',
        'No Information',
        'RPI (Retail Price Index) berbeda dengan CPI (Consumer Price Index) hanya dalam mengukur barang dan jasa yang dibeli untuk tujuan konsumsi oleh sebagian besar rumah tangga, dan itu termasuk biaya perumahan yang dikecualikan dari CPI;',
        0,
        NULL,
        '-'
    ),
    (
        '2026-03-25',
        '16.00',
        'CHF',
        'Low',
        'UBS Economic Expectations',
        '9.8',
        NULL,
        '-35.0',
        'UBS AG (latest release)',
        'Level of a diffusion index based on surveyed institutional investors and analysts;',
        '''Actual'' greater than ''Forecast'' is good for currency;',
        'Released monthly, around about 26 days after the month ends;',
        'No Information',
        'Above 0.0 indicates optimism, below indicates pessimism;',
        0,
        NULL,
        'It''s a leading indicator of economic health - investors and analysts are highly informed by virtue of their job, and changes in their sentiment can be an early signal of future economic activity;'
    ),
    (
        '2026-03-25',
        '16.00',
        'EUR',
        'Medium',
        'German Ifo Business Climate',
        '88.6',
        '86.3',
        '86.4',
        'Ifo Institute for Economic Research',
        'Tingkat indeks komposit berdasarkan survei produsen, pembangun, pedagang besar, jasa, dan pengecer;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 3 minggu dalam bulan berjalan',
        'No Information',
        'Survei ini sangat dihargai karena ukuran sampelnya yang besar dan korelasi historisnya dengan kondisi perekonomian Jerman dan zona euro yang lebih luas. Hal ini cenderung menciptakan dampak pasar yang besar dan kuat setelah dirilis. Sumber mengubah rangkaian dari tahun dasar 2000 menjadi tahun dasar 2005, mulai Mei 2011, dan mengubah rangkaian untuk menyertakan layanan, mulai April 2018;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan perubahan sentimen dapat menjadi sinyal awal mengenai aktivitas perekonomian di masa depan seperti pembelanjaan, perekrutan tenaga kerja, dan investasi;'
    ),
    (
        '2026-03-25',
        '16.30',
        'GBP',
        'Low',
        'HPI y/y',
        '1.9%',
        '1.7%',
        '1.3%',
        'UK Government',
        'Perubahan harga jual rumah',
        '''Aktual'' lebih besar dari ''Prakiraan'' bagus untuk mata uang',
        'Dirilis setiap bulan, sekitar 45 hari setelah bulan berakhir',
        'No Information',
        'Sumber pertama kali dirilis pada Juni 2016',
        0,
        NULL,
        '-'
    ),
    (
        '2026-03-25',
        '19.30',
        'US',
        'Low',
        'Current Account (US)',
        '-239B',
        '-211B',
        '-191B',
        'Biro Analisa Ekonomi',
        'Selisih nilai antara impor dan ekspor dari barang, jasa, arus pendapatan, dan transfer unilateral selama kuartal sebelumnya; Porsi dari barang dan jasa tidak terlalu berdampak karena itu merupakan duplikasi dari data Trade Balance bulanan; Ini secara',
        'Aktual > Perkiraan = Positif',
        'Rilis kuartalan, sekitar 75 hari setelah kuartal berakhir',
        'No Information',
        NULL,
        0,
        NULL,
        NULL
    ),
    (
        '2026-03-25',
        '19.30',
        'US',
        'Low',
        'Import Prices m/m (US)',
        '0.6%',
        '0.6%',
        '1.3%',
        'Biro Statistik Tenaga Kerja',
        'Perubahan harga barang dan jasa impor yang dibeli di dalam negeri;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 13 hari setelah bulan berjalan',
        'No Information',
        'Ini merupakan data inflasi paling awal yang dirilis pemerintah;',
        0,
        NULL,
        'Hal ini berkontribusi terhadap inflasi bagi dunia usaha dan konsumen, terutama mereka yang sangat bergantung pada barang dan jasa impor;'
    ),
    (
        '2026-03-25',
        '20.00',
        'CHN',
        'Low',
        'CB Leading Index m/m',
        '0.1%',
        '-',
        '-0.2%',
        'The Conference Board Inc.',
        'Perubahan tingkat indeks komposit berdasarkan 8 indikator ekonomi;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 24 hari setelah bulan berjalan',
        'No Information',
        'Indeks ini dirancang untuk memprediksi arah perekonomian, namun dampaknya cenderung tidak terlalu besar karena sebagian besar indikator yang digunakan dalam penghitungan dirilis sebelumnya. Sumber pertama kali dirilis pada Mei 2010;',
        0,
        NULL,
        '-'
    ),
    (
        '2026-03-25',
        '21.00',
        'EUR',
        'Low',
        'Belgian NBB Business Climate',
        '-13.7',
        '-14.8',
        '-13.7',
        'Bank Sentral Belgia',
        'Tingkat indeks komposit berdasarkan survey terhadap produsen, pengembang, jasa dan perusahaan yang terkait dengan perdagangan; Angka di atas 0,0 menunjukkan perbaikan kondisi, namun di bawah itu mengindikasikan kondisi yang memburuk. Survei ini sangat p',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 3 minggu dalam bulan berjalan',
        'No Information',
        'Di atas 0,0 menunjukkan kondisi membaik, di bawah menunjukkan kondisi memburuk. Survei ini sangat dihormati karena sumbernya dan ukuran sampel yang besar. Sumber mengubah rumus perhitungan seri pada April 2009;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan perubahan sentimen dapat menjadi sinyal awal mengenai aktivitas perekonomian di masa depan seperti pembelanjaan, perekrutan tenaga kerja, dan investasi;'
    ),
    (
        '2026-03-25',
        '21.30',
        'US',
        'Low',
        'Crude Oil Inventories',
        '6.2M',
        '-1.3M',
        '6.9M',
        'Administrasi Informasi Energi',
        'Perubahan jumlah barel minyak mentah yang disimpan oleh perusahaan komersial selama seminggu terakhir;',
        '''Aktual'' kurang dari ''Perkiraan'' baik untuk mata uang;',
        'Rilis mingguan, sekitar 4 hari setelah minggu berjalan',
        '01-04-2026',
        'Meskipun ini merupakan indikator AS, namun hal ini paling berdampak pada sektor energi Kanada yang cukup besar;',
        0,
        NULL,
        'Ini adalah ukuran utama ketidakseimbangan pasokan dan permintaan di pasar, yang dapat menyebabkan perubahan tingkat produksi dan ketidakstabilan harga;'
    ),
    (
        '2026-03-26',
        '06.50',
        'JPN',
        'Low',
        'SPPI y/y',
        '2.6%',
        '2.6%',
        '2.7%',
        'Bank of Japan (latest release)',
        'Change in the price of services purchased by corporations;',
        '''Actual'' greater than ''Forecast'' is good for currency;',
        'Released monthly, about 25 days after the month ends;',
        'No Information',
        '-',
        0,
        NULL,
        'It''s a leading indicator of consumer inflation - when corporations pay more for services the higher costs are usually passed on to the consumer;'
    ),
    (
        '2026-03-26',
        '12.02',
        'JPN',
        'Low',
        'BOJ Core CPI y/y',
        '1.7%',
        '1.6%',
        '1.7%',
        'Bank of Japan (rilis terbaru)',
        'Perubahan harga barang dan jasa yang dibeli oleh konsumen, tidak termasuk makanan dan energi;',
        '38/5000 Realisasi> Prakiraan = Baik untuk mata uang;',
        'Dirilis setiap bulan, biasanya pada hari Jumat terakhir bulan berikutnya;',
        'No Information',
        'Harga pangan dan energi menyumbang sekitar seperempat dari CPI, namun cenderung sangat fluktuatif dan mengganggu tren yang mendasarinya. BOJ biasanya lebih memperhatikan data Inti - begitu pula para pedagang. Ada versi revisi dari indikator ini yang dirilis sekitar 5 hari kemudian, namun tidak disertakan karena kurang signifikan. Sumber pertama kali dirilis pada November 2015;',
        0,
        NULL,
        'Harga konsumen mencapai mayoritas inflasi secara keseluruhan. Inflasi penting untuk penilaian mata uang karena kenaikan harga menyebabkan bank sentral menaikkan suku bunga karena menghormati mandat penahanan inflasi mereka;'
    ),
    (
        '2026-03-26',
        '14.00',
        'EUR',
        'Low',
        'German GfK Consumer Climate',
        '-24.8',
        '-27.3',
        '-28.0',
        'GfK (latest release)',
        'Tingkat indeks gabungan berdasarkan konsumen yang disurvei;',
        '''Aktual'' lebih besar dari ''Perkiraan'' bagus untuk mata uang;',
        'Dirilis setiap bulan, sekitar akhir bulan berjalan;',
        'No Information',
        'Di atas 0 menunjukkan optimisme, di bawah menunjukkan pesimisme;',
        0,
        NULL,
        'Kepercayaan finansial merupakan indikator utama belanja konsumen, yang menyumbang sebagian besar aktivitas perekonomian secara keseluruhan;'
    ),
    (
        '2026-03-26',
        '16.00',
        'EUR',
        'Low',
        'M3 Money Supply y/y',
        '3.2%',
        '3.3%',
        '3.0%',
        'Bank Sentral Eropa (ECB)',
        'Perubahan jumlah mata uang dalam negeri yang beredar dan disimpan di bank;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 28 hari setelah periode bulan berjalan',
        'No Information',
        'Sumber mengubah rumus perhitungan seri pada Mei 2001;',
        0,
        NULL,
        'Hal ini berkorelasi positif dengan tingkat suku bunga - pada awal siklus ekonomi, peningkatan jumlah uang beredar menyebabkan pengeluaran dan investasi tambahan, dan kemudian pada siklus tersebut, peningkatan jumlah uang beredar menyebabkan inflasi;'
    ),
    (
        '2026-03-26',
        '16.00',
        'EUR',
        'Low',
        'Private Loans y/y',
        '3.0%',
        '3.1%',
        '3.0%',
        'Bank Sentral Eropa (ECB)',
        'Perubahan nilai total pinjaman baru yang diberikan kepada konsumen dan dunia usaha di sektor swasta;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 28 hari setelah periode bulan berjalan',
        'No Information',
        '-',
        0,
        NULL,
        'Pinjaman dan pembelanjaan berkorelasi positif - konsumen dan dunia usaha cenderung mencari kredit ketika mereka yakin dengan posisi keuangan mereka di masa depan dan merasa nyaman membelanjakan uangnya;'
    ),
    (
        '2026-03-26',
        '19.30',
        'US',
        'High',
        'Unemployment Claims',
        '205K',
        '211K',
        '210K',
        'Departemen Tenaga Kerja',
        'Jumlah individu yang pertama kali mengajukan asuransi pengangguran selama seminggu terakhir;',
        '''Aktual'' kurang dari ''Perkiraan'' baik untuk mata uang;',
        'Dirilis setiap minggu, biasanya pada hari Kamis pertama setelah minggu berakhir;',
        '02-04-2026',
        'Ini adalah data ekonomi negara yang paling awal. Dampak pasar berfluktuasi dari minggu ke minggu - cenderung lebih fokus pada rilis ketika pedagang perlu mendiagnosis perkembangan terkini, atau ketika angkanya ekstrem;',
        0,
        NULL,
        'Meskipun secara umum angka ini dipandang sebagai indikator tertinggal, jumlah pengangguran merupakan sinyal penting mengenai kesehatan perekonomian secara keseluruhan karena belanja konsumen sangat berkorelasi dengan kondisi pasar tenaga kerja. Pengangguran juga merupakan pertimbangan utama bagi mereka yang mengendalikan kebijakan moneter negara tersebut;'
    ),
    (
        '2026-03-26',
        '21.30',
        'US',
        'Low',
        'Natural Gas Storage',
        '35B',
        NULL,
        NULL,
        'Administrasi Informasi Energi',
        'Perubahan jumlah kubik feet dari gas alam yang disimpan di gudang bawah tanah selama seminggu sebelumnya;',
        '''Aktual'' kurang dari ''Perkiraan'' baik untuk mata uang;',
        'Rilis mingguan, sekitar 5 hari setelah minggu berjalan',
        '02-04-2026',
        'Persediaan digunakan untuk menjaga stabilitas harga selama kekurangan pasokan dan periode peningkatan permintaan;',
        0,
        NULL,
        '-'
    ),
    (
        '2026-03-27',
        '07.01',
        'GBP',
        'Low',
        'GfK Consumer Confidence',
        '-19',
        '-24',
        '-21',
        'GfK NOP',
        'Tingkat indeks difusi berdasarkan konsumen yang disurvei',
        'Aktual > Perkiraan = Positif',
        'Dirilis bulanan, biasanya pada hari kerja terakhir dari bulan berjalan',
        'No Information',
        'Di atas 0 menunjukkan optimisme, di bawah menunjukkan pesimisme',
        0,
        NULL,
        'Financial confidence adalah indikator utama belanja konsumen, yang menyumbang mayoritas aktivitas ekonomi secara keseluruhan'
    ),
    (
        '2026-03-27',
        '14.00',
        'GBP',
        'High',
        'Retail Sales m/m (GBP)',
        '1.8%',
        '-0.3%',
        NULL,
        'Kantor Statistik Federal',
        'Perubahan nilai total penjualan yang disesuaikan dengan inflasi pada tingkat ritel;',
        'Actual > Forecast = Bagus untuk mata uang',
        'Rilis bulanan, sekitar 20 hari setelah bulan berakhir',
        'No Information',
        'Sumber mengubah rumus perhitungan seri pada Februari 2010;',
        0,
        NULL,
        'Ini adalah ukuran utama belanja konsumen, yang menyumbang mayoritas aktivitas ekonomi secara keseluruhan;'
    ),
    (
        '2026-03-27',
        '15.00',
        'EUR',
        'Low',
        'Spanish Flash CPI y/y',
        '2.3%',
        '2.4%',
        NULL,
        'Institute Statistik Nasional Spanyol',
        'Perubahan harga barang dan jasa yang dibeli oleh konsumen',
        'Aktual > Perkiraan = Biasanya akan positif terhadap nilai tukar',
        'Rilis bulanan, sekitar akhir dari bulan berjalan',
        'No Information',
        'Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar dua minggu - Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Maret 2011, merupakan rilis paling awal dan cenderung memiliki dampak paling besar. Final tidak dilaporkan karena kurang penting;',
        0,
        NULL,
        'Harga-harga konsumen memberikan kontribusi untuk mayoritas inflasi secara keseluruhan. Inflasi penting untuk penilaian mata uang karena kenaikan harga akan bisa menyebabkan bank sentral menaikkan suku bunga guna menahan laju inflasi tersebut;'
    ),
    (
        '2026-03-27',
        '21.00',
        'US',
        'Medium',
        'Revised UoM Consumer Sentiment',
        '55.5',
        '53.9',
        NULL,
        'University of Michigan',
        'Tingkat indeks gabungan berdasarkan konsumen yang disurvei;',
        'Aktual > Perkiraan = Positif',
        'RIlis bulanan, biasanya pada Jumat terakhir dari periode bulan berjalan',
        'No Information',
        'Daftar ''Sebelumnya'' adalah ''Aktual'' dari rilis Awal dan oleh karena itu data ''Riwayat'' akan tampak tidak berhubungan. Ada 2 versi data ini yang dirilis dengan selang waktu sekitar 15 hari ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Pendahuluan dan Revisi. Rilisan Awal adalah yang paling awal sehingga cenderung mempunyai dampak yang lebih besar;',
        0,
        NULL,
        'Kepercayaan finansial merupakan indikator utama belanja konsumen, yang menyumbang sebagian besar aktivitas perekonomian secara keseluruhan;'
    ),
    (
        '2026-03-27',
        '21.00',
        'US',
        'Low',
        'Revised UoM Inflation Expectations',
        '3.4%',
        NULL,
        NULL,
        'University of Michigan',
        'Persentase dari ekspektasi konsumen terhadap perubahan harga barang dan jasa selama 12 bulan ke depan;',
        'Aktual > Perkiraan = Positif',
        'RIlis bulanan, biasanya pada Jumat terakhir dari periode bulan berjalan',
        'No Information',
        'Daftar data ''Sebelumnya'' adalah ''Aktual'' dari rilis data Awal dan oleh karena itu data ''Riwayat'' akan tampak tidak berhubungan. Ada 2 versi data ini yang dirilis dengan selang waktu sekitar 15 hari ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Pendahuluan dan Revisi. Rilisan Awal adalah yang paling awal sehingga cenderung mempunyai dampak paling besar;',
        0,
        NULL,
        'Ekspektasi terhadap inflasi di masa depan dapat terwujud dalam inflasi riil, terutama karena pekerja cenderung mendorong upah yang lebih tinggi ketika mereka yakin harga akan naik;'
    ),
    (
        '2026-03-27',
        '21.55',
        'US',
        'Low',
        'FOMC Member Williams Speaks',
        NULL,
        NULL,
        NULL,
        'Federal Reserve Bank of New York (latest release)',
        '-',
        'Lebih hawkish dari yang diharapkan bagus untuk mata uang;',
        '-',
        'No Information',
        'Anggota pemungutan suara FOMC 2012, 2015, 2018, 2019, dan 2020. Pada Juni 2018 namanya berubah dari Federal Reserve Bank Presiden San Francisco menjadi Federal Reserve Bank Presiden New York;',
        0,
        NULL,
        'Anggota Federal Reserve FOMC memberikan suara di mana untuk menetapkan suku bunga utama negara dan keterlibatan publik mereka sering digunakan untuk menjatuhkan petunjuk halus mengenai kebijakan moneter masa depan;'
    ),
    (
        '2026-03-27',
        'All Day',
        'EUR',
        'Low',
        'ECOFIN Meetings',
        NULL,
        NULL,
        NULL,
        'Konsulat Eropa (European Council)',
        '-',
        '-',
        '-',
        'No Information',
        'Pertemuan ECOFIN biasanya diadakan di Brussels dan dihadiri oleh Menteri Keuangan dari negara-negara anggota UE. Mereka membahas berbagai masalah keuangan, seperti mekanisme dukungan euro dan keuangan pemerintah. Pertemuan tersebut tertutup bagi pers namun para pejabat biasanya berbicara dengan wartawan sepanjang hari, dan pernyataan resmi yang mencakup tujuan pertemuan dapat dikeluarkan setelah pertemuan selesai;',
        0,
        NULL,
        'ECOFIN adalah badan pengambil keputusan keuangan terluas di Zona Euro. Dewan ini mengoordinasikan kebijakan ekonomi dari 28 negara anggota, dan inisiatif serta keputusan mereka dapat berdampak luas pada kesehatan ekonomi Zona Euro;'
    ),
    (
        '2026-03-27',
        'Tentative',
        'US',
        'Low',
        'Fed Monetary Policy Report',
        NULL,
        NULL,
        NULL,
        'Federal Reserve (latest release)',
        NULL,
        'More hawkish than expected is good for currency;',
        'Twice per year;',
        'No Information',
        'Report provides a summary of discussions of the conduct of monetary policy and economic developments and prospects for the future. It is submitted, along with testimony from the Federal Reserve Chair, to the Senate Committee on Banking, Housing, and Urban',
        0,
        NULL,
        NULL
    );

INSERT INTO
    economic_calendar_categories (
        country,
        impact,
        figures,
        sources,
        measures,
        usual_effect,
        frequency,
        next_released,
        notes,
        isBankHoliday,
        bankHolidayNote,
        why_trader_care,
        created_at,
        updated_at
    )
SELECT DISTINCT
    t.country,
    t.impact,
    t.figures,
    t.sources,
    t.measures,
    t.usual_effect,
    t.frequency,
    t.next_released,
    t.notes,
    t.isBankHoliday,
    t.bankHolidayNote,
    t.why_trader_care,
    NOW(),
    NOW()
FROM tmp_economic_calendar_import t
WHERE
    NOT EXISTS (
        SELECT 1
        FROM economic_calendar_categories c
        WHERE
            c.country = t.country
            AND c.impact = t.impact
            AND c.figures = t.figures
    );

INSERT INTO
    economic_calendars (
        economic_calendar_category_id,
        date,
        time,
        country,
        impact,
        figures,
        previous,
        forecast,
        actual,
        sources,
        measures,
        usual_effect,
        frequency,
        next_released,
        notes,
        isBankHoliday,
        bankHolidayNote,
        why_trader_care,
        created_at,
        updated_at
    )
SELECT
    c.id,
    t.date_value,
    t.time_value,
    t.country,
    t.impact,
    t.figures,
    t.previous_value,
    t.forecast_value,
    t.actual_value,
    t.sources,
    t.measures,
    t.usual_effect,
    t.frequency,
    t.next_released,
    t.notes,
    t.isBankHoliday,
    t.bankHolidayNote,
    t.why_trader_care,
    NOW(),
    NOW()
FROM
    tmp_economic_calendar_import t
    JOIN economic_calendar_categories c ON c.country = t.country
    AND c.impact = t.impact
    AND c.figures = t.figures;

COMMIT;