-- Generated from uploaded payload (73 rows)
START TRANSACTION;

DROP TEMPORARY TABLE IF EXISTS tmp_economic_calendar_import;

CREATE TEMPORARY TABLE tmp_economic_calendar_import (
    date_value DATE NULL,
    time_value VARCHAR(50) NULL,
    country VARCHAR(50) NULL,
    impact VARCHAR(20) NULL,
    figures VARCHAR(255) NULL,
    previous_value VARCHAR(100) NULL,
    forecast_value VARCHAR(100) NULL,
    actual_value VARCHAR(100) NULL,
    sources TEXT NULL,
    measures LONGTEXT NULL,
    usual_effect LONGTEXT NULL,
    frequency LONGTEXT NULL,
    next_released VARCHAR(100) NULL,
    notes LONGTEXT NULL,
    isBankHoliday TINYINT(1) NOT NULL DEFAULT 0,
    bankHolidayNote LONGTEXT NULL,
    why_trader_care LONGTEXT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

INSERT INTO
    tmp_economic_calendar_import (
        date_value,
        time_value,
        country,
        impact,
        figures,
        previous_value,
        forecast_value,
        actual_value,
        sources,
        measures,
        usual_effect,
        frequency,
        next_released,
        notes,
        isBankHoliday,
        bankHolidayNote,
        why_trader_care
    )
VALUES (
        '2026-03-16',
        '07.01',
        'GBP',
        'Low',
        'Rightmove HPI m/m',
        '0.0%',
        NULL,
        '0.8%',
        'Rightmove (rilis terbaru)',
        'Perubahan harga yang diminta dari penjualan rumah',
        'Actual> Prakiraan = Baik untuk mata uang;',
        'Dirilis bulanan, sekitar 3 minggu ke bulan berjalan;',
        'No Information',
        'Ini adalah laporan awal Inggris pada inflasi perumahan, namun cenderung menghasilkan dampak yang relatif ringan karena meminta harga dan harga jual tidak selalu berkorelasi;',
        0,
        NULL,
        'Ini adalah indikator utama dari kesehatan industri perumahan karena kenaikan harga rumah menarik investor dan aktivitas industri memacu;'
    ),
    (
        '2026-03-16',
        '08.30',
        'CHN',
        'Low',
        'New Home Prices m/m',
        '-0.37%',
        NULL,
        '-0.28%',
        'National Bureau of Statistics of China',
        'Perubahan harga jual bangunan tempat tinggal baru yang dibangun di 70 kota menengah dan besar;',
        '''Aktual'' lebih besar dari ''Perkiraan'' bagus untuk mata uang;',
        'Dirilis setiap bulan, sekitar 15 hari setelah bulan berakhir;',
        'No Information',
        NULL,
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan industri perumahan karena kenaikan harga rumah menarik investor dan memacu aktivitas industri;'
    ),
    (
        '2026-03-16',
        '09.00',
        'CHN',
        'Low',
        'Fixed Asset Investment ytd/y',
        '-3.8%',
        '-5.0%',
        '1.8%',
        'Biro Statistik Nasional China',
        'Perubahan total pengeluaran untuk investasi modal non-pedesaan seperti pabrik, jalan raya, jaringan listrik, dan properti;',
        'Aktual > Perkiraan = Positif',
        'Dirilis setiap bulan, kecuali bulan Februari, sekitar 15 hari setelah bulan berakhir;',
        'No Information',
        'Data mewakili investasi tahun ini dibandingkan dengan periode yang sama tahun sebelumnya;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan ekonomi - perubahan tingkat investasi swasta dan pemerintah dapat menjadi sinyal awal mengenai aktivitas ekonomi di masa depan seperti perekrutan, pengeluaran, dan pendapatan;'
    ),
    (
        '2026-03-16',
        '09.00',
        'CHN',
        'Low',
        'Industrial Production y/y',
        '5.2%',
        '5.3%',
        '6.3%',
        'Biro Statistik Nasional China',
        'Perubahan total nilai output yang disesuaikan dengan inflasi yang dihasilkan oleh produsen, pertambangan, dan utilitas;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 9 hari pasca bulan berjalan (tidak termasuk Februari)',
        'No Information',
        'Data Tiongkok dapat berdampak luas pada pasar mata uang karena pengaruh Tiongkok terhadap perekonomian global dan sentimen investor;',
        0,
        NULL,
        'Ini adalah indikator utama kesehatan perekonomian - produksi merupakan penggerak perekonomian yang dominan dan bereaksi dengan cepat terhadap naik turunnya siklus bisnis;'
    ),
    (
        '2026-03-16',
        '09.00',
        'CHN',
        'Low',
        'NBS Press Conference',
        NULL,
        NULL,
        NULL,
        'Biro Statistik Nasional China',
        'Konferensi pers yang memiliki 2 bagian - pertama pernyataan yang siap membacakan pengumuman angka ekonomi utama, kemudian konferensi yang disiapkan untuk menampung pertanyaan-pertanyaan.',
        NULL,
        'Dijadwalkan setiap bulan, kecuali bulan Februari, sekitar 15 hari setelah bulan berakhir;',
        'No Information',
        'Konferensi pers terdiri dari 2 bagian - pertama, pernyataan yang telah disiapkan dibacakan yang mengumumkan angka-angka ekonomi utama, kemudian konferensi dibuka secara singkat untuk pertanyaan pers.',
        0,
        NULL,
        NULL
    ),
    (
        '2026-03-16',
        '09.00',
        'CHN',
        'Low',
        'Retail Sales y/y (CHN)',
        '0.9%',
        '2.6%',
        '2.8%',
        'Biro Statistik Nasional China (rilis terbaru)',
        'Perubahan nilai total penjualan di tingkat ritel;',
        '''Sebenarnya'' lebih besar dari ''Prakiraan'' baik untuk mata uang;',
        'Dirilis setiap bulan, tidak termasuk Februari, sekitar 15 hari setelah bulan berakhir;',
        'No Information',
        'Ini adalah gambaran awal data belanja konsumen yang penting. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar dua minggu - Prelim dan Final. Final tidak dilaporkan karena kurang penting;',
        0,
        NULL,
        'Ini adalah ukuran utama belanja konsumen, yang menyumbang sebagian besar aktivitas perekonomian secara keseluruhan;'
    ),
    (
        '2026-03-16',
        '09.00',
        'CHN',
        'Low',
        'Unemployment Rate (CHN)',
        '5.1%',
        '5.1%',
        '5.3%',
        'National Bureau of Statistics of China (latest release)',
        'Persentase total pekerja perkotaan yang menganggur dan aktif mencari pekerjaan selama bulan sebelumnya;',
        '''Actual'' less than ''Forecast'' is good for currency;',
        'Released monthly, excluding Feb, about 15 days after the month ends;',
        'No Information',
        'Sumber pertama kali dirilis pada April 2018;',
        0,
        NULL,
        'Meskipun secara umum angka ini dipandang sebagai indikator tertinggal, jumlah pengangguran merupakan sinyal penting mengenai kesehatan perekonomian secara keseluruhan karena belanja konsumen sangat berkorelasi dengan kondisi pasar tenaga kerja.'
    ),
    (
        '2026-03-16',
        '18.00',
        'EUR',
        'Low',
        'German Buba Monthly Report',
        NULL,
        NULL,
        NULL,
        'Bundesbank Jerman',
        'Dampak terhadap pasar cenderung lebih besar ketika laporan tersebut mengungkapkan sudut pandang yang bertentangan dengan sikap ECB; Ini berisi artikel yang relevan, pidato-pidato, tabel statistik, dan menyediakan analisis rincian atas kondisi ekonomi sa',
        'Lebih "hawkish" daripada ekspektasi biasanya akan berdampak positif terhadap pasar',
        'Rilis bulanan',
        'No Information',
        'Dampak pasar cenderung lebih besar ketika laporan tersebut mengungkapkan sudut pandang yang bertentangan dengan pendirian ECB;',
        0,
        NULL,
        'Ini berisi artikel, pidato, tabel statistik yang relevan, dan memberikan analisis rinci tentang kondisi ekonomi saat ini dan masa depan dari sudut pandang bank;'
    ),
    (
        '2026-03-16',
        '19.30',
        'US',
        'Medium',
        'Empire State Manufacturing Index',
        '7.1',
        '4.0',
        '-0.2',
        'The Fed of New York',
        'Tingkat indeks difusi berdasarkan survei produsen di negara bagian New York;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar pertengahan bulan dari bulan berjalan',
        'No Information',
        'Di atas 0,0 menunjukkan kondisi membaik, di bawah menunjukkan kondisi memburuk;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan perubahan sentimen dapat menjadi sinyal awal mengenai aktivitas perekonomian di masa depan;'
    ),
    (
        '2026-03-16',
        '20.15',
        'US',
        'Low',
        'Capacity Utilization Rate',
        '76.3%',
        '76.2%',
        '76.3%',
        'Federal Reserve',
        'Persentase sumber daya yang tersedia dan dimanfaatkan oleh produsen, tambang, dan utilitas;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 16 hari setelah bulan berjalan',
        'No Information',
        NULL,
        0,
        NULL,
        'Hal ini merupakan indikator utama inflasi konsumen - ketika produsen mendekati kapasitas penuh, mereka merespons dengan menaikkan harga, dan biaya yang lebih tinggi biasanya dibebankan kepada konsumen;'
    ),
    (
        '2026-03-16',
        '20.15',
        'US',
        'Low',
        'Industrial Production m/m',
        '0.7%',
        '0.1%',
        '0.2%',
        'Federal Reserve',
        'Perubahan nilai dari total inflasi yang disesuaikan dengan output yang dihasilkan oleh pabrik, pertambangan, dan utilitas;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 16 hari setelah bulan berjalan',
        'No Information',
        NULL,
        0,
        NULL,
        'Ini adalah indikator utama kesehatan perekonomian - produksi bereaksi dengan cepat terhadap naik turunnya siklus bisnis dan berkorelasi dengan kondisi konsumen seperti tingkat lapangan kerja dan pendapatan;'
    ),
    (
        '2026-03-16',
        '21.00',
        'US',
        'Low',
        'NAHB Housing Market Index',
        '37',
        '37',
        '38',
        'National Association of Home Builders (NAHB)',
        'Tingkat indeks difusi yang didasarkan pada survey para pengembang rumah;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar pertengahan bulan dari bulan berjalan',
        'No Information',
        'Di atas 50 menunjukkan prospek penjualan rumah yang baik, di bawah menunjukkan prospek negatif;',
        0,
        NULL,
        NULL
    ),
    (
        '2026-03-16',
        '22.30',
        'US',
        'Medium',
        'President Trump Speaks',
        NULL,
        NULL,
        NULL,
        'White House (latest release)',
        NULL,
        NULL,
        NULL,
        'No Information',
        'US President Jan 2017 - Jan 2021 and Jan 2025 - Jan 2029. He speaks frequently on a broad range of subjects - only speeches that might have direct market impact are listed on the calendar;',
        0,
        NULL,
        NULL
    ),
    (
        '2026-03-17',
        '10.30',
        'AUD',
        'High',
        'Cash Rate',
        '3.85%',
        '4.10%',
        '4.10%',
        'Reserve Bank of Australia (RBA)',
        'Tingkat suku bunga untuk deposito pasar uang overnight;',
        'Aktual > Perkiraan = Bagus untuk mata uang',
        'Selasa pertama setiap bulan, kecuali Januari',
        'No Information',
        'Pengaruh keputusan suku bunga sering telah terserap kedalam harga pasar sehingga cenderung dibayangi oleh pernyataan tingkat suku bunga oleh RBA yang difokuskan untuk masa depan;',
        0,
        NULL,
        'Suku bunga jangka pendek merupakan faktor terpenting dalam penilaian mata uang - pedagang melihat sebagian besar indikator lain hanya untuk memprediksi bagaimana harga akan berubah di masa depan;'
    ),
    (
        '2026-03-17',
        '10.30',
        'AUD',
        'High',
        'RBA Rate Statement',
        NULL,
        NULL,
        NULL,
        'Reserve Bank of Australia (RBA)',
        NULL,
        'Lebih Hawkish dari perkiraan = Bagus untuk mata uang',
        'Selasa pertama setiap bulan, kecuali Januari',
        'No Information',
        'Sampai Desember 2007 pernyataan itu hanya dikeluarkan ketika tingkat suku bunga mengalami perubahan;',
        0,
        NULL,
        'Ini adalah salah satu alat utama RBA yang digunakan untuk berkomunikasi dengan para investor mengenai kebijakan moneter. Berisikan hasil keputusan dewan bank sentral atas tingkat suku bunga dan komentar-komentar tentang kondisi ekonomi yang bisa mempengaru'
    ),
    (
        '2026-03-17',
        '11.30',
        'JPN',
        'Low',
        'Tertiary Industry Activity m/m',
        '-0.5%',
        '0.7%',
        '1.7%',
        'Kementerian Ekonomi, Perdagangan dan Industri (METI)',
        'Perubahan nilai total jasa yang dibeli oleh pebisnis; Ini adalah indikator utama kesehatan ekonomi - bisnis dengan cepat dipengaruhi oleh kondisi pasar, dan perubahan dalam pengeluaran mereka dapat menjadi sinyal awal kegiatan ekonomi masa depan, sepert',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 40 hari setelah bulan berakhir',
        'No Information',
        NULL,
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan ekonomi - dunia usaha akan cepat terpengaruh oleh kondisi pasar, dan perubahan dalam pengeluaran mereka dapat menjadi sinyal awal mengenai aktivitas ekonomi di masa depan seperti perekrutan, pendapatan, dan investasi;'
    ),
    (
        '2026-03-17',
        '14.30',
        'CHF',
        'Low',
        'PPI m/m (CHF)',
        '-0.2%',
        '0.0%',
        '-0.3%',
        'Kantor Statistik Federal',
        'Perubahan harga barang dan bahan baku yang dibeli oleh produsen;',
        'Actual > Forecast = Bagus untuk mata uang',
        'Rilis bulanan, sekitar 14 hari setelah bulan berakhir;',
        'No Information',
        NULL,
        0,
        NULL,
        'Ini adalah indikator utama inflasi konsumen - ketika produsen membayar lebih tinggi untuk biaya barang maka biasanya biaya tersebut akan diteruskan kepada konsumen;'
    ),
    (
        '2026-03-17',
        '17.00',
        'EUR',
        'Low',
        'German ZEW Economic Sentiment',
        '58.3',
        '39.0',
        '-0.5',
        'Pusat Penelitian Ekonomi Eropa',
        'Tingkat indeks difusi didasarkan pada survei investor institusi Jerman dan analis;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, pada Selasa kedua atau ketiga di bulan berjalan',
        'No Information',
        'Di atas 0,0 menunjukkan optimisme, di bawah menunjukkan pesimisme;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - investor dan analis mempunyai informasi yang lengkap berdasarkan pekerjaan mereka, dan perubahan sentimen mereka dapat menjadi sinyal awal mengenai aktivitas perekonomian di masa depan;'
    ),
    (
        '2026-03-17',
        '17.00',
        'EUR',
        'Low',
        'ZEW Economic Sentiment',
        '39.4',
        '26.5',
        '-8.5',
        'Pusat Penelitian Ekonomi Eropa (ZEW)',
        'Tingkat indeks difusi didasarkan pada survei investor institusi Jerman dan analis;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, pada Selasa kedua atau ketiga di bulan berjalan',
        'No Information',
        'Di atas 0,0 menunjukkan optimisme, di bawah menunjukkan pesimisme. Survei ZEW secara historis berfokus pada perekonomian Jerman, dan Jerman cenderung memimpin perekonomian Zona Euro, sehingga prospek Zona Euro secara keseluruhan cenderung dibayangi oleh data Jerman yang dirilis pada waktu yang sama;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - investor dan analis mempunyai informasi yang lengkap berdasarkan pekerjaan mereka, dan perubahan sentimen mereka dapat menjadi sinyal awal mengenai aktivitas perekonomian di masa depan;'
    ),
    (
        '2026-03-17',
        '19.15',
        'US',
        'Low',
        'ADP Weekly Employment Change',
        '14.8K',
        NULL,
        '9.0K',
        'Automatic Data Processing, Inc. (latest release)',
        'Estimated average weekly change in the number of employed people during the previous 4 weeks, excluding the farming industry and government;',
        '''Actual'' greater than ''Forecast'' is good for currency;',
        'Released weekly, on the first Tuesday about 2 weeks after the rolling four-week period ends;',
        'No Information',
        'This is high-frequency private-sector employment data based on a rolling four-week average, and tends to be more volatile than the monthly ADP Employment Report. The release is skipped in any week that overlaps with publication of the monthly ADP Employment Report. Source first released in Oct 2025;',
        0,
        NULL,
        'Job creation is an important leading indicator of consumer spending, which accounts for a majority of overall economic activity;'
    ),
    (
        '2026-03-17',
        '21.00',
        'US',
        'Medium',
        'Pending Home Sales m/m',
        '-1.0%',
        '-0.6%',
        '1.8%',
        'National Association of Realtors',
        'Perubahan jumlah rumah di bawah kontrak yang akan dijual tetapi masih menunggu penyelesaian transaksi, tidak termasuk konstruksi baru; Data ini dirilis sekitar seminggu setelah Existing Home Sales, tapi lebih dipandang sebagai sebuah kontrak yang ditand',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 28 hari setelah periode bulan berjalan',
        'No Information',
        'Data ini dirilis sekitar seminggu lebih lambat dari Penjualan Rumah yang Ada, namun lebih berwawasan ke depan karena kontrak ditandatangani beberapa minggu sebelum rumah dihitung sebagai terjual;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian karena penjualan rumah memicu efek riak yang luas. Misalnya, renovasi dilakukan oleh pemilik baru, hipotek dijual oleh bank pembiayaan, dan broker dibayar untuk melaksanakan transaksi;'
    ),
    (
        '2026-03-17',
        '21.30',
        'AUD',
        'Low',
        'CB Leading Index m/m',
        '0.3%',
        NULL,
        '0.2%',
        'The Conference Board Inc.',
        'Perubahan tingkat indeks komposit berdasarkan 7 indikator ekonomi;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 50 hari setelah bulan berakhir',
        'No Information',
        'Indeks ini dirancang untuk memprediksi arah perekonomian, namun dampaknya cenderung tidak terlalu besar karena sebagian besar indikator yang digunakan dalam penghitungan dirilis sebelumnya;',
        0,
        NULL,
        NULL
    ),
    (
        '2026-03-18',
        '03.30',
        'US',
        'Low',
        'API Weekly Statistical Bulletin',
        NULL,
        NULL,
        NULL,
        'API (latest release)',
        NULL,
        NULL,
        'Released weekly, 3 days after the week ends;',
        '01-04-2026',
        NULL,
        0,
        NULL,
        NULL
    ),
    (
        '2026-03-18',
        '06.30',
        'AUD',
        'Low',
        'MI Leading Index m/m',
        '0.0%',
        NULL,
        '-0.1%',
        'Melbourne Institute (rilis terbaru)',
        'Perubahan tingkat indeks komposit berdasarkan 9 indikator ekonomi;',
        '''Aktual'' lebih besar dari ''Perkiraan'' baik untuk mata uang;',
        'Dirilis setiap bulan, biasanya pada hari Rabu ketiga setelah bulan berakhir;',
        'No Information',
        'Indeks ini dirancang untuk memprediksi arah perekonomian, namun dampaknya cenderung tidak terlalu besar karena sebagian besar indikator yang digunakan dalam penghitungan dirilis sebelumnya. Laporan lengkap hanya tersedia untuk pelanggan Melbourne Institute;',
        0,
        NULL,
        NULL
    ),
    (
        '2026-03-18',
        '06.50',
        'JPN',
        'Low',
        'Trade Balance (JPN)',
        '0.50T',
        '-0.62T',
        '-0.37T',
        'Kementerian Keuangan',
        'Selisih dari nilai antara barang impor dan ekspor selama bulan yang dilaporkan. Angka yang positif menunjukkan bahwa lebih banyak barang yang diekspor daripada yang diimpor.',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 20 hari setelah bulan berjalan',
        'No Information',
        'Ini adalah data yang disesuaikan secara musiman (seperti kebanyakan angka FF), berbeda dengan angka yang disesuaikan secara non-musiman yang dilaporkan oleh beberapa kantor berita. Angka positif menunjukkan lebih banyak barang yang diekspor dibandingkan yang diimpor;',
        0,
        NULL,
        'Permintaan ekspor dan permintaan mata uang berhubungan langsung karena orang asing harus membeli mata uang domestik untuk membayar ekspor suatu negara. Permintaan ekspor juga berdampak pada produksi dan harga produsen dalam negeri;'
    ),
    (
        '2026-03-18',
        '17.00',
        'EUR',
        'Low',
        'Final Core CPI y/y',
        '2.4%',
        '2.4%',
        '2.4%',
        'Eurostat',
        'Perubahan harga barang dan jasa yang dibeli konsumen, tidak termasuk makanan, energi, alkohol, dan tembakau;',
        '''Actual'' greater than ''Forecast'' is good for currency;',
        'Dirilis setiap bulan, sekitar 16 hari setelah bulan berakhir;',
        'No Information',
        'Daftar ''Sebelumnya'' adalah ''Aktual'' dari Estimasi CPI Flash Core dan oleh karena itu data ''Riwayat'' akan tampak tidak berhubungan. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar dua minggu Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan April 2013, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
        0,
        NULL,
        NULL
    ),
    (
        '2026-03-18',
        '17.00',
        'EUR',
        'Low',
        'Final CPI y/y',
        '1.9%',
        '1.9%',
        '1.9%',
        'Eurostat (latest release)',
        'Perubahan harga barang dan jasa yang dibeli konsumen;',
        '''Aktual'' lebih besar dari ''Perkiraan'' bagus untuk mata uang;',
        'Dirilis setiap bulan, sekitar 16 hari setelah bulan berakhir;',
        'No Information',
        'Daftar ''Sebelumnya'' adalah ''Aktual'' dari Perkiraan Flash CPI dan oleh karena itu data ''Riwayat'' akan tampak tidak berhubungan. Data ini dianggap sebagai data inflasi Zona Euro yang paling penting karena digunakan sebagai target inflasi bank sentral, namun dampaknya cenderung relatif ringan karena Estimasi Kilat CPI dan CPI Pendahuluan Jerman dirilis sekitar 15 hari sebelumnya;',
        0,
        NULL,
        'Harga konsumen menyumbang sebagian besar inflasi secara keseluruhan. Inflasi penting dalam penilaian mata uang karena kenaikan harga menyebabkan bank sentral menaikkan suku bunga untuk menghormati mandat pengendalian inflasi;'
    ),
    (
        '2026-03-18',
        '19.30',
        'US',
        'High',
        'Core PPI m/m',
        '0.8%',
        '0.3%',
        '0.5%',
        'Departemen Tenaga Kerja',
        'Perubahan harga barang jadi dan jasa yang dijual oleh produsen, tidak termasuk pangan dan energi;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 13 hari setelah bulan berjalan',
        'No Information',
        'Sumber mengubah formula perhitungan seri pada bulan Februari 2014. Harga pangan dan energi menyumbang sekitar 40% dari keseluruhan PPI yang cenderung mengabaikan pentingnya data Inti;',
        0,
        NULL,
        NULL
    ),
    (
        '2026-03-18',
        '19.30',
        'US',
        'High',
        'PPI m/m',
        '0.5%',
        '0.3%',
        '0.7%',
        'Departemen Tenaga Kerja',
        'Perubahan harga barang jadi dan jasa yang dijual oleh produsen;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 17 hari setelah bulan berjalan',
        'No Information',
        'Sumber mengubah rumus perhitungan seri pada Februari 2014;',
        0,
        NULL,
        'Ini adalah indikator utama inflasi konsumen - ketika produsen mengenakan harga lebih tinggi untuk barang dan jasa, maka biaya yang lebih tinggi biasanya dibebankan kepada konsumen;'
    ),
    (
        '2026-03-18',
        '21.00',
        'US',
        'Low',
        'Factory Orders m/m',
        '-0.7%',
        '0.1%',
        '0.1%',
        'Biro Sensus',
        'Perubahan nilai total pesanan pembelian baru dengan produsen;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 35 hari setelah bulan berakhir',
        'No Information',
        'Laporan ini berisi revisi data Pesanan Barang Tahan Lama yang dirilis sekitar seminggu sebelumnya, dan data baru mengenai barang tidak tahan lama;',
        0,
        NULL,
        'Ini adalah indikator utama produksi - meningkatnya pesanan pembelian menandakan bahwa produsen akan meningkatkan aktivitas saat mereka berupaya memenuhi pesanan;'
    ),
    (
        '2026-03-18',
        '21.30',
        'US',
        'Low',
        'Crude Oil Inventories',
        '3.8M',
        '-1.5M',
        '6.2M',
        'Administrasi Informasi Energi',
        'Perubahan jumlah barel minyak mentah yang disimpan oleh perusahaan komersial selama seminggu terakhir;',
        '''Aktual'' kurang dari ''Perkiraan'' baik untuk mata uang;',
        'Rilis mingguan, sekitar 4 hari setelah minggu berjalan',
        '01-04-2026',
        'Meskipun ini merupakan indikator AS, namun hal ini paling berdampak pada sektor energi Kanada yang cukup besar;',
        0,
        NULL,
        'Ini adalah ukuran utama ketidakseimbangan pasokan dan permintaan di pasar, yang dapat menyebabkan perubahan tingkat produksi dan ketidakstabilan harga;'
    ),
    (
        '2026-03-18',
        'Tentative',
        'EUR',
        'Low',
        'German 30-y Bond Auction',
        '3.47',
        NULL,
        '3.45',
        'Bundesbank Jerman',
        'Imbal hasil (yield) rata-rata dari obligasi 30-tahun pemerintah Jerman yang dijual pada lelang obligasi;',
        'Tidak ada pengaruh yang konsisten - namun memberikan implikasi terhadap risiko dan pertumbuhan',
        'Variabel, sekitar 11 kali dalam setahun',
        'No Information',
        'Hasil lelang dilaporkan dalam format ''X.XX|X.X'' - angka pertama adalah tingkat bunga rata-rata obligasi yang terjual, dan angka kedua adalah rasio bid-to-cover (jumlah penawaran yang diajukan per penawaran yang diterima). Sumber tidak memberikan waktu rilis pasti - peristiwa ini akan terdaftar sebagai ''Tentatif'' hingga data dirilis;',
        0,
        NULL,
        'Imbal hasil ditentukan oleh investor pasar obligasi, dan oleh karena itu dapat digunakan untuk menguraikan pandangan investor mengenai suku bunga di masa depan. Rasio bid-to-cover mewakili likuiditas dan permintaan pasar obligasi, yang dapat digunakan untuk mengukur kepercayaan investor;'
    ),
    (
        '2026-03-19',
        '01.00',
        'US',
        'High',
        'Federal Funds Rate',
        '3.75%',
        '3.75%',
        '3.75%',
        'Federal Reserve',
        'Tingkat bunga di mana bank meminjamkan saldo yang disimpan Federal Reserve untuk bank lain dalam semalam (overnight);',
        'Aktual > Perkiraan = Biasanya negatif untuk jangka pendek, namun bisa menjadi positif untuk jangka panjang dalam menanggulangi kenaikan inflasi',
        'Jadual 8 kali dalam setahun',
        'No Information',
        'Keputusan suku bunga biasanya sudah diperhitungkan pasar, sehingga cenderung dibayangi oleh Pernyataan FOMC, yang berfokus pada masa depan;',
        0,
        NULL,
        'Suku bunga jangka pendek adalah faktor terpenting dalam penilaian mata uang - pedagang melihat sebagian besar indikator lain hanya untuk memprediksi bagaimana suku bunga akan berubah di masa depan;'
    ),
    (
        '2026-03-19',
        '01.00',
        'US',
        'High',
        'FOMC Economic Projections',
        NULL,
        NULL,
        NULL,
        'Federal Reserve',
        NULL,
        'More hawkish than expected is good for currency;',
        'Scheduled 4 times per year;',
        'No Information',
        'This report includes the FOMC''s projection for inflation and economic growth over the next 2 years and, more importantly, a breakdown of individual FOMC member''s interest rate forecasts. Source first released in Apr 2011;',
        0,
        NULL,
        'It''s the primary tool the Fed uses to communicate their economic and monetary projections to investors;'
    ),
    (
        '2026-03-19',
        '01.00',
        'US',
        'High',
        'FOMC Statement',
        NULL,
        NULL,
        NULL,
        'Federal Reserve',
        NULL,
        'Lebih "dovish" dibandingkan perkiraan biasanya mendapat respon yang positif, namun bila lebih "hawkish" biasanya akan direspon negatif oleh pasar.',
        'Jadual 8 kali dalam setahun',
        'No Information',
        'FOMC biasanya memberikan sedikit perubahan pada pernyataannya pada setiap kali rilis. Perubahan ini yang biasanya menjadi fokus para trader;',
        0,
        NULL,
        'Ini adalah alat utama yang digunakan FOMC untuk berkomunikasi dengan investor mengenai kebijakan moneter. Laporan ini berisi hasil pemungutan suara mereka mengenai suku bunga dan langkah-langkah kebijakan lainnya, serta komentar mengenai kondisi ekonomi yang mempengaruhi pemungutan suara mereka. Yang paling penting, laporan ini membahas prospek ekonomi dan memberikan petunjuk mengenai hasil pemungutan suara di masa depan;'
    ),
    (
        '2026-03-19',
        '01.30',
        'US',
        'High',
        'FOMC Press Conference',
        NULL,
        NULL,
        NULL,
        'Federal Reserve',
        'Konferensi pers yang dilakukan selama satu jam dan mempunyai dua bagian acara - pertama adalah pidato yang telah disiapkan, kedua adalah sesi tanya jawab; Pertanyaan terkadang bisa mengarah pada jawaban tanpa naskah sehingga bisa menciptakan volatilitas',
        'Lebih hawkish dibandingkan perkiraan biasanya akan cenderung direspon secara negatif, namun bila lebih dovish dari perkiraan maka biasanya akan direspon positif oleh pasar.',
        'Dijadwalkan 4 kali dalam setahun;',
        'No Information',
        'Konferensi pers berlangsung sekitar satu jam dan terdiri dari 2 bagian - pertama pernyataan yang telah disiapkan dibacakan, kemudian konferensi terbuka untuk pertanyaan pers. Pertanyaan-pertanyaan tersebut sering kali mengarah pada jawaban tanpa naskah yang menciptakan volatilitas pasar yang besar. Konferensi pers disiarkan melalui web di saluran YouTube The Fed secara real-time. Sumber pertama kali dilakukan pada bulan April 2011;',
        0,
        NULL,
        'Ini adalah salah satu metode utama yang digunakan The Fed untuk berkomunikasi dengan investor mengenai kebijakan moneter. Bab ini mencakup secara rinci faktor-faktor yang mempengaruhi tingkat suku bunga terkini dan keputusan kebijakan lainnya, serta komentar mengenai kondisi ekonomi seperti prospek pertumbuhan di masa depan dan inflasi. Yang paling penting, hal ini memberikan petunjuk mengenai kebijakan moneter masa depan;'
    ),
    (
        '2026-03-19',
        '03.00',
        'US',
        'Low',
        'TIC Long-Term Purchases',
        '96.5B',
        '71.6B',
        '15.5B',
        'Departemen Keuangan',
        'Selisih nilai antara surat berharga asing jangka panjang yang dibeli oleh warga negara AS dan surat berharga jangka panjang AS yang dibeli asing pada periode pelaporan;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 45 hari setelah bulan berjalan',
        'No Information',
        'Data ini mewakili keseimbangan investasi dalam dan luar negeri - misalnya, jika orang asing membeli saham dan obligasi AS senilai $100 miliar, dan AS membeli saham dan obligasi asing senilai $30 miliar, maka angka bersihnya adalah 70,0 miliar;',
        0,
        NULL,
        'Permintaan terhadap sekuritas dalam negeri dan permintaan mata uang berhubungan secara langsung karena orang asing harus membeli mata uang domestik untuk membeli sekuritas negara;'
    ),
    (
        '2026-03-19',
        '06.50',
        'JPN',
        'Low',
        'Core Machinery Orders m/m',
        '19.1%',
        '-9.6%',
        '-5.5%',
        'Kantor Kabinet',
        'Perubahan nilai total pesanan pembelian baru sektor swasta yang ditempatkan pada produsen mesin, tidak termasuk kapal dan utilitas;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 40 hari setelah bulan berakhir',
        'No Information',
        NULL,
        0,
        NULL,
        'Ini adalah indikator utama produksi - meningkatnya pesanan pembelian menandakan bahwa produsen akan meningkatkan aktivitas saat mereka berupaya memenuhi pesanan;'
    ),
    (
        '2026-03-19',
        '07.30',
        'AUD',
        'High',
        'Employment Change (AUD)',
        '17.8K',
        '20.8K',
        '48.9K',
        'Australian Bureau of Statistics',
        'Perubahan jumlah orang yang bekerja selama bulan sebelumnya',
        'Aktual> Prakiraan = Baik untuk mata uang',
        'Dirilis bulanan, sekitar 15 hari setelah akhir bulan',
        'No Information',
        'Ini adalah data ekonomi penting yang dirilis segera setelah bulan ini berakhir. Kombinasi antara tingkat kepentingan dan tingkat awal menghasilkan dampak pasar yang besar;',
        0,
        NULL,
        'Penciptaan lapangan kerja merupakan indikator utama yang penting dalam belanja konsumen, yang menyumbang sebagian besar kegiatan perekonomian secara keseluruhan;'
    ),
    (
        '2026-03-19',
        '07.30',
        'AUD',
        'High',
        'Unemployment Rate',
        '4.1%',
        '4.1%',
        '4.3%',
        'Australian Bureau of Statistics',
        'Persentase jumlah yang menganggur dan aktif mencari pekerjaan pada bulan sebelumnya;',
        'Aktual> Prakiraan = Baik untuk mata uang',
        'Dirilis bulanan, sekitar 15 hari setelah akhir bulan',
        'No Information',
        NULL,
        0,
        NULL,
        'Meskipun secara umum angka ini dipandang sebagai indikator tertinggal, jumlah pengangguran merupakan sinyal penting mengenai kesehatan perekonomian secara keseluruhan karena belanja konsumen sangat berkorelasi dengan kondisi pasar tenaga kerja;'
    ),
    (
        '2026-03-19',
        '07.30',
        'AUD',
        'Low',
        'RBA Financial Stability Review',
        NULL,
        NULL,
        NULL,
        'Reserve Bank of Australia (RBA)',
        NULL,
        'Lebih hawkish dari prediksi = Bagus untuk mata uang',
        'Dua kali dalam setahun',
        'No Information',
        NULL,
        0,
        NULL,
        'Ini adalah penilaian kondisi dalam sistem keuangan dan risiko potensial terhadap stabilitas keuangan - bukti apabila adanya ketidakseimbangan dapat memberikan wawasan tentang masa depan kebijakan moneter. Sumber pertama kali dirilis Maret 2004;'
    ),
    (
        '2026-03-19',
        '09.45',
        'JPN',
        'High',
        'BOJ Policy Rate',
        '0.75%',
        '0.75%',
        '0.75%',
        'Bank of Japan (latest release)',
        'Suku bunga yang dikenakan atas kelebihan saldo giro pada rekening BOJ;',
        'Realisasi> Prakiraan = Baik untuk mata uang;',
        'Dijadwalkan 8 kali per tahun',
        'No Information',
        'Sumber tidak memberikan waktu rilis pasti - acara ini akan terdaftar sebagai ''Tentatif'' hingga tarif diumumkan. Tingkat suku bunga ini saat ini menjadi target operasi utama BOJ. Sumber pertama kali dirilis pada Januari 2016;',
        0,
        NULL,
        'Suku bunga jangka pendek adalah faktor terpenting dalam penilaian mata uang - pedagang melihat sebagian besar indikator lain hanya untuk memprediksi bagaimana suku bunga akan berubah di masa depan;'
    ),
    (
        '2026-03-19',
        '09.45',
        'JPN',
        'High',
        'Monetary Policy Statement',
        NULL,
        NULL,
        NULL,
        'Bank of Japan',
        NULL,
        'Lebih "hawkish" dibandingkan perkiraan akan cenderung direspon negatif oleh pasar, lebih "dovish" dari perkiraan akan cenderung direspon lebih positif.',
        'Variabel, sekitar 8 kali dalam setahun',
        'No Information',
        'Sumber tidak memberikan waktu rilis pasti - acara tersebut akan terdaftar sebagai ''Tentatif'' hingga pernyataan dikeluarkan. Sumber pertama kali dirilis pada Juli 2008. Sumber mengubah frekuensi rilis dari sekitar 14 kali per tahun menjadi delapan kali per tahun pada Januari 2016;',
        0,
        NULL,
        'Ini adalah salah satu alat utama yang digunakan BOJ untuk berkomunikasi dengan investor mengenai kebijakan moneter. Ini berisi hasil keputusan mereka mengenai pembelian aset dan komentar tentang kondisi ekonomi yang mempengaruhi keputusan mereka. Yang paling penting, hal ini memproyeksikan prospek ekonomi dan memberikan petunjuk mengenai hasil pemungutan suara di masa depan;'
    ),
    (
        '2026-03-19',
        '11.30',
        'JPN',
        'Low',
        'Revised Industrial Production m/m',
        '2.2%',
        '2.2%',
        '4.3%',
        'Kementerian Ekonomi, Perdagangan dan Industri (METI)',
        'Perubahan total nilai output yang disesuaikan dengan inflasi yang dihasilkan oleh produsen, pertambangan, dan utilitas;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 45 hari pasca bulan berjalan',
        'No Information',
        'Daftar ''Sebelumnya'' adalah ''Aktual'' dari rilis Awal dan oleh karena itu data ''Riwayat'' akan tampak tidak berhubungan. Ada 2 versi indikator ini yang dirilis dengan selang waktu sekitar 15 hari - Pendahuluan dan Revisi. Rilisan Awal merupakan rilis paling a',
        0,
        NULL,
        'Ini adalah indikator utama kesehatan perekonomian - produksi bereaksi dengan cepat terhadap naik turunnya siklus bisnis dan berkorelasi dengan kondisi konsumen seperti tingkat lapangan kerja dan pendapatan;'
    ),
    (
        '2026-03-19',
        '13.30',
        'JPN',
        'High',
        'BOJ Press Conference',
        NULL,
        NULL,
        NULL,
        'Bank of Japan',
        NULL,
        'Lebih "hawkish" dibandingkan perkiraan akan cenderung direspon negatif oleh pasar, tapi bila lebih "dovish" dibandingkan perkiraan maka akan cenderung direspon positif.',
        'Dijadwalkan, sekitar 8 kali dalam setahun',
        'No Information',
        'Sumber tidak memberikan waktu mulai yang pasti - acara ini akan terdaftar sebagai ''Tentatif'' hingga konferensi pers dimulai. Sumber mengubah frekuensi rilis dari sekitar 14 kali per tahun menjadi delapan kali per tahun pada Januari 2016;',
        0,
        NULL,
        'Ini adalah salah satu metode utama yang digunakan BOJ untuk berkomunikasi dengan investor mengenai kebijakan moneter. Hal ini mencakup faktor-faktor yang mempengaruhi keputusan suku bunga terkini, prospek perekonomian secara keseluruhan, inflasi, dan petunjuk mengenai kebijakan moneter di masa depan;'
    ),
    (
        '2026-03-19',
        '14.00',
        'GBP',
        'High',
        'Claimant Count Change',
        '28.6K',
        '25.8K',
        '24.7K',
        'Kantor Statistik Nasional (rilis terbaru)',
        'Perubahan jumlah orang yang mengklaim tunjangan terkait pengangguran selama bulan sebelumnya;',
        '''Aktual'' kurang dari ''Prakiraan'' bagus untuk mata uang;',
        'Dirilis setiap bulan, sekitar 16 hari setelah bulan berakhir;',
        'No Information',
        'Ini adalah indikasi pertama dari situasi ketenagakerjaan, yang dirilis sebulan lebih awal dari Tingkat Pengangguran. Sumber mengubah rumus perhitungan seri per Juni 2015;',
        0,
        NULL,
        'Meskipun secara umum dianggap sebagai indikator yang tertinggal, jumlah pengangguran merupakan sinyal penting kesehatan ekonomi secara keseluruhan karena belanja konsumen sangat berkorelasi dengan kondisi pasar tenaga kerja. Pengangguran juga merupakan pertimbangan utama bagi mereka yang mengendalikan kebijakan moneter negara;'
    ),
    (
        '2026-03-19',
        '14.00',
        'GBP',
        'Medium',
        'Average Earnings Index 3m/y',
        '4.2%',
        '3.9%',
        '3.9%',
        'Kantor Statistik Nasional',
        'Perubahan harga bisnis dan gaji pemerintah untuk tenaga kerja, termasuk bonus;',
        'Aktual > Forecast = Bagus untuk mata uang;',
        'Rilis bulanan, sekitar 45 hari setelah bulan berakhir',
        'No Information',
        'Data mewakili rata-rata pergerakan 3 bulan dibandingkan periode yang sama tahun sebelumnya. Angka yang tidak termasuk bonus juga dirilis, namun tidak dimasukkan karena kurang penting. Sumber mengubah rumus perhitungan seri pada Jan 2010;',
        0,
        NULL,
        'Ini adalah indikator utama inflasi konsumen - ketika perusahaan membayar lebih banyak untuk tenaga kerja, maka biaya yang lebih tinggi biasanya dibebankan kepada konsumen;'
    ),
    (
        '2026-03-19',
        '14.00',
        'GBP',
        'Low',
        'Unemployment Rate (GBP)',
        '5.2%',
        '5.2%',
        '5.2%',
        'Kantor Statistik Nasional',
        'Persentase terhadap jumlah angkatan kerja yang tidak bekerja dan aktif mencari pekerjaan selama 3 bulan terakhir;',
        'Aktual aan = Bagus untuk mata uang',
        'Rilis bulanan, sekitar 45 hari setelah bulan berakhir',
        'No Information',
        NULL,
        0,
        NULL,
        'Meskipun secara umum angka ini dipandang sebagai indikator tertinggal, jumlah pengangguran merupakan sinyal penting mengenai kesehatan perekonomian secara keseluruhan karena belanja konsumen sangat berkorelasi dengan kondisi pasar tenaga kerja. Pengangguran juga merupakan pertimbangan utama bagi mereka yang mengendalikan kebijakan moneter negara tersebut;'
    ),
    (
        '2026-03-19',
        '15.30',
        'CHF',
        'High',
        'SNB Monetary Policy Assessment',
        NULL,
        NULL,
        NULL,
        'Swiss National Bank (SNB)',
        NULL,
        'Lebih hawkish dari prediksi = Bagus untuk mata uang',
        'Jadual kuartalan',
        'No Information',
        NULL,
        0,
        NULL,
        'Ini adalah alat utama Dewan Pengurus SNB yang digunakan untuk berkomunikasi dengan para investor mengenai kebijakan moneter. Ini berisi hasil keputusan mereka terhadap tingkat suku bunga dan komentar tentang kondisi ekonomi yang mempengaruhi keputusan mere'
    ),
    (
        '2026-03-19',
        '15.30',
        'CHF',
        'High',
        'SNB Policy Rate',
        '0.00%',
        '0.00%',
        '0.00%',
        'Swiss National Bank (latest release)',
        'Interest rate the SNB seeks to maintain in the short-term money market;',
        '''Actual'' greater than ''Forecast'' is good for currency;',
        'Scheduled quarterly;',
        'No Information',
        'This rate is the SNB''s main operating target. The decision is usually priced into the market, so it tends to be overshadowed by the Monetary Policy Assessment, which is focused on the future. Source first released in Jun 2019;',
        0,
        NULL,
        'Short term interest rates are the paramount factor in currency valuation - traders look at most other indicators merely to predict how rates will change in the future;'
    ),
    (
        '2026-03-19',
        '16.00',
        'CHF',
        'High',
        'SNB Press Conference',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Sikap yang lebih hawkish dari perkiraan akan berdampak baik bagi mata uang;',
        'Dijadwalkan setiap triwulan;',
        'No Information',
        'Konferensi ini diadakan ketika tarif diumumkan pada bulan Juni dan Desember. Durasinya sekitar satu jam dan terdiri dari 2 bagian - pertama pernyataan yang telah disiapkan dibacakan, kemudian konferensi terbuka untuk pertanyaan pers. Pertanyaan-pertanyaan',
        0,
        NULL,
        'Ini adalah salah satu alat utama yang digunakan Dewan Pengurus SNB untuk berkomunikasi dengan investor mengenai kebijakan moneter dan prospek ekonomi;'
    ),
    (
        '2026-03-19',
        '16.44',
        'EUR',
        'Low',
        'Spanish 10-y Bond Auction',
        '3.17',
        NULL,
        '3.48',
        'Sekretariat Keuangan Umum Spanyol',
        'Rata-rata imbal hasil (yield) obligasi 10-tahun pemerintah Spanyol yang dijual melalui lelang, dan lelang bid-to-cover ratio; Hasil Lelang dilaporkan dalam format ''x.xx | x.x'' - nomor pertama adalah tingkat suku bunga rata-rata obligasi yang dijual, dan',
        'Tidak memberikan pengaruh yang konsisten, namun tetap mengimplikasi terhadap risiko dan pertumbuhan.',
        'Variabel, sekitar 8 kali dalam setahun',
        '16-10-2104',
        'Peristiwa ini mencakup obligasi dengan jatuh tempo yang beberapa tahun lebih pendek atau lebih panjang dari 10 tahun, membuat kumpulan data tampak lebih fluktuatif daripada suku bunga 10 tahun yang sebenarnya. Hasil lelang dilaporkan dalam format ''X.XX|X.X'' - angka pertama adalah suku bunga rata-rata obligasi yang dijual, dan angka kedua adalah rasio bid-to-cover (jumlah tawaran yang dibuat per tawaran yang diterima). Sumber tidak memberikan waktu rilis yang pasti - peristiwa ini akan dicantumkan sebagai ''Tentatif'' hingga data dirilis;',
        0,
        NULL,
        'Imbal hasil ditetapkan oleh investor pasar obligasi, dan karenanya dapat digunakan untuk menguraikan prospek investor terhadap suku bunga di masa mendatang. Rasio bid-to-cover menggambarkan likuiditas dan permintaan pasar obligasi, yang dapat digunakan untuk mengukur keyakinan investor;'
    ),
    (
        '2026-03-19',
        '19.00',
        'GBP',
        'High',
        'Monetary Policy Summary',
        NULL,
        NULL,
        NULL,
        'Bank of England (latest release)',
        NULL,
        'More hawkish than expected is good for currency;',
        'Dirilis setiap bulan;',
        'No Information',
        'Sumber pertama kali dirilis pada Agustus 2015;',
        0,
        NULL,
        'Ini adalah salah satu alat utama yang digunakan MPC untuk berkomunikasi dengan investor mengenai kebijakan moneter. Laporan ini berisi hasil pemungutan suara mereka mengenai suku bunga dan langkah-langkah kebijakan lainnya, serta komentar mengenai kondisi ekonomi yang mempengaruhi pemungutan suara mereka. Yang paling penting, laporan ini membahas prospek ekonomi dan memberikan petunjuk mengenai hasil pemungutan suara di masa depan;'
    ),
    (
        '2026-03-19',
        '19.00',
        'GBP',
        'High',
        'MPC Official Bank Rate Votes',
        '0-4-5',
        '0-2-7',
        '0-0-9',
        'Bank of England (BOE)',
        NULL,
        'Lebih hawkish dari perkiraan = Bagus untuk mata uang',
        'Dirilis setiap bulan;',
        'No Information',
        'Pemungutan suara dilaporkan dalam format ''X-X-X'' - angka pertama adalah berapa banyak anggota MPC yang memilih untuk menaikkan suku bunga, angka kedua adalah berapa banyak yang memilih untuk menurunkan suku bunga, dan yang ketiga adalah berapa banyak yang memilih untuk mempertahankan suku bunga;',
        0,
        NULL,
        'Risalah rapat MPC BOE berisi pemungutan suara mengenai suku bunga untuk setiap anggota MPC pada rapat terakhir. Perincian hasil pemungutan suara memberikan gambaran mengenai anggota mana yang mengubah pendirian mereka mengenai suku bunga dan seberapa dekat komite tersebut dalam memberlakukan perubahan suku bunga di masa depan;'
    ),
    (
        '2026-03-19',
        '19.00',
        'GBP',
        'High',
        'Official Bank Rate',
        '3.75%',
        '3.75%',
        '3.75%',
        'Bank of England (BOE)',
        'Suku bunga yang BOE berikan pinjaman kepada lembaga keuangan;',
        'Aktual > Perkiraan = Bagus untuk mata uang',
        'Dijadwalkan setiap bulan;',
        'No Information',
        'Keputusan suku bunga biasanya sudah diperhitungkan di pasar, sehingga cenderung dibayangi oleh Ringkasan Kebijakan Moneter, yang berfokus pada masa depan;',
        0,
        NULL,
        'Suku bunga jangka pendek adalah faktor terpenting dalam penilaian mata uang - pedagang melihat sebagian besar indikator lain hanya untuk memprediksi bagaimana suku bunga akan berubah di masa depan;'
    ),
    (
        '2026-03-19',
        '19.30',
        'US',
        'High',
        'Unemployment Claims',
        '213K',
        '215K',
        '205K',
        'Departemen Tenaga Kerja',
        'Jumlah individu yang pertama kali mengajukan asuransi pengangguran selama seminggu terakhir;',
        '''Aktual'' kurang dari ''Perkiraan'' baik untuk mata uang;',
        'Dirilis setiap minggu, biasanya pada hari Kamis pertama setelah minggu berakhir;',
        '02-04-2026',
        'Ini adalah data ekonomi negara yang paling awal. Dampak pasar berfluktuasi dari minggu ke minggu - cenderung lebih fokus pada rilis ketika pedagang perlu mendiagnosis perkembangan terkini, atau ketika angkanya ekstrem;',
        0,
        NULL,
        'Meskipun secara umum angka ini dipandang sebagai indikator tertinggal, jumlah pengangguran merupakan sinyal penting mengenai kesehatan perekonomian secara keseluruhan karena belanja konsumen sangat berkorelasi dengan kondisi pasar tenaga kerja. Pengangguran juga merupakan pertimbangan utama bagi mereka yang mengendalikan kebijakan moneter negara tersebut;'
    ),
    (
        '2026-03-19',
        '19.30',
        'US',
        'Medium',
        'Philly Fed Manufacturing Index',
        '16.3',
        '8.3',
        '18.1',
        'The Fed of Philadelphia',
        'Tingkat indeks difusi berdasarkan survei produsen di Philadelphia;',
        'Aktual > Perkiraan = Positif',
        'Dirilis setiap bulan, pada hari Kamis ketiga bulan berjalan;',
        'No Information',
        'Di atas 0,0 menunjukkan kondisi membaik, di bawah menunjukkan kondisi memburuk;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan perubahan sentimen dapat menjadi sinyal awal mengenai aktivitas perekonomian di masa depan seperti pembelanjaan, perekrutan tenaga kerja, dan investasi;'
    ),
    (
        '2026-03-19',
        '20.15',
        'EUR',
        'High',
        'Main Refinancing Rate',
        '2.15%',
        '2.15%',
        '2.15%',
        'European Central Bank (latest release)',
        'Suku bunga pada operasi refinancing utama yang menyediakan sebagian besar likuiditas bagi sistem perbankan;',
        '''Aktual'' lebih besar dari ''Perkiraan'' bagus untuk mata uang;',
        'Dijadwalkan 8 kali per tahun;',
        'No Information',
        'Keputusan suku bunga biasanya sudah diperhitungkan oleh pasar, sehingga cenderung dibayangi oleh Konferensi Pers ECB yang diadakan 45 menit kemudian. Sumber mengubah frekuensi rilis dari bulanan menjadi delapan kali per tahun pada Januari 2015;',
        0,
        NULL,
        'Suku bunga jangka pendek adalah faktor terpenting dalam penilaian mata uang - pedagang melihat sebagian besar indikator lain hanya untuk memprediksi bagaimana suku bunga akan berubah di masa depan;'
    ),
    (
        '2026-03-19',
        '20.15',
        'EUR',
        'High',
        'Monetary Policy Statement',
        NULL,
        NULL,
        NULL,
        'European Central Bank (latest release)',
        NULL,
        'Sikap yang lebih hawkish dari perkiraan akan berdampak baik bagi mata uang;',
        'Dijadwalkan 8 kali per tahun;',
        'No Information',
        'ECB biasanya sedikit mengubah pernyataannya pada setiap rilis. Perubahan inilah yang menjadi fokus para pedagang. Sumber pertama kali dirilis pada Maret 2016;',
        0,
        NULL,
        'Ini adalah alat utama yang digunakan ECB untuk berkomunikasi dengan investor mengenai kebijakan moneter. Ini berisi hasil keputusan mereka mengenai suku bunga dan komentar tentang kondisi ekonomi yang mempengaruhi keputusan mereka. Yang paling penting, laporan ini membahas prospek ekonomi dan memberikan petunjuk mengenai hasil keputusan di masa depan;'
    ),
    (
        '2026-03-19',
        '20.45',
        'EUR',
        'High',
        'ECB Press Conference',
        NULL,
        NULL,
        NULL,
        'Bank Sentral Eropa (ECB)',
        NULL,
        'Lebih hawkish dibandingkan perkiraan biasanya akan cenderung direspon negatif oleh pasar, namun bila lebih dovish dari perkiraan akan cenderung direspon positif.',
        'Dijadwalkan 8 kali per tahun, sekitar 45 menit setelah Minimum Bid Rate diumumkan;',
        'No Information',
        'Konferensi pers berlangsung sekitar satu jam dan terdiri dari 2 bagian - pertama pernyataan yang telah disiapkan dibacakan, kemudian konferensi terbuka untuk pertanyaan pers. Pertanyaan-pertanyaan tersebut sering kali mengarah pada jawaban tanpa naskah yang menciptakan volatilitas pasar yang besar. Konferensi pers disiarkan melalui web di situs web ECB dengan sedikit penundaan dari waktu nyata. Sumber mengubah frekuensi rilis dari bulanan menjadi delapan kali per tahun pada Januari 2015;',
        0,
        NULL,
        'Ini adalah metode utama yang digunakan ECB untuk berkomunikasi dengan investor mengenai kebijakan moneter. Bab ini mencakup secara rinci faktor-faktor yang mempengaruhi tingkat suku bunga terkini dan keputusan kebijakan lainnya, seperti prospek perekonomian secara keseluruhan dan inflasi. Yang paling penting, hal ini memberikan petunjuk mengenai kebijakan moneter masa depan;'
    ),
    (
        '2026-03-19',
        '21.00',
        'US',
        'Medium',
        'New Home Sales',
        '712K',
        '725K',
        '587K',
        'Biro Sensus',
        'Jumlah tahunan dari rumah keluarga tunggal baru yang terjual selama bulan sebelumnya;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 25 hari setelah bulan berakhir',
        'No Information',
        'Meskipun ini adalah data bulanan, namun dilaporkan dalam format tahunan (angka bulanan x12);',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian karena penjualan rumah baru memicu efek riak yang luas. Misalnya, furnitur dan peralatan dibeli untuk rumah, hipotek dijual oleh bank pembiayaan, dan perantara dibayar untuk melaksanakan transaksi;'
    ),
    (
        '2026-03-19',
        '21.00',
        'US',
        'Low',
        'Final Wholesale Inventories m/m',
        '0.2%',
        '0.2%',
        '-0.5%',
        'Biro Sensus',
        'Perubahan nilai total barang yang disimpan dalam persediaan oleh pedagang grosir;',
        '''Aktual'' kurang dari ''Perkiraan'' baik untuk mata uang;',
        'Rilis bulanan, sekitar 40 hari setelah bulan berjalan',
        'No Information',
        'Daftar ''Sebelumnya'' adalah ''Aktual'' dari rilis Awal dan oleh karena itu data ''Riwayat'' akan tampak tidak berhubungan. Ada 2 versi indikator ini yang dirilis dengan selang waktu sekitar satu minggu - Pendahuluan dan Final. Rilisan Awal, yang pertama kali di',
        0,
        NULL,
        'Hal ini merupakan sinyal pengeluaran bisnis di masa depan karena perusahaan lebih cenderung membeli barang setelah persediaannya habis;'
    ),
    (
        '2026-03-19',
        '21.30',
        'US',
        'Low',
        'Natural Gas Storage',
        '-38B',
        '39B',
        '35B',
        'Administrasi Informasi Energi',
        'Perubahan jumlah kubik feet dari gas alam yang disimpan di gudang bawah tanah selama seminggu sebelumnya;',
        '''Aktual'' kurang dari ''Perkiraan'' baik untuk mata uang;',
        'Rilis mingguan, sekitar 5 hari setelah minggu berjalan',
        '02-04-2026',
        'Persediaan digunakan untuk menjaga stabilitas harga selama kekurangan pasokan dan periode peningkatan permintaan;',
        0,
        NULL,
        NULL
    ),
    (
        '2026-03-20',
        '08.00',
        'CHN',
        'Medium',
        '1-y Loan Prime Rate',
        '3.00%',
        '3.00%',
        '3.00%',
        'People''s Bank of China',
        'Tingkat bunga yang diberikan bank komersial kepada rumah tangga dan dunia usaha;',
        '''Aktual'' lebih besar dari ''Perkiraan'' bagus untuk mata uang;',
        'Dijadwalkan setiap bulan;',
        'No Information',
        'Ini adalah suku bunga pinjaman acuan yang ditetapkan oleh Bank Rakyat Tiongkok dalam upayanya mempengaruhi suku bunga jangka pendek sebagai bagian dari strategi kebijakan moneternya;',
        0,
        NULL,
        'Suku bunga jangka pendek adalah faktor terpenting dalam penilaian mata uang - pedagang melihat sebagian besar indikator lain hanya untuk memprediksi bagaimana suku bunga akan berubah di masa depan;'
    ),
    (
        '2026-03-20',
        '08.00',
        'CHN',
        'Medium',
        '5-y Loan Prime Rate',
        '3.50%',
        '3.50%',
        '3.50%',
        'People''s Bank of China',
        'Suku bunga yang diterapkan oleh bank umum untuk pinjaman hipotek;',
        '''Aktual'' lebih besar dari ''Perkiraan'' bagus untuk mata uang;',
        'Dijadwalkan setiap bulan;',
        'No Information',
        'Ini adalah suku bunga pinjaman acuan yang ditetapkan oleh Bank Rakyat Tiongkok dalam upayanya mempengaruhi suku bunga jangka pendek sebagai bagian dari strategi kebijakan moneternya;',
        0,
        NULL,
        'Suku bunga jangka pendek adalah faktor terpenting dalam penilaian mata uang - pedagang melihat sebagian besar indikator lain hanya untuk memprediksi bagaimana suku bunga akan berubah di masa depan;'
    ),
    (
        '2026-03-20',
        '14.00',
        'EUR',
        'Low',
        'German PPI m/m',
        '-0.6%',
        '0.3%',
        '-0.5%',
        'Destatis (rilis terbaru)',
        'Perubahan harga barang yang dijual oleh produsen;',
        '''Aktual'' lebih besar dari ''Prakiraan'' bagus untuk mata uang;',
        'Dirilis setiap bulan, sekitar 20 hari setelah bulan berakhir;',
        'No Information',
        NULL,
        0,
        NULL,
        'Ini adalah indikator utama inflasi konsumen - ketika produsen mengenakan biaya lebih untuk barang, biaya yang lebih tinggi biasanya diteruskan ke konsumen;'
    ),
    (
        '2026-03-20',
        '14.00',
        'GBP',
        'Low',
        'Public Sector Net Borrowing',
        '-30.4B',
        '8.6B -',
        '14.3B',
        'Kantor Statistik Federal',
        'Selisih nilai pengeluaran dan pendapatan perusahaan publik, pemerintah pusat, dan pemerintah daerah pada bulan sebelumnya;',
        'Actual st = Bagus untuk mata uang',
        'Rilis bulanan, sekitar 23 hari setelah bulan berakhir',
        'No Information',
        'Angka positif menunjukkan defisit anggaran, angka negatif menunjukkan surplus. Angka ini termasuk "intervensi keuangan" - ada juga angka yang dirilis pada saat yang sama yang tidak termasuk intervensi tersebut;',
        0,
        NULL,
        NULL
    ),
    (
        '2026-03-20',
        '16.00',
        'EUR',
        'Low',
        'Current Account ( EUR )',
        '14.6B',
        '17.2B',
        '37.9B',
        'Bank Sentral Eropa (ECB)',
        'Selisih nilai antara barang, jasa, arus pendapatan, dan transfer sepihak yang diimpor dan diekspor pada bulan sebelumnya;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 50 hari setelah bulan berakhir',
        'No Information',
        'Ini adalah data yang disesuaikan secara musiman (seperti kebanyakan angka FF), berbeda dengan angka yang disesuaikan secara non-musiman yang dilaporkan oleh beberapa kantor berita. Porsi barang tidak berpengaruh karena merupakan duplikat dari data Neraca Perdagangan yang dirilis sekitar seminggu sebelumnya;',
        0,
        NULL,
        'Hal ini terkait langsung dengan permintaan mata uang - peningkatan surplus menunjukkan bahwa pihak asing membeli lebih banyak mata uang domestik untuk melakukan transaksi di wilayah tersebut;'
    ),
    (
        '2026-03-20',
        '16.00',
        'EUR',
        'Low',
        'Italian Trade Balance',
        '5.99B',
        '5.65B',
        '1.09B',
        'Istat (Italian National Institute of Statistic)',
        'Selisih nilai antara barang impor dan ekspor selama bulan yang dilaporkan;',
        'Aktual > Perkiraan = Cenderung positif',
        'Rilis bulanan, sekitar 45 hari setelah bulan berakhir',
        'No Information',
        'Angka positif menunjukkan lebih banyak barang yang diekspor dibandingkan barang impor. Ini adalah salah satu dari sedikit angka penyesuaian non-musiman yang dilaporkan di kalender, karena ini adalah perhitungan utama untuk indikator ini;',
        0,
        NULL,
        NULL
    ),
    (
        '2026-03-20',
        '17.00',
        'EUR',
        'Low',
        'Trade Balance (EUR)',
        '11.6B',
        '12.8B',
        '12.1B',
        'Destatis (Kantor Statistik Federal Jerman)',
        'Selisih nilai antara barang dan jasa impor dan ekspor selama bulan yang dilaporkan;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 40 hari setelah bulan berakhir',
        'No Information',
        'Ini adalah data yang disesuaikan secara musiman (seperti kebanyakan angka FF), berbeda dengan angka yang disesuaikan secara non-musiman yang dilaporkan oleh beberapa kantor berita. Cenderung memiliki dampak yang tidak terlalu besar karena Jerman dan Perancis, yang menyumbang sekitar setengah perekonomian Zona Euro, merilis data perdagangan lebih awal. Neraca Perdagangan yang positif menunjukkan lebih banyak barang dan jasa yang diekspor daripada yang diimpor;',
        0,
        NULL,
        NULL
    ),
    (
        '2026-03-20',
        '18.00',
        'GBP',
        'Low',
        'CBI Industrial Order Expectations',
        '-28',
        '-30',
        '-27',
        'Konfederasi Industri Inggris (Confederation of British Industry)',
        'Tingkat indeks difusi berdasarkan produsen yang disurvei;',
        'Actual > Forecast = Bagus untuk mata uang',
        'Dirilis bulanan, sekitar 3 minggu dari bulan berjalan',
        'No Information',
        'Di atas 0 menunjukkan bertambahnya volume order yang diharapkan, di bawah 0 menunjukkan harapan untuk volume yang lebih rendah;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan perubahan ekspektasi mereka dapat menjadi sinyal awal mengenai aktivitas perekonomian di masa depan seperti belanja, perekrutan tenaga kerja, dan investasi;'
    ),
    (
        '2026-03-20',
        'All Day',
        'JPN',
        'Low',
        'Bank Holiday',
        NULL,
        NULL,
        NULL,
        'Bank of Japan',
        NULL,
        'Likuiditas dan volatilitas yang rendah',
        NULL,
        'No Information',
        'Kebanyakan broker Forex tetap buka setiap hari libur kecuali Natal dan Tahun Baru. Pasar saham dan bank memiliki jadwal liburan yang sedikit berbeda;',
        1,
        'Kebanyakan broker Forex tetap buka setiap hari libur kecuali Natal dan Tahun Baru. Pasar saham dan bank memiliki jadwal liburan yang sedikit berbeda;',
        'Banks facilitate the majority of foreign exchange volume. When they are closed the market is less liquid and speculators become a more dominant market influence. This can lead to both abnormally low and abnormally high volatility;'
    ),
    (
        '2026-03-20',
        'Tentative',
        'US',
        'Low',
        'Fed Monetary Policy Report',
        NULL,
        NULL,
        NULL,
        'Federal Reserve (latest release)',
        NULL,
        'More hawkish than expected is good for currency;',
        'Twice per year;',
        '27-04-2026',
        'Report provides a summary of discussions of the conduct of monetary policy and economic developments and prospects for the future. It is submitted, along with testimony from the Federal Reserve Chair, to the Senate Committee on Banking, Housing, and Urban',
        0,
        NULL,
        NULL
    );

-- Insert category hanya jika kombinasi country + impact + figures belum ada
INSERT INTO
    economic_calendar_categories (
        country,
        impact,
        figures,
        sources,
        measures,
        usual_effect,
        frequency,
        next_released,
        notes,
        isBankHoliday,
        bankHolidayNote,
        why_trader_care,
        created_at,
        updated_at
    )
SELECT DISTINCT
    t.country,
    t.impact,
    t.figures,
    t.sources,
    t.measures,
    t.usual_effect,
    t.frequency,
    t.next_released,
    t.notes,
    t.isBankHoliday,
    t.bankHolidayNote,
    t.why_trader_care,
    NOW(),
    NOW()
FROM tmp_economic_calendar_import t
WHERE
    NOT EXISTS (
        SELECT 1
        FROM economic_calendar_categories c
        WHERE
            c.country COLLATE utf8mb4_unicode_ci = t.country COLLATE utf8mb4_unicode_ci
            AND c.impact COLLATE utf8mb4_unicode_ci = t.impact COLLATE utf8mb4_unicode_ci
            AND c.figures COLLATE utf8mb4_unicode_ci = t.figures COLLATE utf8mb4_unicode_ci
    );

-- Tetap insert economic_calendars, pakai category yang sudah ada / baru dibuat
-- Dan skip jika detail kalender dengan kombinasi date + time + country + figures sudah ada
INSERT INTO
    economic_calendars (
        economic_calendar_category_id,
        date,
        time,
        country,
        impact,
        figures,
        previous,
        forecast,
        actual,
        sources,
        measures,
        usual_effect,
        frequency,
        next_released,
        notes,
        isBankHoliday,
        bankHolidayNote,
        why_trader_care,
        created_at,
        updated_at
    )
SELECT
    c.id,
    t.date_value,
    t.time_value,
    t.country,
    t.impact,
    t.figures,
    t.previous_value,
    t.forecast_value,
    t.actual_value,
    t.sources,
    t.measures,
    t.usual_effect,
    t.frequency,
    t.next_released,
    t.notes,
    t.isBankHoliday,
    t.bankHolidayNote,
    t.why_trader_care,
    NOW(),
    NOW()
FROM
    tmp_economic_calendar_import t
    JOIN economic_calendar_categories c ON c.country COLLATE utf8mb4_unicode_ci = t.country COLLATE utf8mb4_unicode_ci
    AND c.impact COLLATE utf8mb4_unicode_ci = t.impact COLLATE utf8mb4_unicode_ci
    AND c.figures COLLATE utf8mb4_unicode_ci = t.figures COLLATE utf8mb4_unicode_ci
WHERE
    NOT EXISTS (
        SELECT 1
        FROM economic_calendars ec
        WHERE
            ec.date = t.date_value
            AND ec.time COLLATE utf8mb4_unicode_ci = t.time_value COLLATE utf8mb4_unicode_ci
            AND ec.country COLLATE utf8mb4_unicode_ci = t.country COLLATE utf8mb4_unicode_ci
            AND ec.figures COLLATE utf8mb4_unicode_ci = t.figures COLLATE utf8mb4_unicode_ci
    );

COMMIT;