-- Generated from payload updatedAt: 2026-03-27T03:23:07.589Z
START TRANSACTION;

DROP TEMPORARY TABLE IF EXISTS tmp_economic_calendar_import;

CREATE TEMPORARY TABLE tmp_economic_calendar_import (
    date_value DATE NULL,
    time_value VARCHAR(50) NULL,
    country VARCHAR(50) NULL,
    impact VARCHAR(20) NULL,
    figures VARCHAR(255) NULL,
    previous_value VARCHAR(100) NULL,
    forecast_value VARCHAR(100) NULL,
    actual_value VARCHAR(100) NULL,
    sources TEXT NULL,
    measures LONGTEXT NULL,
    usual_effect LONGTEXT NULL,
    frequency LONGTEXT NULL,
    next_released VARCHAR(100) NULL,
    notes LONGTEXT NULL,
    isBankHoliday TINYINT(1) NOT NULL DEFAULT 0,
    bankHolidayNote LONGTEXT NULL,
    why_trader_care LONGTEXT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

INSERT INTO
    tmp_economic_calendar_import (
        date_value,
        time_value,
        country,
        impact,
        figures,
        previous_value,
        forecast_value,
        actual_value,
        sources,
        measures,
        usual_effect,
        frequency,
        next_released,
        notes,
        isBankHoliday,
        bankHolidayNote,
        why_trader_care
    )
VALUES (
        '2026-03-30',
        '06.50',
        'JPN',
        'Low',
        'BOJ Summary of Opinions',
        NULL,
        NULL,
        NULL,
        'Bank of Japan (latest release)',
        '-',
        'More hawkish than expected is good for currency;',
        'Scheduled 8 times per year, about 10 days after the Monetary Policy Statement is released;',
        '30-03-2026',
        'This report includes the BOJ''s projection for inflation and economic growth. Source first released in Feb 2016;',
        0,
        NULL,
        'It''s the primary tool the BOJ uses to communicate their economic and monetary projections to investors;'
    ),
    (
        '2026-03-30',
        '13.00',
        'EUR',
        'Low',
        'German Import Prices m/m',
        '1.1%',
        NULL,
        NULL,
        'Destatis (Kantor Statistik Federal Jerman)',
        'Perubahan harga barang impor yang dibeli di dalam negeri;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 26 hari setelah periode bulan berjalan',
        '30-03-2026',
        '-',
        0,
        NULL,
        'Hal ini berkontribusi terhadap inflasi bagi dunia usaha dan konsumen, terutama mereka yang sangat bergantung pada barang impor;'
    ),
    (
        '2026-03-30',
        '13.00',
        'EUR',
        'Low',
        'German Retail Sales m/m',
        NULL,
        NULL,
        NULL,
        'Destatis (Kantor Statistik Federal Jerman)',
        'Perubahan nilai total penjualan yang disesuaikan dengan inflasi di tingkat ritel, tidak termasuk mobil dan SPBU;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 30 hari setelah periode bulan berjalan',
        '30-03-2026',
        '-',
        0,
        NULL,
        'Ini adalah ukuran utama belanja konsumen, yang menyumbang sebagian besar aktivitas perekonomian secara keseluruhan;'
    ),
    (
        '2026-03-30',
        '13.00',
        'GBP',
        'Low',
        'Nationwide HPI m/m',
        NULL,
        NULL,
        NULL,
        'Nationwide Building Society (latest release)',
        'Perubahan harga jual rumah yang di danai KPR secara menyeluruh;',
        'Aktual > Perkiraan = Bagus untuk mata uang',
        'Rilis bulanan, sekitar akhir dari bulan berjalan',
        '30-03-2026',
        'Ini adalah laporan paling awal kedua di Inggris mengenai inflasi perumahan;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan industri perumahan karena kenaikan harga rumah menarik investor dan memacu aktivitas industri;'
    ),
    (
        '2026-03-30',
        '14.00',
        'CHF',
        'Low',
        'KOF Economic Barometer',
        '104.2',
        NULL,
        NULL,
        'KOF Economic Research Agency',
        'Tingkat indeks gabungan berdasarkan pada 219 indikator ekonomi;',
        'Aktual > Perkiraan = Bagus untuk mata uang',
        'Dirilis bulanan, sekitar akhir dari bulan berjalan',
        '30-03-2026',
        'Indeks ini dirancang untuk memprediksi arah perekonomian selama 6 bulan ke depan. Sumber mengubah rumus perhitungan seri pada April 2006 dan April 2014;',
        0,
        NULL,
        '-'
    ),
    (
        '2026-03-30',
        '15.30',
        'GBP',
        'Low',
        'M4 Money Supply m/m',
        '-0.1%',
        NULL,
        NULL,
        'Bank of England',
        'Perubahan jumlah mata uang dalam negeri yang beredar dan disimpan di bank;',
        '''Aktual'' lebih besar dari ''Perkiraan'' bagus untuk mata uang;',
        'Dirilis setiap bulan, sekitar 30 hari setelah bulan berakhir;',
        '30-03-2026',
        'Sumber mengubah seri dari format pendahuluan/final menjadi rilis tunggal, pada November 2010;',
        0,
        NULL,
        'Hal ini berkorelasi positif dengan tingkat suku bunga - pada awal siklus ekonomi, peningkatan jumlah uang beredar menyebabkan pengeluaran dan investasi tambahan, dan kemudian pada siklus tersebut, peningkatan jumlah uang beredar menyebabkan inflasi;'
    ),
    (
        '2026-03-30',
        '15.30',
        'GBP',
        'Low',
        'Mortgage Approvals',
        '60K',
        NULL,
        NULL,
        'Bank of England',
        'Jumlah Hipotek baru yang disetujui untuk pembelian rumah selama bulan sebelumnya;',
        'Aktual > Perkiraan = Bagus untuk mata uang',
        'Rilis bulanan, sekitar 30 hari setelah bulan berakhir',
        '30-03-2026',
        'Cenderung memiliki dampak yang tidak terlalu besar karena sekitar 60% dari seluruh hipotek dilindungi oleh data Persetujuan Hipotek BBA yang dirilis beberapa hari sebelumnya;',
        0,
        NULL,
        '-'
    ),
    (
        '2026-03-30',
        '15.30',
        'GBP',
        'Low',
        'Net Lending to Individuals m/m',
        '5.9B',
        NULL,
        NULL,
        'Bank of England (BOE)',
        'Perubahan nilai total kredit baru yang dikeluarkan untuk konsumen;',
        'Aktual > Perkiraan = Bagus untuk mata uang',
        'Rilis bulanan, sekitar 30 hari setelah bulan pengamatan berakhir',
        '30-03-2026',
        '-',
        0,
        NULL,
        'Ini berkorelasi dengan pengeluaran konsumen dan kepercayaan - meningkatnya tingkat utang adalah tanda bahwa pemberi pinjaman (bank kreditur) merasa merasa lebih nyaman untuk menyalurkan pinjaman, dan para konsumen pun yakin terhadap posisi keuangan mereka'
    ),
    (
        '2026-03-30',
        'All Day',
        'EUR',
        'Medium',
        'German Prelim CPI m/m',
        '0.2%',
        NULL,
        NULL,
        'Destatis (Kantor Statistik Federal Jerman)',
        'Perubahan harga barang dan jasa yang dibeli konsumen;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar akhir periode bulan berjalan',
        '30-03-2026',
        'Terdaftar sebagai acara ''Sepanjang Hari'' karena ''Aktual'' terdiri dari data dari 6 negara bagian Jerman yang melaporkan CPI mereka sepanjang hari. Ada 2 versi CPI yang dirilis dengan selang waktu sekitar 15 hari - Penyisihan dan Final. Rilis awal ini merupakan inflasi konsumen terbesar yang paling awal terjadi di Zona Euro;',
        0,
        NULL,
        'Harga konsumen menyumbang sebagian besar inflasi secara keseluruhan. Inflasi penting dalam penilaian mata uang karena kenaikan harga menyebabkan bank sentral menaikkan suku bunga untuk menghormati mandat pengendalian inflasi;'
    ),
    (
        '2026-03-31',
        '06.30',
        'JPN',
        'Low',
        'Tokyo Core CPI y/y',
        '1.8%',
        NULL,
        NULL,
        'Biro Statistik',
        'Perubahan harga barang dan jasa yang dibeli konsumen di Tokyo, tidak termasuk makanan segar;',
        'Aktual > Perkiraan = Positif',
        'RIlis bulanan, biasanya pada Jumat terakhir dari periode bulan berjalan',
        '31-03-2026',
        'Tokyo adalah kota terpadat di Jepang dan merilis data CPI sebulan sebelum CPI Nasional. Data awal ini dianggap sebagai rilis inflasi konsumen yang paling penting. Dampaknya cenderung ringan namun bervariasi dari bulan ke bulan;',
        0,
        NULL,
        'Harga konsumen menyumbang sebagian besar inflasi secara keseluruhan. Inflasi penting untuk penilaian mata uang karena kenaikan harga menyebabkan bank sentral memperketat kebijakan moneter untuk menghormati mandat pengendalian inflasi;'
    ),
    (
        '2026-03-31',
        '06.30',
        'JPN',
        'Low',
        'Unemployment Rate',
        '2.7%',
        NULL,
        NULL,
        'Biro Statistik',
        'Persentase total angkatan kerja yang menganggur dan aktif mencari pekerjaan selama bulan sebelumnya;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 30 hari setelah bulan berjalan',
        '31-03-2026',
        'Cenderung memiliki dampak yang tidak terlalu besar dibandingkan dengan data ketenagakerjaan dari negara lain karena perekonomian Jepang lebih bergantung pada sektor industri dibandingkan belanja pribadi;',
        0,
        NULL,
        '-'
    ),
    (
        '2026-03-31',
        '06.50',
        'JPN',
        'Low',
        'Prelim Industrial Production m/m',
        '4.3%',
        NULL,
        NULL,
        'Kementerian Ekonomi, Perdagangan dan Industri (METI)',
        'Perubahan nilai total inflasi yang disesuaikan dari output yang dihasilkan oleh pabrikan, pertambangan, dan perusahaan utilitas;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 30 hari setelah periode bulan berjalan',
        '31-03-2026',
        'Ada 2 versi indikator ini yang dirilis dengan selang waktu sekitar 15 hari - Pendahuluan dan Revisi. Rilisan Awal adalah yang paling awal sehingga cenderung mempunyai dampak yang paling besar;',
        0,
        NULL,
        'Ini adalah indikator utama kesehatan perekonomian - produksi bereaksi dengan cepat terhadap naik turunnya siklus bisnis dan berkorelasi dengan kondisi konsumen seperti tingkat lapangan kerja dan pendapatan;'
    ),
    (
        '2026-03-31',
        '06.50',
        'JPN',
        'Low',
        'Retail Sales y/y (JPN)',
        '1.8%',
        NULL,
        NULL,
        'METI (rilis terbaru)',
        'Perubahan nilai total penjualan di tingkat ritel;',
        'Sebenarnya'' lebih besar dari ''Prakiraan'' baik untuk mata uang;',
        'Dirilis setiap bulan, sekitar 27 hari setelah bulan berakhir;',
        '31-03-2026',
        '-',
        0,
        NULL,
        'Ini adalah ukuran utama pengeluaran konsumen, yang menyumbang sebagian besar kegiatan ekonomi secara keseluruhan;'
    ),
    (
        '2026-03-31',
        '07.30',
        'AUD',
        'Low',
        'Monetary Policy Meeting Minutes (AUD)',
        NULL,
        NULL,
        NULL,
        'Reserve Bank of Australia (RBA)',
        '-',
        'Lebih hawkish dari perkiraan = Bagus untuk mata uang',
        '8 kali per tahun, 2 minggu setelah Suku Bunga Acuan diumumkan;',
        '31-03-2026',
        'Sumber pertama kali dirilis pada Desember 2007;',
        0,
        NULL,
        'Ini mencatat perincian dari pertemuan terbaru Dewan Reserve Bank of Australia, menyediakan wawasan mendalam tentang kondisi ekonomi yang mempengaruhi keputusan mereka dalam menetapkan tingkat suku bunga;'
    ),
    (
        '2026-03-31',
        '07.30',
        'AUD',
        'Low',
        'Private Sector Credit m/m',
        '0.5%',
        NULL,
        NULL,
        'Reserve Bank of Australia',
        'Perubahan nilai total kredit baru yang dikeluarkan untuk konsumen dan bisnis',
        'Aktual > Perkiraan = Positif',
        'Dirilis bulanan, pada hari kerja terakhir bulan berikut',
        '31-03-2026',
        '-',
        0,
        NULL,
        'Pinjaman dan pengeluaran berkorelasi positif - konsumen dan bisnis cenderung mencari kredit ketika mereka percaya diri dalam posisi keuangan masa depan mereka dan merasa uang belanja nyaman'
    ),
    (
        '2026-03-31',
        '08.30',
        'CHN',
        'High',
        'HSBC Flash Manufacturing PMI',
        '49.0',
        NULL,
        NULL,
        'Markit',
        'Tingkat indeks difusi berdasarkan survei terhadap manajer pembelian pada industri manufaktur; Angka diatas 50,0 mengindikasikan ekspansi industri, tapi angka di bawah itu menunjukkan kontraksi; Ada 2 versi laporan yang dirilis terpisah sekitar seming',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 3 minggu dalam bulan berjalan',
        '31-03-2026',
        NULL,
        0,
        NULL,
        NULL
    ),
    (
        '2026-03-31',
        '08.30',
        'CHN',
        'Medium',
        'Non-Manufacturing PMI (CHN)',
        '49.5',
        NULL,
        NULL,
        'Federasi Logistik & Pembelian China (CFLP)',
        'Tingkat indeks difusi berdasarkan survey atas manajer pembelian dalam industri jasa;',
        'Aktual > Perkiraan = Positif',
        'Dirilis setiap bulan, pada hari terakhir bulan berjalan;',
        '31-03-2026',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Data Tiongkok dapat berdampak luas pada pasar mata uang karena pengaruh Tiongkok terhadap perekonomian global dan sentimen investor. Sumber mengubah seri dari penyesuaian non-musiman menjadi penyesuaian musiman pada April 2012;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-03-31',
        '12.00',
        'JPN',
        'Low',
        'Housing Starts y/y',
        '-0.4%',
        NULL,
        NULL,
        'MLIT (latest release)',
        'Change in the number of new residential buildings that began construction;',
        '''Actual'' greater than ''Forecast'' is good for currency;',
        'Released monthly, about 30 days after the month ends;',
        '31-03-2026',
        NULL,
        0,
        NULL,
        'It''s a leading indicator of economic health because building construction produces a wide-reaching ripple effect. For example, jobs are created for the construction workers, subcontractors and inspectors are hired, and various construction services are purchased by the builder;'
    ),
    (
        '2026-03-31',
        '13.00',
        'GBP',
        'Low',
        'Current Account (GBP)',
        '-12.1B',
        NULL,
        NULL,
        'Kantor Statistik Nasional',
        'Selisih nilai antara barang impor dan ekspor dari jasa, arus pendapatan, dan transfer unilateral selama kuartal sebelumnya;',
        'Aktual > Perkiraan = Bagus untuk mata uang',
        'Rilis kuartalan, sekitar 85 hari setelah kuartal berakhir',
        '31-03-2026',
        'Porsi untuk barang dan jasa tidak memberikan pengaruh karena ini merupakan duplikasi dari data trade balance bulanan;',
        0,
        NULL,
        'Ini langsung terkait dengan permintaan mata uang - surplus yang meningkat menunjukkan bahwa orang asing biasanya akan membeli lebih dari mata uang domestik untuk melakukan transaksi di dalam negeri;'
    ),
    (
        '2026-03-31',
        '13.00',
        'GBP',
        'Low',
        'Final GDP q/q (GBP)',
        '0.1%',
        NULL,
        NULL,
        'Kantor Statistik Nasional',
        'Perubahan nilai yang disesuaikan dengan inflasi dari seluruh barang dan jasa yang dihasilkan oleh perekonomian;',
        'Aktual > Perkiraan = Bagus untuk mata uang',
        'Rilis kuartalan, sekitar 85 hari setelah kuartal berakhir',
        '31-03-2026',
        'Ada 3 versi dari data GDP yang dirilis dalam sebulan secara terpisah - 1. Preliminary, 2.Estimasi, dan Final. Rilis Preliminary (awal) adalah cenderung memiliki dampak yang paling signifikan dibandingkan data Estimasi ataupun data Final;',
        0,
        NULL,
        'Ini adalah ukuran terluas dari kegiatan ekonomi dan tolak ukur utama atas kesehatan perekonomian;'
    ),
    (
        '2026-03-31',
        '13.45',
        'EUR',
        'Low',
        'French Consumer Spending m/m',
        '0.5%',
        NULL,
        NULL,
        'INSEE (National Institute of Statistics and Economic Studies)',
        'Perubahan nilai inflasi yang disesuaikan dari seluruh pengeluaran barang oleh konsumen;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 27 hari setelah periode bulan berjalan',
        '31-03-2026',
        '-',
        0,
        NULL,
        'Ini adalah tolak ukur utama belanja konsumen, yang menyumbang mayoritas aktivitas ekonomi secara keseluruhan.'
    ),
    (
        '2026-03-31',
        '13.45',
        'EUR',
        'Low',
        'French Prelim CPI m/m',
        '0.6%',
        NULL,
        NULL,
        'INSEE',
        'Perubahan harga barang dan jasa yang dibeli konsumen;',
        '''Aktual'' lebih besar dari ''Perkiraan'' bagus untuk mata uang;',
        'Dirilis setiap bulan, sekitar akhir bulan berjalan;',
        '31-03-2026',
        'Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar dua minggu ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Pendahuluan dan Final. Rilisan Awal, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Januari 2016, merupakan rilis paling awal sehingga cenderung memiliki dampak paling besar. Ini adalah salah satu dari sedikit angka penyesuaian non-musiman yang dilaporkan di kalender, karena ini adalah perhitungan utama untuk indikator ini;',
        0,
        NULL,
        '-'
    ),
    (
        '2026-03-31',
        '14.55',
        'EUR',
        'Low',
        'German Unemployment Change',
        '1K',
        NULL,
        NULL,
        'Destatis (Kantor Statistik Federal Jerman)',
        'Perubahan jumlah pengangguran pada bulan sebelumnya;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 30 hari setelah periode bulan berjalan',
        '31-03-2026',
        '-',
        0,
        NULL,
        'Meskipun secara umum angka ini dipandang sebagai indikator tertinggal, jumlah pengangguran merupakan sinyal penting mengenai kesehatan perekonomian secara keseluruhan karena belanja konsumen sangat berkorelasi dengan kondisi pasar tenaga kerja;'
    ),
    (
        '2026-03-31',
        '16.00',
        'EUR',
        'Medium',
        'Core CPI Flash Estimate y/y',
        '2.4%',
        NULL,
        NULL,
        'Eurostat',
        'Perubahan harga barang dan jasa yang dibeli oleh konsumen, tidak termasuk makanan, energi, alkohol, dan tembakau;',
        'Aktual > Perkiraan = Cenderung Positif Untuk Mata Uang',
        'Rilis bulanan, biasanya pada hari kerja terakhir di bulan berjalan',
        '31-03-2026',
        'Eurostat mendasarkan perkiraan ini pada 13 negara anggota kawasan euro yang melaporkan data awal CPI. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar dua minggu ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan April 2013, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
        0,
        NULL,
        'Harga-harga konsumen memberikan kontribusi untuk mayoritas tingkat inflasi secara keseluruhan. Inflasi penting untuk penilaian mata uang karena kenaikan harga-harga akan bisa membuat bank sentral menaikkan suku bunga guna meredam kenaikan inflasi;'
    ),
    (
        '2026-03-31',
        '16.00',
        'EUR',
        'Medium',
        'CPI Flash Estimate y/y',
        '1.9%',
        NULL,
        NULL,
        'Komisi Statistik Wilayah Euro (Eurostat)',
        'Perubahan harga barang dan jasa yang dibeli oleh konsumen;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, hari kerja terakhir pada periode bulan berjalan',
        '31-03-2026',
        'Eurostat mendasarkan perkiraan ini pada harga energi dan 13 negara anggota kawasan euro yang melaporkan data awal CPI. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar dua minggu ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Flash dan Final. Laporan ini masih sangat dini dan cenderung mempunyai dampak yang signifikan;',
        0,
        NULL,
        'Harga konsumen menyumbang sebagian besar inflasi secara keseluruhan. Inflasi penting dalam penilaian mata uang karena kenaikan harga menyebabkan bank sentral menaikkan suku bunga untuk mengendalikan inflasi;'
    ),
    (
        '2026-03-31',
        '16.00',
        'EUR',
        'Low',
        'Italian Prelim CPI m/m',
        '0.7%',
        NULL,
        NULL,
        'Istat (Italian National Institute of Statistic)',
        'Perubahan harga barang dan jasa yang dibeli oleh konsumen;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar akhir bulan berjalan',
        '31-03-2026',
        'Ada 2 versi CPI yang dirilis dengan selang waktu sekitar 25 hari - Penyisihan dan Final. Rilis awal ini sangat dini namun dampaknya tidak terlalu besar karena dampak Italia yang relatif kecil terhadap Zona Euro. Final tidak disertakan karena kurang penting;',
        0,
        NULL,
        '-'
    ),
    (
        '2026-03-31',
        '20.00',
        'US',
        'Low',
        'HPI m/m',
        '0.1%',
        NULL,
        NULL,
        'Agen Pembiayaan Rumah Federal (FHFA)',
        'Perubahan harga pembelian rumah dengan hipotek yang didukung oleh Fannie Mae dan Freddie Mac;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 60 hari setelah bulan berjalan',
        '31-03-2026',
        'Sumber frekuensi m/m dimulai pada bulan Maret 2008;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan industri perumahan karena kenaikan harga rumah menarik investor dan memacu aktivitas industri;'
    ),
    (
        '2026-03-31',
        '20.00',
        'US',
        'Low',
        'S&P/CS Composite-20 HPI y/y',
        '1.4%',
        NULL,
        NULL,
        'Standard & Poor''s',
        'Perubahan harga jual rumah keluarga tunggal di 20 daerah metropolitan; Ini adalah salah satu dari beberapa angka non-musiman yang disesuaikan yang dilaporkan dalam kalender ekonomi; Ini merupakan indikator utama kesehatan industri perumahan karena ke',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 60 hari setelah periode bulan berjalan',
        '31-03-2026',
        'Ini adalah salah satu dari sedikit angka yang tidak disesuaikan secara musiman yang dilaporkan pada kalender, karena ini adalah perhitungan utama untuk indikator ini;',
        0,
        NULL,
        'Ini merupakan indikator utama kesehatan industri perumahan karena kenaikan harga rumah menarik investor dan mendorong aktivitas industri;'
    ),
    (
        '2026-03-31',
        '20.45',
        'US',
        'Low',
        'Chicago PMI',
        '57.7',
        NULL,
        NULL,
        'MNI',
        'Tingkat indeks difusi didasarkan pada survey manager pembelian di daerah Chicago;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, hari kerja terakhir pada periode bulan berjalan',
        '31-03-2026',
        'Data diberikan kepada pelanggan MNI 3 menit sebelum waktu rilis publik yang tercantum di kalender - reaksi awal pasar biasanya merupakan hasil perdagangan yang dilakukan oleh pelanggan tersebut. Di atas 50,0 menunjukkan ekspansi, di bawah menunjukkan kontraksi;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-03-31',
        '21.00',
        'US',
        'High',
        'JOLTS Job Openings',
        '6.95M',
        NULL,
        NULL,
        'Biro Statistik Tenaga Kerja',
        'Jumlah lowongan pekerjaan selama bulan yang dilaporkan, tidak termasuk pada industri pertanian;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 40 hari setelah bulan berjalan',
        '31-03-2026',
        'Laporan ini dirilis akhir, namun dapat berdampak pada pasar karena lowongan pekerjaan merupakan indikator utama lapangan kerja secara keseluruhan;',
        0,
        NULL,
        'Penciptaan lapangan kerja merupakan indikator utama yang penting dalam belanja konsumen, yang menyumbang sebagian besar kegiatan ekonomi secara keseluruhan;'
    ),
    (
        '2026-03-31',
        '21.00',
        'US',
        'Medium',
        'CB Consumer Confidence',
        '91.2',
        NULL,
        NULL,
        'The Conference Board Inc. (latest release)',
        'Level of a composite index based on surveyed households;',
        '''Actual'' greater than ''Forecast'' is good for currency;',
        'Released monthly, on the last Tuesday of the current month;',
        '31-03-2026',
        '-',
        0,
        NULL,
        'Financial confidence is a leading indicator of consumer spending, which accounts for a majority of overall economic activity;'
    ),
    (
        '2026-04-01',
        '-',
        'JPN',
        'Low',
        'Final Manufacturing PMI (JPN)',
        NULL,
        NULL,
        NULL,
        'S&P Global',
        'Tingkat indeks difusi berdasarkan survey terhadap manajer pembelian dalam industri manufaktur;',
        'Aktual > Perkiraan = Positif',
        'RIlis bulanan, biasanya hari kerja terakhir dari periode bulan berjalan',
        '02-06-2026',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Daftar ''Sebelumnya'' adalah ''Aktual'' dari rilis Flash dan oleh karena itu data ''Riwayat'' akan tampak tidak berhubungan. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Mei 2014, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-04-01',
        '03.30',
        'US',
        'Low',
        'API Weekly Statistical Bulletin',
        NULL,
        NULL,
        NULL,
        'API (latest release)',
        '-',
        '-',
        'Released weekly, 3 days after the week ends;',
        '01-04-2026',
        '-',
        0,
        NULL,
        '-'
    ),
    (
        '2026-04-01',
        '07.30',
        'AUD',
        'Low',
        'Building Approvals m/m',
        '-7.2%',
        NULL,
        NULL,
        'Australian Bureau of Statistics / Biro Statistik Australia',
        'Perubahan jumlah persetujuan bangunan baru yang dikeluarkan;',
        'Aktual > Perkiraan = Bagus untuk mata uang',
        'Rilis bulanan, sekitar 30 hari setelah bulan berakhir',
        '01-04-2026',
        '-',
        0,
        NULL,
        'Ini merupakan ukuran yang sangat baik untuk aktivitas konstruksi di masa depan karena mendapatkan persetujuan pemerintah merupakan salah satu langkah pertama dalam membangun gedung baru. Konstruksi penting karena menghasilkan efek riak yang luas misalnya, lapangan kerja diciptakan untuk pekerja konstruksi, subkontraktor dan pengawas dipekerjakan, dan berbagai layanan dibeli oleh pembangun;'
    ),
    (
        '2026-04-01',
        '12.30',
        'AUD',
        'Low',
        'Commodity Prices y/y',
        '3.4%',
        NULL,
        NULL,
        'Reserve Bank of Australia (latest release)',
        'Perubahan harga jual komoditi ekspor;',
        '''Actual'' greater than ''Forecast'' is good for currency;',
        'Dirilis setiap bulan, pada hari kerja pertama setelah bulan berakhir;',
        '01-04-2026',
        'Komoditas menyumbang lebih dari separuh pendapatan ekspor Australia. Sumber mengubah rumus perhitungan seri pada November 2009;',
        0,
        NULL,
        'Hal ini merupakan indikator utama neraca perdagangan suatu negara dengan negara lain karena kenaikan harga komoditas meningkatkan pendapatan ekspor;'
    ),
    (
        '2026-04-01',
        '13.30',
        'CHF',
        'Low',
        'Retail Sales y/y (CHF)',
        '-1.1%',
        NULL,
        NULL,
        'Kantor Statistik Federal',
        'Perubahan nilai total penjualan yang disesuaikan dengan inflasi di tingkat ritel, tidak termasuk mobil dan pompa bensin;',
        'Aktual > Forecast = Bagus untuk mata uang',
        'Rilis bulanan, sekitar 35 hari setelah bulan berakhir',
        '01-04-2026',
        'Sumber mengubah rumus perhitungan seri pada Jan 2010;',
        0,
        NULL,
        'Ini adalah ukuran utama belanja konsumen, yang menyumbang mayoritas aktivitas ekonomi secara keseluruhan;'
    ),
    (
        '2026-04-01',
        '14.15',
        'EUR',
        'Low',
        'Spanish Manufacturing PMI',
        '50.0',
        NULL,
        NULL,
        'Markit',
        'Tingkat indeks difusi berdasarkan survey atas manajer pembelian dalam industri manufaktur;',
        'Aktual > Perkiraan = Positif',
        'RIlis bulanan, biasanya hari kerja pertama setelah periode bulan berjalan',
        '01-04-2026',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-04-01',
        '14.30',
        'CHF',
        'Low',
        'Manufacturing PMI',
        '47.4',
        NULL,
        NULL,
        NULL,
        'Level of a diffusion index based on surveyed purchasing managers;',
        '''Actual'' greater than ''Forecast'' is good for currency;',
        'Released monthly, on the first business day after the month ends;',
        '01-04-2026',
        'Above 50.0 indicates industry expansion, below indicates contraction;',
        0,
        NULL,
        'It''s a leading indicator of economic health - businesses react quickly to market conditions, and their purchasing managers hold perhaps the most current and relevant insight into the company''s view of the economy;'
    ),
    (
        '2026-04-01',
        '14.45',
        'EUR',
        'Low',
        'Italian Manufacturing PMI',
        '50.6',
        NULL,
        NULL,
        'S&P Global (latest release)',
        'Tingkat indeks difusi berdasarkan survey manajer pembelian dalam industri manufaktur;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, pada hari kerja pertama setelah bulan berakhir',
        '01-04-2026',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-04-01',
        '14.50',
        'EUR',
        'Low',
        'French Final Manufacturing PMI',
        NULL,
        NULL,
        NULL,
        'S&P Global',
        'Tingkat indeks difusi berdasarkan survei manajer pembelian di industri manufaktur;',
        '''Aktual'' lebih besar dari ''Perkiraan'' bagus untuk mata uang;',
        'Dirilis setiap bulan, pada hari kerja pertama setelah bulan berakhir;',
        '01-04-2026',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Daftar ''Sebelumnya'' adalah ''Aktual'' dari rilis Flash dan oleh karena itu data ''Riwayat'' akan tampak tidak berhubungan. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Maret 2008, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-04-01',
        '14.55',
        'EUR',
        'Low',
        'German Final Manufacturing PMI',
        NULL,
        NULL,
        NULL,
        'S&P Global',
        'Tingkat indeks difusi berdasarkan survei manajer pembelian di industri manufaktur;',
        '''Aktual'' lebih besar dari ''Perkiraan'' bagus untuk mata uang;',
        'Dirilis setiap bulan, pada hari kerja pertama setelah bulan berakhir;',
        '01-04-2026',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Daftar ''Sebelumnya'' adalah ''Aktual'' dari rilis Flash dan oleh karena itu data ''Riwayat'' akan tampak tidak berhubungan. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Maret 2008, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-04-01',
        '15.00',
        'EUR',
        'Low',
        'Final Manufacturing PMI (EUR)',
        NULL,
        NULL,
        NULL,
        'S&P Global (latest release)',
        'Tingkat indeks difusi berdasarkan survey terhadap manajer pembelian dalam industri manufaktur;',
        'Aktual > Perkiraan = Positif',
        'RIlis bulanan, biasanya hari kerja pertama setelah periode bulan berjalan',
        '01-04-2026',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Daftar ''Sebelumnya'' adalah ''Aktual'' dari rilis Flash dan oleh karena itu data ''Riwayat'' akan tampak tidak berhubungan. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Juni 2007, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-04-01',
        '15.00',
        'EUR',
        'Low',
        'Italian Monthly Unemployment Rate',
        '5.1%',
        NULL,
        NULL,
        'Istat (Italian National Institute of Statistic)',
        'Persentase total angkatan kerja yang menganggur dan aktif mencari pekerjaan selama bulan sebelumnya;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 30 hari setelah periode bulan berjalan',
        '01-04-2026',
        'Sumber pertama kali merilis format bulanan pada Desember 2009;',
        0,
        NULL,
        '-'
    ),
    (
        '2026-04-01',
        '15.30',
        'GBP',
        'Low',
        'Final Manufacturing PMI',
        NULL,
        NULL,
        NULL,
        'S&P Global (latest release)',
        'Tingkat indeks difusi berdasarkan survei manajer pembelian di industri manufaktur;',
        '''Actual'' greater than ''Forecast'' is good for currency;',
        'Dirilis setiap bulan, pada hari kerja pertama setelah bulan berakhir;',
        '01-04-2026',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Daftar ''Sebelumnya'' adalah ''Aktual'' dari rilis Flash dan oleh karena itu data ''Riwayat'' akan tampak tidak berhubungan. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada November 2019, merupakan rilis paling awal sehingga cenderung memiliki dampak paling besar;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-04-01',
        '16.00',
        'EUR',
        'Low',
        'Unemployment Rate (EUR)',
        '6.1%',
        NULL,
        NULL,
        'Komisi Statistik Wilayah Euro (Eurostat)',
        'Persentase total angkatan kerja yang menganggur dan aktif mencari pekerjaan selama bulan sebelumnya;',
        '''Aktual'' kurang dari ''Perkiraan'' baik untuk mata uang;',
        'Rilis bulanan, sekitar 30 hari setelah periode bulan berjalan',
        '01-04-2026',
        'Cenderung memiliki dampak yang tidak terlalu besar karena terdapat beberapa indikator sebelumnya yang terkait dengan kondisi ketenagakerjaan zona Euro;',
        0,
        NULL,
        'Meskipun secara umum angka ini dipandang sebagai indikator tertinggal, jumlah pengangguran merupakan sinyal penting mengenai kesehatan perekonomian secara keseluruhan karena belanja konsumen sangat berkorelasi dengan kondisi pasar tenaga kerja;'
    ),
    (
        '2026-04-01',
        '19.15',
        'US',
        'High',
        'ADP Non-Farm Employment Change',
        '63K',
        NULL,
        NULL,
        'Automatic Data Processing, Inc.',
        'Perkiraan perubahan jumlah pekerja pada bulan sebelumnya, tidak termasuk industri pertanian dan pemerintahan;',
        'Aktual > Perkiraan = Positif',
        'Dirilis setiap bulan, biasanya pada hari Rabu pertama setelah bulan berakhir;',
        '01-04-2026',
        'Data ini memberikan gambaran awal mengenai pertumbuhan lapangan kerja, biasanya 2 hari sebelum data ketenagakerjaan yang dirilis pemerintah dirancang untuk ditiru. Sumber mengubah rumus perhitungan seri pada bulan Februari 2007, Desember 2008, dan November 2012, agar lebih selaras dengan data pemerintah;',
        0,
        NULL,
        'Penciptaan lapangan kerja merupakan indikator utama yang penting dalam belanja konsumen, yang menyumbang sebagian besar kegiatan ekonomi secara keseluruhan;'
    ),
    (
        '2026-04-01',
        '19.30',
        'US',
        'High',
        'Core Retail Sales m/m',
        '0.0%',
        NULL,
        NULL,
        'Biro Sensus',
        'Perubahan total nilai penjualan di tingkat eceran, tidak termasuk mobil;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 16 hari setelah bulan berjalan',
        '01-04-2026',
        'Penjualan mobil menyumbang sekitar 20% dari Penjualan Ritel, namun cenderung sangat fluktuatif dan mendistorsi tren yang mendasarinya. Oleh karena itu, data Inti dianggap sebagai ukuran tren belanja yang lebih baik;',
        0,
        NULL,
        'Ini adalah ukuran utama belanja konsumen, yang menyumbang sebagian besar aktivitas perekonomian secara keseluruhan;'
    ),
    (
        '2026-04-01',
        '19.30',
        'US',
        'High',
        'Retail Sales m/m (US)',
        '-0.2%',
        NULL,
        NULL,
        'Biro Sensus',
        'Perubahan nilai total penjualan di tingkat ritel;',
        'Aktual > Perkriaan = Positif',
        'Rilis bulanan, sekitar 14 hari setelah bulan berjalan',
        '01-04-2026',
        'Ini adalah gambaran paling awal dan terluas mengenai data belanja konsumen yang penting;',
        0,
        NULL,
        'Ini adalah ukuran utama belanja konsumen, yang menyumbang sebagian besar aktivitas perekonomian secara keseluruhan;'
    ),
    (
        '2026-04-01',
        '20.05',
        'US',
        'Low',
        'FOMC Member Musalem Speaks',
        NULL,
        NULL,
        NULL,
        'Federal Reserve Bank of St. Louis (latest release)',
        '-',
        'Sikap yang lebih agresif dari yang diharapkan adalah baik untuk mata uang;',
        '-',
        '01-04-2026',
        'Anggota pemilih FOMC 2025;',
        0,
        NULL,
        'Anggota Federal Reserve FOMC memberikan suara tentang penetapan suku bunga acuan negara dan keterlibatan publik mereka sering kali digunakan untuk memberikan petunjuk halus mengenai kebijakan moneter masa depan;'
    ),
    (
        '2026-04-01',
        '20.45',
        'US',
        'Low',
        'Final Manufacturing PMI (US)',
        NULL,
        NULL,
        NULL,
        'S&P Global (latest release)',
        'Tingkat indeks difusi berdasarkan survey terhadap manajer pembelian dalam industri manufaktur;',
        'Aktual > Perkiraan = Positif',
        'RIlis bulanan, biasanya hari kerja pertama setelah periode bulan berjalan',
        '01-04-2026',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. ''Sebelumnya'' yang tercantum adalah ''Aktual'' dari rilis Flash dan oleh karena itu data ''Riwayat'' akan tampak tidak berhubungan. Ada 2 versi laporan ini yang dirilis sekitar seminggu terpisah – Flash dan Final. Rilis Flash adalah yang paling awal dan dengan demikian cenderung memiliki dampak paling besar. Sumber pertama kali dirilis pada Mei 2012;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-04-01',
        '21.00',
        'US',
        'High',
        'ISM Manufacturing PMI',
        '52.4',
        NULL,
        NULL,
        'Institute for Supply Management',
        'Tingkat indeks difusi berdasarkan survey terhadap manajer pembelian dalam industri manufaktur;',
        'Aktual > Perkiraan = Positif',
        'RIlis bulanan, biasanya hari kerja pertama setelah periode bulan berjalan',
        '01-04-2026',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi;',
        0,
        NULL,
        'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;'
    ),
    (
        '2026-04-01',
        '21.00',
        'US',
        'Medium',
        'ISM Manufacturing Prices',
        '70.5',
        NULL,
        NULL,
        'Institute for Supply Management',
        'Tingkat indeks difusi berdasarkan survey terhadap manajer pembelian dalam industri manufaktur;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, hari kerja pertama setelah periode bulan berjalan',
        '01-04-2026',
        'Ini adalah komponen PMI namun dilaporkan secara terpisah sebagai alat pengukur inflasi. Di atas 50,0 menunjukkan kenaikan harga, di bawah menunjukkan penurunan harga;',
        0,
        NULL,
        'Ini adalah indikator utama inflasi konsumen - ketika dunia usaha membayar lebih untuk barang dan jasa, biaya yang lebih tinggi biasanya dibebankan kepada konsumen;'
    ),
    (
        '2026-04-01',
        '21.00',
        'US',
        'Low',
        'Business Inventories m/m',
        '0.1%',
        NULL,
        NULL,
        'Biro Sensus',
        'Perubahan nilai total barang yang disimpan dalam persediaan oleh produsen, pedagang grosir, dan pengecer;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 45 hari setelah bulan berjalan',
        '01-04-2026',
        '-',
        0,
        NULL,
        'Hal ini merupakan sinyal pengeluaran bisnis di masa depan karena perusahaan lebih cenderung membeli barang setelah persediaannya habis;'
    ),
    (
        '2026-04-01',
        '21.30',
        'US',
        'Low',
        'Crude Oil Inventories',
        NULL,
        NULL,
        NULL,
        'Administrasi Informasi Energi',
        'Perubahan jumlah barel minyak mentah yang disimpan oleh perusahaan komersial selama seminggu terakhir;',
        '''Aktual'' kurang dari ''Perkiraan'' baik untuk mata uang;',
        'Rilis mingguan, sekitar 4 hari setelah minggu berjalan',
        '01-04-2026',
        'Meskipun ini merupakan indikator AS, namun hal ini paling berdampak pada sektor energi Kanada yang cukup besar;',
        0,
        NULL,
        'Ini adalah ukuran utama ketidakseimbangan pasokan dan permintaan di pasar, yang dapat menyebabkan perubahan tingkat produksi dan ketidakstabilan harga;'
    ),
    (
        '2026-04-01',
        'All Day',
        'US',
        'Low',
        'Wards Total Vehicle Sales',
        '15.8M',
        NULL,
        NULL,
        'Wards Auto (latest release)',
        'Jumlah tahunan mobil dan truk yang terjual di dalam negeri selama bulan sebelumnya;',
        '''Aktual'' lebih besar dari ''Perkiraan'' bagus untuk mata uang;',
        'Released monthly, about 1 day after the month ends;',
        '01-04-2026',
        'Laporan lengkap hanya tersedia untuk pelanggan Wards Intelligence;',
        0,
        NULL,
        'Hal ini merupakan tanda kepercayaan konsumen – meningkatnya permintaan akan barang-barang tahan lama yang mahal menunjukkan bahwa konsumen yakin akan posisi keuangan mereka di masa depan dan merasa nyaman membelanjakan uangnya;'
    ),
    (
        '2026-04-02',
        '06.50',
        'JPN',
        'Low',
        'Monetary Base y/y',
        '-10.6%',
        NULL,
        NULL,
        'Bank of Japan',
        'Perubahan jumlah total mata uang domestik dalam sirkulasi dan deposito giro yang ada di BOJ;',
        'Aktual > Perkiraan = Positif',
        'RIlis bulanan, biasanya hari kerja kedua setelah periode bulan berjalan',
        '02-04-2026',
        'BOJ mulai menggunakan ini sebagai target operasi utamanya pada bulan April 2013;',
        0,
        NULL,
        'Penyimpangan dari lintasan pertumbuhan basis moneter yang direncanakan menyebabkan bank sentral menyesuaikan kebijakan untuk menghormati mandat inflasi mereka;'
    ),
    (
        '2026-04-02',
        '07.30',
        'AUD',
        'Low',
        'Goods Trade Balance',
        '2.63B',
        NULL,
        NULL,
        'Biro Statistik Australia (rilis terbaru)',
        'Selisih nilai barang impor dan ekspor pada bulan laporan;',
        '''Aktual'' lebih besar dari ''Perkiraan'' bagus untuk mata uang;',
        'Dirilis setiap bulan, sekitar 35 hari setelah bulan berakhir;',
        '02-04-2026',
        'Sumber mengubah rangkaian dari neraca barang dan jasa menjadi neraca barang pada November 2023. Angka positif menunjukkan lebih banyak barang yang diekspor daripada yang diimpor;',
        0,
        NULL,
        'Permintaan ekspor dan permintaan mata uang berhubungan langsung karena orang asing harus membeli mata uang domestik untuk membayar ekspor suatu negara. Permintaan ekspor juga berdampak pada produksi dan harga produsen dalam negeri;'
    ),
    (
        '2026-04-02',
        '10.35',
        'JPN',
        'Low',
        '10-y Bond Auction (JPN)',
        '2.12',
        NULL,
        NULL,
        'Kementerian Keuangan Jepang',
        'Rata-rata imbal hasil (yield) obligasi 10-tahun pemerintah Jepang yang dijual melalui lelang, dan lelang bid-to-cover ratio;',
        'TIdak ada pengaruh yang konsisten, namun tetap ada pengaruh terhadap risiko dan pertumbuhan',
        'Biasanya dilakukan secara bulanan',
        '02-04-2026',
        'Hasil lelang dilaporkan dalam format ''X.XX|X.X'' - angka pertama adalah tingkat bunga rata-rata obligasi yang terjual, dan angka kedua adalah rasio bid-to-cover (jumlah penawaran yang diajukan per penawaran yang diterima);',
        0,
        NULL,
        'Imbal hasil ditentukan oleh investor pasar obligasi, dan oleh karena itu dapat digunakan untuk menguraikan pandangan investor mengenai suku bunga di masa depan. Rasio bid-to-cover mewakili likuiditas dan permintaan pasar obligasi, yang dapat digunakan untuk mengukur kepercayaan investor;'
    ),
    (
        '2026-04-02',
        '13.30',
        'CHF',
        'High',
        'CPI m/m (CHF)',
        '0.6%',
        NULL,
        NULL,
        'Kantor Statistik Federal',
        'Perubahan harga barang dan jasa yang dibeli oleh konsumen;',
        'Aktual > Perkiraan = Bagus untuk mata uang',
        'Rilis bulanan, sekitar 6 hari setelah bulan pengamatan berakhir',
        '02-04-2026',
        'Ini adalah data inflasi utama yang dirilis lebih awal oleh negara manapun, muncul hanya beberapa hari setelah bulan pengamatan berakhir. Dampaknya cenderung signifikan, namun bervariasi dari bulan ke bulan karena tingkat volatilitas dalam kumpulan data;',
        0,
        NULL,
        'Harga-harga konsumen memberikan kontribusi untuk mayoritas inflasi secara keseluruhan. Inflasi penting untuk penilaian mata uang karena kenaikan harga makan mengarahkan bank sentral untuk menaikkan suku bunga guna penahanan inflasi;'
    ),
    (
        '2026-04-02',
        '13.45',
        'EUR',
        'Low',
        'French Gov Budget Balance',
        '-9.7B',
        NULL,
        NULL,
        'Lembaga Keuangan Perancis',
        'Selisih nilai antara pendapatan dan pengeluaran pemerintah pusat yang terkini sejak awal tahun;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 30 hari setelah bulan berakhir',
        '02-04-2026',
        'Angka positif menunjukkan surplus anggaran, angka negatif menunjukkan defisit. Karena format year-to-date, data yang dirilis pada bulan Februari mencakup seluruh anggaran tahun sebelumnya, sedangkan rilis bulan Maret hanya mencakup bulan pertama pada tahun berjalan;',
        0,
        NULL,
        '-'
    ),
    (
        '2026-04-02',
        '16.00',
        'EUR',
        'Low',
        'Italian Retail Sales m/m',
        '0.6%',
        NULL,
        NULL,
        'Istat',
        'Perubahan nilai total penjualan di tingkat ritel;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 35 hari setelah periode bulan berjalan',
        '02-04-2026',
        '-',
        0,
        NULL,
        'Ini adalah ukuran utama belanja konsumen, yang menyumbang sebagian besar aktivitas perekonomian secara keseluruhan;'
    ),
    (
        '2026-04-02',
        '18.30',
        'US',
        'Medium',
        'Challenger Job Cuts y/y',
        '-71.9%',
        NULL,
        NULL,
        'Challenger, Gray & Christmas, Inc.',
        'Perubahan jumlah karyawan PHK yang diumumkan oleh pemberi kerja;',
        'Aktual > Perkiraan = Positif',
        'Dirilis setiap bulan, biasanya pada hari Kamis pertama setelah bulan berakhir;',
        '02-04-2026',
        'Ini merupakan data yang sangat awal, namun secara historis memiliki korelasi jangka pendek yang terbatas dengan kondisi ketenagakerjaan secara keseluruhan;',
        0,
        NULL,
        '-'
    ),
    (
        '2026-04-02',
        '19.30',
        'US',
        'High',
        'Unemployment Claims',
        '205K',
        '211K',
        '210K',
        'Departemen Tenaga Kerja',
        'Jumlah individu yang pertama kali mengajukan asuransi pengangguran selama seminggu terakhir;',
        '''Aktual'' kurang dari ''Perkiraan'' baik untuk mata uang;',
        'Dirilis setiap minggu, biasanya pada hari Kamis pertama setelah minggu berakhir;',
        '02-04-2026',
        'Ini adalah data ekonomi negara yang paling awal. Dampak pasar berfluktuasi dari minggu ke minggu - cenderung lebih fokus pada rilis ketika pedagang perlu mendiagnosis perkembangan terkini, atau ketika angkanya ekstrem;',
        0,
        NULL,
        'Meskipun secara umum angka ini dipandang sebagai indikator tertinggal, jumlah pengangguran merupakan sinyal penting mengenai kesehatan perekonomian secara keseluruhan karena belanja konsumen sangat berkorelasi dengan kondisi pasar tenaga kerja. Pengangguran juga merupakan pertimbangan utama bagi mereka yang mengendalikan kebijakan moneter negara tersebut;'
    ),
    (
        '2026-04-02',
        '19.30',
        'US',
        'Low',
        'Trade Balance (US)',
        '-54.5B',
        NULL,
        NULL,
        'Biro Analisa Ekonomi',
        'Selisih nilai antara barang dan jasa impor dan ekspor selama bulan yang dilaporkan; Angka yang positif menunjukkan bahwa lebih banyak barang dan jasa yang diekspor dibandingkan dengan yang diimpor; Permintaan ekspor dan permintaan mata uang secara la',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 35 hari setelah bulan berjalan',
        '02-04-2026',
        'Porsi barang memiliki dampak yang tidak terlalu besar karena merupakan duplikat data Neraca Perdagangan Barang yang dirilis sekitar 5 hari sebelumnya. Angka positif menunjukkan bahwa lebih banyak barang dan jasa yang diekspor daripada yang diimpor;',
        0,
        NULL,
        'Permintaan ekspor dan permintaan mata uang saling terkait secara langsung karena orang asing harus membeli mata uang domestik untuk membayar ekspor negara tersebut. Permintaan ekspor juga memengaruhi produksi dan harga di produsen dalam negeri;'
    ),
    (
        '2026-04-02',
        '21.30',
        'US',
        'Low',
        'Natural Gas Storage',
        NULL,
        NULL,
        NULL,
        'Administrasi Informasi Energi',
        'Perubahan jumlah kubik feet dari gas alam yang disimpan di gudang bawah tanah selama seminggu sebelumnya;',
        '''Aktual'' kurang dari ''Perkiraan'' baik untuk mata uang;',
        'Rilis mingguan, sekitar 5 hari setelah minggu berjalan',
        '02-04-2026',
        'Persediaan digunakan untuk menjaga stabilitas harga selama kekurangan pasokan dan periode peningkatan permintaan;',
        0,
        NULL,
        '-'
    ),
    (
        '2026-04-02',
        'Tentative',
        'EUR',
        'Low',
        'Spanish 10-y Bond Auction',
        NULL,
        NULL,
        NULL,
        'Sekretariat Keuangan Umum Spanyol',
        'Rata-rata imbal hasil (yield) obligasi 10-tahun pemerintah Spanyol yang dijual melalui lelang, dan lelang bid-to-cover ratio; Hasil Lelang dilaporkan dalam format ''x.xx | x.x'' - nomor pertama adalah tingkat suku bunga rata-rata obligasi yang dijual, dan',
        'Tidak memberikan pengaruh yang konsisten, namun tetap mengimplikasi terhadap risiko dan pertumbuhan.',
        'Variabel, sekitar 8 kali dalam setahun',
        '16-10-2104',
        'Peristiwa ini mencakup obligasi dengan jatuh tempo yang beberapa tahun lebih pendek atau lebih panjang dari 10 tahun, membuat kumpulan data tampak lebih fluktuatif daripada suku bunga 10 tahun yang sebenarnya. Hasil lelang dilaporkan dalam format ''X.XX|X.X'' - angka pertama adalah suku bunga rata-rata obligasi yang dijual, dan angka kedua adalah rasio bid-to-cover (jumlah tawaran yang dibuat per tawaran yang diterima). Sumber tidak memberikan waktu rilis yang pasti - peristiwa ini akan dicantumkan sebagai ''Tentatif'' hingga data dirilis;',
        0,
        NULL,
        'Imbal hasil ditetapkan oleh investor pasar obligasi, dan karenanya dapat digunakan untuk menguraikan prospek investor terhadap suku bunga di masa mendatang. Rasio bid-to-cover menggambarkan likuiditas dan permintaan pasar obligasi, yang dapat digunakan untuk mengukur keyakinan investor;'
    ),
    (
        '2026-04-02',
        'Tentative',
        'EUR',
        'Low',
        'French 10-y Bond Auction',
        NULL,
        NULL,
        NULL,
        'Departemen Keuangan Perancis',
        'Rata-rata imbal hasil (yield) obligasi 10-tahun pemerintah Perancis yang dijual melalui lelang, dan lelang bid-to-cover ratio;',
        'Tidak ada pengaruh yang konsisten, namun tetap mengimplikasi terhadap risiko dan pertumbuhan.',
        'Variabel, sekitar 11 kali dalam setahun',
        '02-04-2026',
        'Hasil lelang dilaporkan dalam format ''X.XX|X.X'' - angka pertama adalah suku bunga rata-rata obligasi yang dijual, dan angka kedua adalah rasio bid-to-cover (jumlah tawaran yang dibuat per tawaran yang diterima). Sumber tidak memberikan waktu rilis yang pasti - peristiwa ini akan dicantumkan sebagai ''Tentatif'' hingga data dirilis;',
        0,
        NULL,
        'Imbal hasil ditetapkan oleh investor pasar obligasi, dan karenanya dapat digunakan untuk menguraikan prospek investor terhadap suku bunga di masa mendatang. Rasio bid-to-cover menggambarkan likuiditas dan permintaan pasar obligasi, yang dapat digunakan untuk mengukur keyakinan investor;'
    ),
    (
        '2026-04-03',
        '12.00',
        'JPN',
        'Low',
        'Leading Indicators',
        NULL,
        NULL,
        NULL,
        'Kantor Kabinet',
        'Perubahan pada level indeks gabungan (komposite) berdasarkan pada 11 indikator ekonomi;',
        'Aktual > Perkiraan = Positif (Kecenderungan)',
        'Rilis bulanan, sekitar 35 hari setelah bulan berakhir',
        '03-04-2026',
        'Indeks ini dirancang untuk memprediksi arah ekonomi, tetapi cenderung memiliki dampak yang tidak terlalu besar karena sebagian besar indikator yang digunakan dalam perhitungan telah dirilis sebelumnya. Ada versi revisi dari indikator ini yang dirilis sekitar 20 hari kemudian, tetapi tidak disertakan karena kurang signifikan. Sumber mengubah seri dari indeks difusi menjadi indeks komposit mulai Juni 2008 dan mengubah rumus perhitungan seri mulai Juli 2023;',
        0,
        NULL,
        '-'
    ),
    (
        '2026-04-03',
        '13.45',
        'EUR',
        'Low',
        'French Industrial Production m/m',
        '0.5%',
        NULL,
        NULL,
        'INSEE (National Institute of Statistics and Economic Studies)',
        'Perubahan nilai total inflasi yang disesuaikan dengan output yang dihasilkan oleh pabrikan, pertambangan, dan sektor utilitas;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, sekitar 40 hari setelah bulan berakhir',
        '03-04-2026',
        '-',
        0,
        NULL,
        'Ini adalah indikator utama kesehatan ekonomi - produksi bereaksi cepat terhadap naik turunnya siklus bisnis dan berkorelasi dengan kondisi konsumen seperti tingkat pekerjaan dan pendapatan;'
    ),
    (
        '2026-04-03',
        '19.30',
        'US',
        'High',
        'Average Hourly Earnings m/m',
        '0.4%',
        NULL,
        NULL,
        'Bureau of Labor Statistics',
        'Perubahan harga yang dibayar bisnis untuk tenaga kerja, tidak termasuk industri pertanian;',
        '''Aktual'' lebih besar dari ''Prakiraan'' bagus untuk mata uang;',
        'Rilis bulanan, biasanya pada hari Jumat pertama setelah bulan berakhir;',
        '03-04-2026',
        'Ini adalah data paling awal terkait inflasi tenaga kerja. Sumber mengubah rumus perhitungan seri pada Feb 2010;',
        0,
        NULL,
        'Ini adalah indikator utama inflasi konsumen - ketika bisnis membayar lebih untuk tenaga kerja, biaya yang lebih tinggi biasanya diteruskan ke konsumen;'
    ),
    (
        '2026-04-03',
        '19.30',
        'US',
        'High',
        'Non-Farm Employment Change',
        '-92K',
        NULL,
        NULL,
        'Biro Statistik Tenaga Kerja',
        'Perubahan jumlah orang yang dipekerjakan selama bulan sebelumnya, tidak termasuk pada industri pertanian;',
        'Aktual > Perkiraan = Positif',
        'Rilis bulanan, biasanya di Jumat pertama setelah bulan berakhir',
        '03-04-2026',
        'Ini adalah data ekonomi penting yang dirilis segera setelah bulan ini berakhir. Kombinasi antara tingkat kepentingan dan tingkat awal menghasilkan dampak pasar yang besar;',
        0,
        NULL,
        'Penciptaan lapangan kerja merupakan indikator utama yang penting dalam belanja konsumen, yang menyumbang sebagian besar kegiatan ekonomi secara keseluruhan;'
    ),
    (
        '2026-04-03',
        '19.30',
        'US',
        'High',
        'Unemployment Rate (US)',
        '4.4%',
        NULL,
        NULL,
        'Biro Statistik Tenaga Kerja',
        'Persentase total angkatan kerja yang menganggur dan aktif mencari pekerjaan selama bulan sebelumnya;',
        'Aktual > Perkiraan = Negatif',
        'Rilis bulanan, biasanya di Jumat pertama setelah bulan berjalan',
        '03-04-2026',
        '-',
        0,
        NULL,
        'Meskipun secara umum angka ini dipandang sebagai indikator tertinggal, jumlah pengangguran merupakan sinyal penting mengenai kesehatan perekonomian secara keseluruhan karena belanja konsumen sangat berkorelasi dengan kondisi pasar tenaga kerja. Pengangguran juga merupakan pertimbangan utama bagi mereka yang mengendalikan kebijakan moneter negara tersebut;'
    ),
    (
        '2026-04-03',
        '20.45',
        'US',
        'Medium',
        'Final Services PMI (US)',
        NULL,
        NULL,
        NULL,
        'S&P Global (latest release)',
        'Tingkat indeks difusi berdasarkan manajer pembelian yang disurvei dalam industri jasa;',
        '''Aktual'' lebih besar dari ''Prakiraan'' bagus untuk mata uang;',
        'Rilis bulanan, biasanya hari kerja ketiga setelah bulan pengamatan berakhir.',
        '03-04-2026',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. ''Sebelumnya'' yang tercantum adalah ''Aktual'' dari rilis Flash dan oleh karena itu data ''Riwayat'' akan tampak tidak berhubungan. Ada 2 versi laporan ini yang dirilis sekitar seminggu terpisah ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Flash dan Final. Rilis Flash adalah yang paling awal dan dengan demikian cenderung memiliki dampak paling besar. Sumber pertama kali dirilis pada Desember 2013;',
        0,
        NULL,
        'Ini adalah indikator utama kesehatan ekonomi - bisnis bereaksi cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap ekonomi;'
    ),
    (
        '2026-04-03',
        '21.00',
        'US',
        'High',
        'ISM Services PMI',
        '56.1',
        NULL,
        NULL,
        'Institute for Supply Management (latest release)',
        'Tingkat indeks difusi berdasarkan manajer pembelian yang disurvei, tidak termasuk industri manufaktur;',
        '''Aktual'' lebih besar dari ''Prakiraan'' bagus untuk mata uang;',
        'Dirilis setiap bulan, pada hari kerja ketiga setelah bulan berakhir;',
        '03-04-2026',
        'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Sumber mengubah seri dari yang tidak disesuaikan menjadi disesuaikan secara musiman per Januari 2001. Sumber mengubah rumus perhitungan seri per Februari 2008;',
        0,
        NULL,
        'Ini adalah indikator utama kesehatan ekonomi - bisnis bereaksi cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap ekonomi;'
    ),
    (
        '2026-04-03',
        'All Day',
        'EUR',
        'Low',
        'German Bank Holiday',
        NULL,
        NULL,
        NULL,
        '-',
        '-',
        'Low liquidity and irregular volatility;',
        '-',
        '03-04-2026',
        'Most Forex brokers remain open for every holiday except Christmas and New Year''s Day. Stock markets and banks have slightly different holiday schedules;',
        1,
        'Most Forex brokers remain open for every holiday except Christmas and New Year''s Day. Stock markets and banks have slightly different holiday schedules;',
        'Banks facilitate the majority of foreign exchange volume. When they are closed the market is less liquid and speculators become a more dominant market influence. This can lead to both abnormally low and abnormally high volatility;'
    ),
    (
        '2026-04-03',
        'All Day',
        'GBP',
        'Low',
        'Bank Holiday',
        NULL,
        NULL,
        NULL,
        '-',
        'Bank Holiday',
        'Likuiditas rendah dan volatilitas tidak teratur;',
        '-',
        '03-04-2026',
        'Sebagian besar broker forex tetap buka untuk setiap hari libur kecuali Natal dan Tahun Baru. Pasar saham dan perbankan sedikit mempunyai perbedaan jadual hari libur nasional.',
        1,
        'Sebagian besar broker forex tetap buka untuk setiap hari libur kecuali Natal dan Tahun Baru. Pasar saham dan perbankan sedikit mempunyai perbedaan jadual hari libur nasional.',
        'Bank memfasilitasi sebagian besar volume valuta asing. Ketika bank tutup, pasar menjadi kurang likuid dan spekulan menjadi pengaruh pasar yang lebih dominan. Hal ini dapat menyebabkan volatilitas yang sangat rendah dan sangat tinggi;'
    );

INSERT INTO
    economic_calendar_categories (
        country,
        impact,
        figures,
        sources,
        measures,
        usual_effect,
        frequency,
        next_released,
        notes,
        isBankHoliday,
        bankHolidayNote,
        why_trader_care,
        created_at,
        updated_at
    )
SELECT t.country, t.impact, t.figures, t.sources, t.measures, t.usual_effect, t.frequency, t.next_released, t.notes, t.isBankHoliday, t.bankHolidayNote, t.why_trader_care, NOW(), NOW()
FROM tmp_economic_calendar_import t
WHERE
    NOT EXISTS (
        SELECT 1
        FROM economic_calendar_categories c
        WHERE
            TRIM(LOWER(c.country)) COLLATE utf8mb4_unicode_ci = TRIM(LOWER(t.country)) COLLATE utf8mb4_unicode_ci
            AND TRIM(LOWER(c.figures)) COLLATE utf8mb4_unicode_ci = TRIM(LOWER(t.figures)) COLLATE utf8mb4_unicode_ci
    )
GROUP BY
    t.country,
    t.impact,
    t.figures,
    t.sources,
    t.measures,
    t.usual_effect,
    t.frequency,
    t.next_released,
    t.notes,
    t.isBankHoliday,
    t.bankHolidayNote,
    t.why_trader_care;

INSERT INTO
    economic_calendars (
        economic_calendar_category_id,
        date,
        time,
        country,
        impact,
        figures,
        previous,
        forecast,
        actual,
        sources,
        measures,
        usual_effect,
        frequency,
        next_released,
        notes,
        isBankHoliday,
        bankHolidayNote,
        why_trader_care,
        created_at,
        updated_at
    )
SELECT
    c.id,
    t.date_value,
    t.time_value,
    t.country,
    t.impact,
    t.figures,
    t.previous_value,
    t.forecast_value,
    t.actual_value,
    t.sources,
    t.measures,
    t.usual_effect,
    t.frequency,
    t.next_released,
    t.notes,
    t.isBankHoliday,
    t.bankHolidayNote,
    t.why_trader_care,
    NOW(),
    NOW()
FROM
    tmp_economic_calendar_import t
    JOIN economic_calendar_categories c ON TRIM(LOWER(c.country)) COLLATE utf8mb4_unicode_ci = TRIM(LOWER(t.country)) COLLATE utf8mb4_unicode_ci
    AND TRIM(LOWER(c.figures)) COLLATE utf8mb4_unicode_ci = TRIM(LOWER(t.figures)) COLLATE utf8mb4_unicode_ci
WHERE
    NOT EXISTS (
        SELECT 1
        FROM economic_calendars ec
        WHERE
            ec.date = t.date_value
            AND TRIM(LOWER(ec.time)) COLLATE utf8mb4_unicode_ci = TRIM(LOWER(t.time_value)) COLLATE utf8mb4_unicode_ci
            AND TRIM(LOWER(ec.country)) COLLATE utf8mb4_unicode_ci = TRIM(LOWER(t.country)) COLLATE utf8mb4_unicode_ci
            AND TRIM(LOWER(ec.figures)) COLLATE utf8mb4_unicode_ci = TRIM(LOWER(t.figures)) COLLATE utf8mb4_unicode_ci
    );

COMMIT;