-- Plain SQL import generated from the 53 current payload items provided by the user.
-- This file does not use JSON functions.

START TRANSACTION;

DROP TEMPORARY TABLE IF EXISTS tmp_economic_payload_seed;
CREATE TEMPORARY TABLE tmp_economic_payload_seed (
    country VARCHAR(50) NOT NULL,
    impact ENUM('Low', 'Medium', 'High') NOT NULL,
    figures VARCHAR(255) NOT NULL,
    sources TEXT NOT NULL,
    measures LONGTEXT NULL,
    usual_effect LONGTEXT NULL,
    frequency LONGTEXT NULL,
    next_released LONGTEXT NULL,
    notes LONGTEXT NULL,
    why_trader_care LONGTEXT NULL,
    detail_date DATE NOT NULL,
    detail_time VARCHAR(10) NULL,
    previous_value VARCHAR(100) NULL,
    forecast_value VARCHAR(100) NULL,
    actual_value VARCHAR(100) NULL,
    isBankHoliday TINYINT(1) NOT NULL DEFAULT 0,
    bankHolidayNote TEXT NULL
);

INSERT INTO tmp_economic_payload_seed (
    country,
    impact,
    figures,
    sources,
    measures,
    usual_effect,
    frequency,
    next_released,
    notes,
    why_trader_care,
    detail_date,
    detail_time,
    previous_value,
    forecast_value,
    actual_value,
    isBankHoliday,
    bankHolidayNote
) VALUES
(
    'US',
    'Low',
    'Construction Spending m/m',
    'Biro Sensus',
    'Perubahan total jumlah pengeluaran dari pengembang rumah yang dibelanjakan untuk proyek-proyek konstruksi.',
    'Aktual > Perkiraan = Positif',
    'Rilis bulanan, sekitar 30 hari setelah bulan berjalan',
    'No Information',
    NULL,
    NULL,
    '2026-03-23',
    '21:00',
    '0.8%',
    '0.1%',
    '-0.3%',
    0,
    NULL
),
(
    'EUR',
    'Low',
    'Consumer Confidence',
    'Komisi Statistik Wilayah Euro (Eurostat)',
    'Tingkat indeks difusi berdasarkan konsumen yang disurvei;',
    'Aktual > Perkiraan = Positif',
    'Rilis bulanan, sekitar 22 hari setelah bulan berjalan',
    'No Information',
    'Angka di atas 0 menunjukkan optimisme, sedangkan angka di bawah 0 menunjukkan pesimisme. Laporan ini diterbitkan dalam dua versi dengan selisih waktu sekitar satu minggu – Flash dan Final. Versi Flash, yang pertama kali dilaporkan oleh sumber tersebut pada Januari 2010, adalah yang paling awal dan karenanya cenderung memiliki dampak terbesar. Versi Final tidak dilaporkan karena kurang signifikan;',
    'Kepercayaan finansial merupakan indikator utama belanja konsumen, yang menyumbang sebagian besar aktivitas perekonomian secara keseluruhan;',
    '2026-03-23',
    '22:00',
    '-12',
    '-15',
    '-16',
    0,
    NULL
),
(
    'AUD',
    'Low',
    'Flash Manufacturing PMI',
    'Markit (rilis terbaru)',
    'Tingkat indeks difusi berdasarkan manajer pembelian yang disurvei di industri manufaktur;',
    '''Sebenarnya'' lebih besar dari ''Prakiraan'' baik untuk mata uang;',
    'Dirilis setiap bulan, sekitar 3 minggu ke bulan saat ini;',
    'No Information',
    'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu - Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada Oktober 2018, merupakan rilis paling awal sehingga cenderung memiliki dampak paling besar. Final tidak disertakan karena kurang penting;',
    'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;',
    '2026-03-24',
    '05:00',
    '51.0',
    NULL,
    '50.1',
    0,
    NULL
),
(
    'AUD',
    'Low',
    'Flash Services PMI',
    'S&P Global',
    'Tingkat indeks difusi berdasarkan survei manajer pembelian di industri jasa;',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Dirilis setiap bulan, sekitar 3 minggu setelah bulan berjalan;',
    'No Information',
    'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu - Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada Oktober 2018, merupakan rilis paling awal sehingga cenderung memiliki dampak paling besar. Final tidak disertakan karena kurang penting;',
    'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;',
    '2026-03-24',
    '05:00',
    '52.8',
    NULL,
    '46.6',
    0,
    NULL
),
(
    'JPN',
    'Low',
    'National Core CPI y/y',
    'Biro Statistik',
    'Perubahan harga barang dan jasa yang dibeli konsumen, tidak termasuk pangan segar;',
    'Aktual > Perkiraan = Positif',
    'RIlis bulanan, biasanya pada Jumat terakhir dari periode bulan berjalan',
    'No Information',
    NULL,
    NULL,
    '2026-03-24',
    '06:30',
    '2.0%',
    '1.7%',
    '1.6%',
    0,
    NULL
),
(
    'JPN',
    'Low',
    'Flash Manufacturing PMI (JPN)',
    'S&P Global',
    'Tingkat indeks difusi berdasarkan manajer pembelian yang disurvei dalam industri manufaktur; Survei dari sekitar 400 manajer pembelian yang dimintai respon untuk menilai tingkat relatif dari kondisi bisnis termasuk ketenagakerjaan, produksi, pesanan bar',
    'Aktual > Perkiraan = Cenderung positif untuk mata uang (USD)',
    'Dirilis bulanan, sekitar 3 minggu dari bulan berjalan',
    'No Information',
    'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Mei 2014, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
    'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;',
    '2026-03-24',
    '07:30',
    '53.0',
    '52.9',
    NULL,
    0,
    NULL
),
(
    'EUR',
    'Medium',
    'French Flash Manufacturing PMI',
    'S&P Global',
    'Tingkat indeks difusi berdasarkan survei manajer pembelian di industri manufaktur;',
    '''Aktual'' lebih besar dari ''Perkiraan'' bagus untuk mata uang;',
    'Dirilis setiap bulan, sekitar 3 minggu setelah bulan berjalan;',
    'No Information',
    'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Maret 2008, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
    'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;',
    '2026-03-24',
    '15:15',
    '50.1',
    '49.4',
    '50.2',
    0,
    NULL
),
(
    'EUR',
    'High',
    'German Flash Manufacturing PMI',
    'S&P Global',
    'Tingkat indeks difusi berdasarkan survei manajer pembelian di industri manufaktur;',
    'Aktual > Perkiraan = Positif',
    'Rilis bulanan, sekitar 3 minggu dalam bulan berjalan',
    'No Information',
    'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Maret 2008, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
    'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;',
    '2026-03-24',
    '15:30',
    '50.9',
    '49.6',
    '51.7',
    0,
    NULL
),
(
    'EUR',
    'High',
    'German Flash Services PMI',
    'S&P Global',
    'Tingkat indeks difusi berdasarkan survei manajer pembelian di industri jasa;',
    'Aktual > Perkiraan = Positif',
    'Rilis bulanan, sekitar 3 minggu dalam bulan berjalan',
    NULL,
    'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Maret 2008, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
    'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;',
    '2026-03-24',
    '15:30',
    '53.5',
    '52.5',
    '51.2',
    0,
    NULL
),
(
    'EUR',
    'Low',
    'Flash Manufacturing PMI (EUR)',
    'S&P Global',
    'Tingkat indeks difusi berdasarkan survei manajer pembelian di industri manufaktur;',
    'Aktual > Perkiraan = Positif',
    'Rilis bulanan, sekitar 3 minggu dalam bulan berjalan',
    'No Information',
    'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Juni 2007, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
    'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;',
    '2026-03-24',
    '16:00',
    '50.8',
    '49.5',
    '51.4',
    0,
    NULL
),
(
    'EUR',
    'Low',
    'Flash Services PMI',
    'S&P Global (latest release)',
    'Level of a diffusion index based on surveyed purchasing managers in the services industry;',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Released monthly, around 3 weeks into the current month;',
    NULL,
    'Above 50.0 indicates industry expansion, below indicates contraction. There are 2 versions of this report released about a week apart ??? Flash and Final. The Flash release, which the source first reported in Jun 2007, is the earliest and thus tends to have the most impact;',
    NULL,
    '2026-03-24',
    '16:00',
    '51.9',
    '51.1',
    '50.1',
    0,
    NULL
),
(
    'GBP',
    'Medium',
    'Flash Services PMI',
    'S&P Global',
    'Tingkat indeks difusi berdasarkan survei manajer pembelian di industri jasa;',
    'Aktual > Perkiraan = Positif',
    'Rilis bulanan, sekitar 3 minggu dalam bulan berjalan',
    'No Information',
    'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu - Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Juni 2007, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
    'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;',
    '2026-03-24',
    '16:30',
    '53.9',
    '52.8',
    '51.2',
    0,
    NULL
),
(
    'GBP',
    'High',
    'Flash Manufacturing PMI',
    'S&P Global (latest release)',
    'Level of a diffusion index based on surveyed purchasing managers in the manufacturing industry;',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Released monthly, around 3 weeks into the current month;',
    NULL,
    'Above 50.0 indicates industry expansion, below indicates contraction. There are 2 versions of this report released about a week apart ??? Flash and Final. The Flash release, which the source first reported in Nov 2019, is the earliest and thus tends to have the most impact;',
    NULL,
    '2026-03-24',
    '16:30',
    '51.7',
    '50.0',
    '51.4',
    0,
    NULL
),
(
    'GBP',
    'High',
    'Flash Services PMI (GBP)',
    'Markit (latest release)',
    'Tingkat indeks difusi berdasarkan manajer pembelian yang disurvei di industri jasa;',
    '''Aktual'' lebih besar dari ''Perkiraan'' bagus untuk mata uang;',
    'Dirilis setiap bulan, sekitar 3 minggu ke bulan saat ini;',
    'No Information',
    'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada November 2019, merupakan rilis paling awal sehingga cenderung memiliki dampak paling besar;',
    'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;',
    '2026-03-24',
    '16:30',
    '53.9',
    '52.8',
    '51.2',
    0,
    NULL
),
(
    'GBP',
    'Low',
    'CBI Realized Sales',
    'Confederation of British Industry (latest release)',
    'Level of a diffusion index based on surveyed retailers and wholesalers;',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Released monthly, around the end of the current month;',
    NULL,
    'Above 0 indicates higher sales volume, below indicates lower. Source changed series calculation formula as of July 2009;',
    NULL,
    '2026-03-24',
    '18:00',
    '-43',
    '-43',
    '-52',
    0,
    NULL
),
(
    'US',
    'Low',
    'ADP Weekly Employment Change',
    'Automatic Data Processing, Inc. (latest release)',
    'Estimated average weekly change in the number of employed people during the previous 4 weeks, excluding the farming industry and government;',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Released weekly, on the first Tuesday about 2 weeks after the rolling four-week period ends;',
    'No Information',
    'This is high-frequency private-sector employment data based on a rolling four-week average, and tends to be more volatile than the monthly ADP Employment Report. The release is skipped in any week that overlaps with publication of the monthly ADP Employment Report. Source first released in Oct 2025;',
    'Job creation is an important leading indicator of consumer spending, which accounts for a majority of overall economic activity;',
    '2026-03-24',
    '19:15',
    '9.0K',
    NULL,
    '10.0K',
    0,
    NULL
),
(
    'US',
    'Low',
    'Revised Nonfarm Productivity q/q',
    'Bureau of Labor Statistics (latest release)',
    'Annualized change in labor efficiency when producing goods and services, excluding the farming industry;',
    '''Actual'' less than ''Forecast'' is good for currency;',
    'Released quarterly, about 65 days after the quarter ends;',
    'Mar 5, 2026',
    'While this is q/q data, it''s reported in an annualized format (quarterly change x4). The ''Previous'' listed is the ''Actual'' from the Preliminary release and therefore the ''History'' data will appear unconnected. There are 2 versions of this report released a month apart ??? Preliminary and Revised. The Preliminary release is the earliest and thus tends to have the most impact;',
    NULL,
    '2026-03-24',
    '19:30',
    '2.8%',
    '2.4%',
    '1.8%',
    0,
    NULL
),
(
    'US',
    'Low',
    'Revised Unit Labor Costs q/q',
    'Bureau of Labor Statistics (latest release)',
    'Annualized change in the price businesses pay for labor, excluding the farming industry;',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Released quarterly, about 65 days after the quarter ends;',
    'Mar 5, 2026',
    'While this is q/q data, it''s reported in an annualized format (quarterly change x4). The ''Previous'' listed is the ''Actual'' from the Preliminary release and therefore the ''History'' data will appear unconnected. There are 2 versions of this report released a month apart ??? Preliminary and Revised. The Preliminary release is the earliest and thus tends to have the most impact;',
    NULL,
    '2026-03-24',
    '19:30',
    '2.8%',
    '3.4%',
    '4.4%',
    0,
    NULL
),
(
    'US',
    'High',
    'Flash Manufacturing PMI (US)',
    'S&P Global',
    'Tingkat indeks difusi berdasarkan survei terhadap manajer pembelian dalam industri manufaktur;',
    'Aktual > Perkiraan = Positif',
    'Rilis bulanan, sekitar 3 minggu dalam bulan berjalan',
    'No Information',
    'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu - Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan Mei 2012, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
    'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;',
    '2026-03-24',
    '20:45',
    '51.6',
    '51.5',
    '52.4',
    0,
    NULL
),
(
    'US',
    'High',
    'Flash Services PMI (US)',
    'S&P Global',
    'Tingkat indeks difusi berdasarkan survei terhadap manajer pembelian dalam industri jasa;',
    'Aktual > Perkiraan = Positif',
    'Rilis bulanan, sekitar 3 minggu dalam bulan berjalan',
    'No Information',
    'Di atas 50,0 menunjukkan ekspansi industri, di bawah menunjukkan kontraksi. Ada 2 versi laporan ini yang dirilis dengan selang waktu sekitar satu minggu - Flash dan Final. Rilisan Flash, yang pertama kali dilaporkan oleh sumber tersebut pada bulan November 2013, adalah yang paling awal dan cenderung memiliki dampak paling besar;',
    'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan manajer pembelian mereka mungkin memiliki wawasan terkini dan relevan mengenai pandangan perusahaan terhadap perekonomian;',
    '2026-03-24',
    '20:45',
    '51.7',
    '52.0',
    '51.1',
    0,
    NULL
),
(
    'US',
    'Medium',
    'Richmond Manufacturing Index',
    'Federal Reserve Bank of Richmond (latest release)',
    'Level of a composite index based on surveyed manufacturers in Richmond;',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Released monthly, on the fourth Tuesday of the current month;',
    NULL,
    'Above 0 indicates improving conditions, below indicates worsening conditions. Tends to have a muted impact because there are earlier regional indicators related to manufacturing conditions;',
    NULL,
    '2026-03-24',
    '21:00',
    '-10',
    '-5',
    '0',
    0,
    NULL
),
(
    'JPN',
    'Low',
    'Monetary Policy Meeting Minutes (JPN)',
    'Bank of Japan',
    'Ini adalah catatan rinci dari pertemuan Kebijakan Dewan Bank of Japan, memberikan wawasan mendalam terhadap kondisi ekonomi yang bisa mempengaruhi keputusan mereka untuk menetapkan tingkat suku bunga.',
    'Lebih hawkish dari pada perkiraan biasanya akan direspon negatif oleh pasar, tapi bila lebih dovish dibandingkan perkiraan biasanya akan direspon positif.',
    'Variabel, sekitar 14 kali dalam setahun, 30-50 hari setelah pengumuman suku bunga antar bank (Overnight Call Rate)',
    'No Information',
    NULL,
    NULL,
    '2026-03-25',
    '06:50',
    NULL,
    NULL,
    NULL,
    0,
    NULL
),
(
    'AUD',
    'High',
    'CPI y/y (AUD)',
    'Australian Bureau of Statistics',
    'Perubahan harga barang dan jasa yang dibeli konsumen;',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Dirilis setiap bulan, sekitar 25 hari setelah bulan berakhir;',
    'No Information',
    'Angka ini merupakan salah satu dari sedikit angka penyesuaian non-musiman yang dilaporkan dalam kalender. Sumber pertama kali dirilis pada Oktober 2022;',
    'Harga konsumen menyumbang sebagian besar inflasi secara keseluruhan. Inflasi penting dalam penilaian mata uang karena kenaikan harga menyebabkan bank sentral menaikkan suku bunga untuk pengendalian inflasi;',
    '2026-03-25',
    '07:30',
    '3.8%',
    '3.8%',
    '3.7%',
    0,
    NULL
),
(
    'AUD',
    'High',
    'CPI m/m',
    'Australian Bureau of Statistics (latest release)',
    NULL,
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Released monthly, about 25 days after the month ends;',
    'No Information',
    'Ini rilis inflasi yang paling penting, karena keluar paling cepat dibanding indikator inflasi lain dan cakupannya luas (ngukur banyak komponen harga di ekonomi, bukan cuma satu sektor). Angka ini termasuk sedikit data yang dilaporkan dalam bentuk non-seasonally adjusted (NSA) sehingga bisa terlihat lebih naik-turun secara alami. Sumber data mengubah frekuensi rilis dari triwulan menjadi bulanan, jadi data jadi lebih sering keluar.',
    'Data inflasi konsumen penting karena mewakili porsi besar inflasi. Kenaikan inflasi biasanya mendorong bank sentral menaikkan suku bunga untuk menahan laju harga, yang dapat memperkuat mata uang lewat kenaikan imbal hasil aset domestik.',
    '2026-03-25',
    '07:30',
    '0.4%',
    '0.1%',
    '0.0%',
    0,
    NULL
),
(
    'AUD',
    'High',
    'Trimmed Mean CPI m/m',
    'Reserve Bank of Australia (latest release)',
    'Perubahan harga barang dan jasa yang dibeli oleh konsumen, tidak termasuk 30% barang yang paling fluktuatif;',
    'Angka aktual yang lebih besar dari angka prakiraan baik untuk mata uang;',
    'Dirilis setiap bulan, sekitar 25 hari setelah bulan berakhir;',
    'No Information',
    'Data ini mewakili tren inflasi yang mendasari melalui pembobotan komponen dan pengecualian anomali. Ini adalah salah satu dari sedikit angka yang tidak disesuaikan secara musiman yang dilaporkan pada kalender. Sumber mengubah frekuensi rilis dari triwulanan menjadi bulanan dan mengubah rumus perhitungan seri mulai Januari 2026;',
    'Harga konsumen menyumbang sebagian besar inflasi secara keseluruhan. Inflasi penting bagi valuasi mata uang karena kenaikan harga menyebabkan bank sentral menaikkan suku bunga sebagai bentuk penghormatan terhadap mandat pengendalian inflasi mereka;',
    '2026-03-25',
    '07:30',
    '0.3%',
    '0.3%',
    '0.2%',
    0,
    NULL
),
(
    'GBP',
    'High',
    'CPI y/y (GBP)',
    'Kantor Statistik Federal',
    'Perubahan harga barang dan jasa yang dibeli oleh konsumen;',
    'Actual > Forecast = Bagus untuk mata uang',
    'Rilis bulanan, sekitar 16 hari setelah bulan berakhir',
    'No Information',
    'Data ini dianggap sebagai data inflasi paling penting di Inggris karena digunakan sebagai target inflasi bank sentral (BOE);',
    'Harga konsumen menyumbang sebagian besar inflasi secara keseluruhan. Inflasi penting dalam penilaian mata uang karena kenaikan harga menyebabkan bank sentral menaikkan suku bunga untuk menghormati mandat pengendalian inflasi;',
    '2026-03-25',
    '14:00',
    '3.0%',
    '3.0%',
    '3.0%',
    0,
    NULL
),
(
    'GBP',
    'Low',
    'Core CPI y/y',
    'Office for National Statistics (latest release)',
    'Change in the price of goods and services purchased by consumers, excluding the volatile food, energy, alcohol, and tobacco items;',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Released monthly, about 16 days after the month ends;',
    NULL,
    'The Core data has a mild impact relative to other countries because overall CPI is the central bank''s mandated inflation target;',
    NULL,
    '2026-03-25',
    '14:00',
    '3.1%',
    '3.1%',
    '3.2%',
    0,
    NULL
),
(
    'GBP',
    'Low',
    'PPI Input m/m',
    'Office for National Statistics (latest release)',
    'Change in the price of goods and raw materials purchased by manufacturers;',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Released monthly, about 15 days after the month ends;',
    NULL,
    NULL,
    NULL,
    '2026-03-25',
    '14:00',
    '0.4%',
    '0.5%',
    '0.8%',
    0,
    NULL
),
(
    'GBP',
    'Low',
    'PPI Output m/m',
    'Office for National Statistics (latest release)',
    'Change in the price of goods sold by manufacturers',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Released monthly, about 15 days after the month ends;',
    NULL,
    'Only includes goods produced domestically;',
    NULL,
    '2026-03-25',
    '14:00',
    '0.0%',
    '0.3%',
    '-0.5%',
    0,
    NULL
),
(
    'GBP',
    'Low',
    'RPI y/y',
    'Office for National Statistics (latest release)',
    'Change in the price of goods and services purchased by consumers for the purpose of consumption;',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Released monthly, about 16 days after the month ends;',
    NULL,
    'RPI differs from CPI in that it only measures goods and services bought for the purpose of consumption by the vast majority of households, and it includes housing costs which are excluded from CPI;',
    NULL,
    '2026-03-25',
    '14:00',
    '3.8%',
    '3.7%',
    '3.6%',
    0,
    NULL
),
(
    'CHF',
    'Low',
    'UBS Economic Expectations',
    'UBS AG (latest release)',
    'Level of a diffusion index based on surveyed institutional investors and analysts;',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Released monthly, around about 26 days after the month ends;',
    NULL,
    'Above 0.0 indicates optimism, below indicates pessimism;',
    NULL,
    '2026-03-25',
    '16:00',
    '9.8',
    NULL,
    '-35.0',
    0,
    NULL
),
(
    'EUR',
    'Medium',
    'German Ifo Business Climate',
    'Ifo Institute for Economic Research',
    'Tingkat indeks komposit berdasarkan survei produsen, pembangun, pedagang besar, jasa, dan pengecer;',
    'Aktual > Perkiraan = Positif',
    'Rilis bulanan, sekitar 3 minggu dalam bulan berjalan',
    'No Information',
    'Survei ini sangat dihargai karena ukuran sampelnya yang besar dan korelasi historisnya dengan kondisi perekonomian Jerman dan zona euro yang lebih luas. Hal ini cenderung menciptakan dampak pasar yang besar dan kuat setelah dirilis. Sumber mengubah rangkaian dari tahun dasar 2000 menjadi tahun dasar 2005, mulai Mei 2011, dan mengubah rangkaian untuk menyertakan layanan, mulai April 2018;',
    'Hal ini merupakan indikator utama kesehatan perekonomian - dunia usaha bereaksi dengan cepat terhadap kondisi pasar, dan perubahan sentimen dapat menjadi sinyal awal mengenai aktivitas perekonomian di masa depan seperti pembelanjaan, perekrutan tenaga kerja, dan investasi;',
    '2026-03-25',
    '16:00',
    '88.6',
    '86.3',
    '86.4',
    0,
    NULL
),
(
    'GBP',
    'Low',
    'HPI y/y',
    'UK Government (latest release)',
    'Change in the selling price of homes;',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Released monthly, about 45 days after the month ends;',
    NULL,
    'Source first released in Jun 2016;',
    NULL,
    '2026-03-25',
    '16:30',
    '1.9%',
    '1.7%',
    '1.3%',
    0,
    NULL
),
(
    'US',
    'Low',
    'Current Account (U.S)',
    'Biro Analisa Ekonomi',
    'Selisih nilai antara impor dan ekspor dari barang, jasa, arus pendapatan, dan transfer unilateral selama kuartal sebelumnya; Porsi dari barang dan jasa tidak terlalu berdampak karena itu merupakan duplikasi dari data Trade Balance bulanan; Ini secara',
    'Aktual > Perkiraan = Positif',
    'Rilis kuartalan, sekitar 75 hari setelah kuartal berakhir',
    'No Information',
    NULL,
    NULL,
    '2026-03-25',
    '19:30',
    '-239B',
    '-211B',
    '-191B',
    0,
    NULL
),
(
    'US',
    'Low',
    'Import Prices m/m (US)',
    'Biro Statistik Tenaga Kerja',
    'Perubahan harga barang dan jasa impor yang dibeli di dalam negeri;',
    'Aktual > Perkiraan = Positif',
    'Rilis bulanan, sekitar 13 hari setelah bulan berjalan',
    NULL,
    'Ini merupakan data inflasi paling awal yang dirilis pemerintah;',
    NULL,
    '2026-03-25',
    '19:30',
    '0.6%',
    '0.6%',
    '1.3%',
    0,
    NULL
),
(
    'CHN',
    'Low',
    'CB Leading Index m/m',
    'The Conference Board Inc. (latest release)',
    'Change in the level of a composite index based on 8 economic indicators;',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Released monthly, about 24 days after the month ends;',
    NULL,
    'This index is designed to predict the direction of the economy, but it tends to have a muted impact because most of the indicators used in the calculation are released previously. Source first released in May 2010;',
    NULL,
    '2026-03-25',
    '20:00',
    '0.1%',
    NULL,
    '-0.2%',
    0,
    NULL
),
(
    'EUR',
    'Low',
    'Belgian NBB Business Climate',
    'National Bank of Belgium (latest release)',
    'Level of a composite index based on surveyed manufacturers, builders, services, and trade-related firms;',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Released monthly, around 3 weeks into the current month;',
    NULL,
    'Above 0.0 indicates improving conditions, below indicates worsening conditions. This survey is highly respected due to its source and large sample size. Source changed series calculation formula as of April 2009;',
    NULL,
    '2026-03-25',
    '21:00',
    '-13.7',
    '-14.8',
    '-13.7',
    0,
    NULL
),
(
    'US',
    'Low',
    'Crude Oil Inventories',
    'Energy Information Administration (latest release)',
    'Change in the number of barrels of crude oil held in inventory by commercial firms during the past week;',
    '''Actual'' less than ''Forecast'' is good for currency;',
    'Released weekly, 4 days after the week ends;',
    NULL,
    'While this is a US indicator, it most affects the loonie due to Canada''s sizable energy sector;',
    NULL,
    '2026-03-25',
    '21:30',
    '6.2M',
    '-1.3M',
    '6.9M',
    0,
    NULL
),
(
    'JPN',
    'Low',
    'SPPI y/y',
    'Bank of Japan (latest release)',
    'Change in the price of services purchased by corporations;',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Released monthly, about 25 days after the month ends;',
    NULL,
    NULL,
    'It''s a leading indicator of consumer inflation - when corporations pay more for services the higher costs are usually passed on to the consumer;',
    '2026-03-26',
    '06:50',
    '2.6%',
    '2.6%',
    '2.7%',
    0,
    NULL
),
(
    'JPN',
    'Low',
    'BOJ Core CPI y/y',
    'Bank of Japan (latest release)',
    'Change in the price of goods and services purchased by consumers, excluding food and energy;',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Released monthly, usually on the last Friday of the following month;',
    NULL,
    'Food and energy prices account for about a quarter of CPI, but they tend to be very volatile and distort the underlying trend. The BOJ usually pays the more attention to the Core data - so do traders. There''s a revised version of this indicator released about 5 days later, but it''s not included for lack of significance. Source first released in Nov 2015;',
    NULL,
    '2026-03-26',
    '12:02',
    '1.7%',
    '1.6%',
    '1.7%',
    0,
    NULL
),
(
    'EUR',
    'Low',
    'German GfK Consumer Climate',
    'GfK (latest release)',
    'Tingkat indeks gabungan berdasarkan konsumen yang disurvei;',
    '''Aktual'' lebih besar dari ''Perkiraan'' bagus untuk mata uang;',
    'Dirilis setiap bulan, sekitar akhir bulan berjalan;',
    NULL,
    'Di atas 0 menunjukkan optimisme, di bawah menunjukkan pesimisme;',
    'Kepercayaan finansial merupakan indikator utama belanja konsumen, yang menyumbang sebagian besar aktivitas perekonomian secara keseluruhan;',
    '2026-03-26',
    '14:00',
    '-24.8',
    '-27.3',
    '-28.0',
    0,
    NULL
),
(
    'EUR',
    'Low',
    'M3 Money Supply y/y',
    'Bank Sentral Eropa (ECB)',
    'Perubahan jumlah mata uang dalam negeri yang beredar dan disimpan di bank;',
    'Aktual > Perkiraan = Positif',
    'Rilis bulanan, sekitar 28 hari setelah periode bulan berjalan',
    NULL,
    'Sumber mengubah rumus perhitungan seri pada Mei 2001;',
    'Hal ini berkorelasi positif dengan tingkat suku bunga - pada awal siklus ekonomi, peningkatan jumlah uang beredar menyebabkan pengeluaran dan investasi tambahan, dan kemudian pada siklus tersebut, peningkatan jumlah uang beredar menyebabkan inflasi;',
    '2026-03-26',
    '16:00',
    '3.2%',
    '3.3%',
    '3.0%',
    0,
    NULL
),
(
    'EUR',
    'Low',
    'Private Loans y/y',
    'Bank Sentral Eropa (ECB)',
    'Perubahan nilai total pinjaman baru yang diberikan kepada konsumen dan dunia usaha di sektor swasta;',
    'Aktual > Perkiraan = Positif',
    'Rilis bulanan, sekitar 28 hari setelah periode bulan berjalan',
    NULL,
    NULL,
    'Pinjaman dan pembelanjaan berkorelasi positif - konsumen dan dunia usaha cenderung mencari kredit ketika mereka yakin dengan posisi keuangan mereka di masa depan dan merasa nyaman membelanjakan uangnya;',
    '2026-03-26',
    '16:00',
    '3.0%',
    '3.1%',
    '3.0%',
    0,
    NULL
),
(
    'US',
    'High',
    'Unemployment Claims',
    'Departemen Tenaga Kerja',
    'Jumlah individu yang pertama kali mengajukan asuransi pengangguran selama seminggu terakhir;',
    '''Aktual'' kurang dari ''Perkiraan'' baik untuk mata uang;',
    'Dirilis setiap minggu, biasanya pada hari Kamis pertama setelah minggu berakhir;',
    'No Information',
    'Ini adalah data ekonomi negara yang paling awal. Dampak pasar berfluktuasi dari minggu ke minggu - cenderung lebih fokus pada rilis ketika pedagang perlu mendiagnosis perkembangan terkini, atau ketika angkanya ekstrem;',
    'Meskipun secara umum angka ini dipandang sebagai indikator tertinggal, jumlah pengangguran merupakan sinyal penting mengenai kesehatan perekonomian secara keseluruhan karena belanja konsumen sangat berkorelasi dengan kondisi pasar tenaga kerja. Pengangguran juga merupakan pertimbangan utama bagi mereka yang mengendalikan kebijakan moneter negara tersebut;',
    '2026-03-26',
    '19:30',
    '205K',
    '211K',
    '210K',
    0,
    NULL
),
(
    'US',
    'Low',
    'Natural Gas Storage',
    'Administrasi Informasi Energi',
    'Perubahan jumlah kubik feet dari gas alam yang disimpan di gudang bawah tanah selama seminggu sebelumnya;',
    '''Aktual'' kurang dari ''Perkiraan'' baik untuk mata uang;',
    'Rilis mingguan, sekitar 5 hari setelah minggu berjalan',
    NULL,
    'Persediaan digunakan untuk menjaga stabilitas harga selama kekurangan pasokan dan periode peningkatan permintaan;',
    NULL,
    '2026-03-26',
    '21:30',
    '35B',
    NULL,
    NULL,
    0,
    NULL
),
(
    'GBP',
    'Low',
    'GfK Consumer Confidence',
    'NIQ (latest release)',
    'Level of a diffusion index based on surveyed consumers;',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Released monthly, usually on the third Friday of the current month;',
    NULL,
    'Above 0 indicates optimism, below indicates pessimism;',
    NULL,
    '2026-03-27',
    '07:01',
    '-19',
    '-24',
    '-21',
    0,
    NULL
),
(
    'GBP',
    'High',
    'Retail Sales m/m (GBP)',
    'Kantor Statistik Federal',
    'Perubahan nilai total penjualan yang disesuaikan dengan inflasi pada tingkat ritel;',
    'Actual > Forecast = Bagus untuk mata uang',
    'Rilis bulanan, sekitar 20 hari setelah bulan berakhir',
    'No Information',
    'Sumber mengubah rumus perhitungan seri pada Februari 2010;',
    'Ini adalah ukuran utama belanja konsumen, yang menyumbang mayoritas aktivitas ekonomi secara keseluruhan;',
    '2026-03-27',
    '14:00',
    '1.8%',
    '-0.3%',
    NULL,
    0,
    NULL
),
(
    'EUR',
    'Low',
    'Spanish Flash CPI y/y',
    'National Statistics Institute (latest release)',
    'Change in the price of goods and services purchased by consumers;',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Released monthly, around the end of the current month;',
    NULL,
    'There are 2 versions of this report released about two weeks apart - Flash and Final. The Flash release, which the source first reported in Mar 2011, is the earliest and thus tends to have the most impact. The Final is not reported for lack of significance;',
    NULL,
    '2026-03-27',
    '15:00',
    '2.3%',
    '2.4%',
    NULL,
    0,
    NULL
),
(
    'US',
    'Medium',
    'Revised UoM Consumer Sentiment',
    'University of Michigan (latest release)',
    'Level of a composite index based on surveyed consumers;',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Released monthly, usually on the last Friday of the current month;',
    NULL,
    'The ''Previous'' listed is the ''Actual'' from the Preliminary release and therefore the ''History'' data will appear unconnected. There are 2 versions of this data released about 15 days apart ??? Preliminary and Revised. The Preliminary release is the earliest and thus tends to have more impact;',
    NULL,
    '2026-03-27',
    '21:00',
    '55.5',
    '53.9',
    NULL,
    0,
    NULL
),
(
    'US',
    'Low',
    'Revised UoM Inflation Expectations',
    'University of Michigan (latest release)',
    'Percentage that consumers expect the price of goods and services to change during the next 12 months;',
    '''Actual'' greater than ''Forecast'' is good for currency;',
    'Released monthly, usually on the last Friday of the current month;',
    NULL,
    'The ''Previous'' listed is the ''Actual'' from the Preliminary release and therefore the ''History'' data will appear unconnected. There are 2 versions of this data released about 15 days apart ??? Preliminary and Revised. The Preliminary release is the earliest and thus tends to have more impact;',
    NULL,
    '2026-03-27',
    '21:00',
    '3.4%',
    NULL,
    NULL,
    0,
    NULL
),
(
    'US',
    'Low',
    'FOMC Member Williams Speaks',
    'Federal Reserve Bank of New York (latest release)',
    NULL,
    'Lebih hawkish dari yang diharapkan bagus untuk mata uang;',
    NULL,
    'No Information',
    'Anggota pemungutan suara FOMC 2012, 2015, 2018, 2019, dan 2020. Pada Juni 2018 namanya berubah dari Federal Reserve Bank Presiden San Francisco menjadi Federal Reserve Bank Presiden New York;',
    'Anggota Federal Reserve FOMC memberikan suara di mana untuk menetapkan suku bunga utama negara dan keterlibatan publik mereka sering digunakan untuk menjatuhkan petunjuk halus mengenai kebijakan moneter masa depan;',
    '2026-03-27',
    '21:55',
    NULL,
    NULL,
    NULL,
    0,
    NULL
),
(
    'EUR',
    'Low',
    'ECOFIN Meetings',
    'European Council (latest release)',
    NULL,
    NULL,
    NULL,
    NULL,
    'ECOFIN meetings are usually held in Brussels and attended by Finance Ministers from EU member states. They discuss a range of financial issues, such as euro support mechanisms and government finances. The meetings are closed to the press but officials usually talk with reporters throughout the day, and a formal statement covering meeting objectives may be released after the meetings have concluded;',
    NULL,
    '2026-03-27',
    'All Day',
    NULL,
    NULL,
    NULL,
    0,
    NULL
),
(
    'US',
    'Low',
    'Fed Monetary Policy Report',
    'Federal Reserve (latest release)',
    NULL,
    'More hawkish than expected is good for currency;',
    'Twice per year;',
    'No Information',
    'Report provides a summary of discussions of the conduct of monetary policy and economic developments and prospects for the future. It is submitted, along with testimony from the Federal Reserve Chair, to the Senate Committee on Banking, Housing, and Urban',
    NULL,
    '2026-03-27',
    'Tentative',
    NULL,
    NULL,
    NULL,
    0,
    NULL
);

INSERT INTO economic_calendar_categories (
    country,
    impact,
    figures,
    sources,
    measures,
    usual_effect,
    frequency,
    next_released,
    notes,
    isBankHoliday,
    bankHolidayNote,
    why_trader_care,
    created_at,
    updated_at
)
SELECT DISTINCT
    seed.country,
    seed.impact,
    seed.figures,
    seed.sources,
    seed.measures,
    seed.usual_effect,
    seed.frequency,
    seed.next_released,
    seed.notes,
    seed.isBankHoliday,
    seed.bankHolidayNote,
    seed.why_trader_care,
    NOW(),
    NOW()
FROM tmp_economic_payload_seed AS seed
ON DUPLICATE KEY UPDATE
    sources = VALUES(sources),
    measures = VALUES(measures),
    usual_effect = VALUES(usual_effect),
    frequency = VALUES(frequency),
    next_released = VALUES(next_released),
    notes = VALUES(notes),
    isBankHoliday = VALUES(isBankHoliday),
    bankHolidayNote = VALUES(bankHolidayNote),
    why_trader_care = VALUES(why_trader_care),
    updated_at = NOW();

DELETE ec
FROM economic_calendars AS ec
JOIN economic_calendar_categories AS cat
    ON cat.id = ec.economic_calendar_category_id
JOIN (
    SELECT DISTINCT country, impact, figures
    FROM tmp_economic_payload_seed
) AS src
    ON src.country = cat.country
   AND src.impact = cat.impact
   AND src.figures = cat.figures;

INSERT INTO economic_calendars (
    economic_calendar_category_id,
    date,
    time,
    country,
    impact,
    figures,
    previous,
    forecast,
    actual,
    sources,
    measures,
    usual_effect,
    frequency,
    next_released,
    notes,
    isBankHoliday,
    bankHolidayNote,
    why_trader_care,
    created_at,
    updated_at
)
SELECT
    cat.id,
    seed.detail_date,
    seed.detail_time,
    cat.country,
    cat.impact,
    cat.figures,
    seed.previous_value,
    seed.forecast_value,
    seed.actual_value,
    cat.sources,
    cat.measures,
    cat.usual_effect,
    cat.frequency,
    cat.next_released,
    cat.notes,
    cat.isBankHoliday,
    cat.bankHolidayNote,
    cat.why_trader_care,
    NOW(),
    NOW()
FROM tmp_economic_payload_seed AS seed
JOIN economic_calendar_categories AS cat
    ON cat.country = seed.country
   AND cat.impact = seed.impact
   AND cat.figures = seed.figures
ORDER BY seed.detail_date DESC, seed.detail_time DESC, cat.id DESC;

COMMIT;
